#! /bin/sh
# 
# usage: runtest [<testfile>...]
# without args, runs all *.test files in the current directory   
#
TESTFILES=$*
if [ "x$TESTFILES" = "x" ]; then TESTFILES='*.test'; fi
if [ ! -d work ];  then mkdir work; fi
opp_test -g -v $TESTFILES || exit 1
echo
(cd work; opp_makemake -f -u cmdenv; make) || exit 1
echo
opp_test -r -v $TESTFILES || exit 1
echo
echo Results can be found in ./work
