module ZOrder
{
    @display("bgb=1200,1200");

    @figure[t0] (type=text; text=Figures should appear cascaded; pos=100,100);
//TODO
//    @figure[o3] (type=rectangle; fillColor=#40ff40; pos=300,300; size=500,500; anchor=nw; zIndex=3);
//    @figure[o3a](type=rectangle; fillColor=#40ff40; pos=330,330; size=500,500; anchor=nw; zIndex=3);
//    @figure[o3b](type=rectangle; fillColor=#40ff40; pos=360,360; size=500,500; anchor=nw; zIndex=3);
//    @figure[o4] (type=rectangle; fillColor=#60ff60; pos=400,400; size=500,500; anchor=nw; zIndex=4);
//    @figure[o1] (type=rectangle; fillColor=#00ff00; pos=500,500; size=500,500; anchor=nw; zIndex=1);
//    @figure[o5] (type=rectangle; fillColor=#80ff80; pos=500,500; size=500,500; anchor=nw; zIndex=5);
//    @figure[o2] (type=rectangle; fillColor=#20ff20; pos=200,200; size=500,500; anchor=nw; zIndex=2);
}

