module Anchor
{
    @display("bgb=800,500");

    @figure[n](type=oval;coords=100,100;size=50,50;anchor=n;fillcolor=#a0a0ff);
    @figure[e](type=oval;coords=100,100;size=50,50;anchor=e;fillcolor=#a0a0ff);
    @figure[w](type=oval;coords=100,100;size=50,50;anchor=w;fillcolor=#a0a0ff);
    @figure[s](type=oval;coords=100,100;size=50,50;anchor=s;fillcolor=#a0a0ff);

    @figure[ne](type=oval;coords=200,100;size=50,50;anchor=ne;fillcolor=#a0ffa0);
    @figure[nw](type=oval;coords=200,100;size=50,50;anchor=nw;fillcolor=#a0ffa0);
    @figure[se](type=oval;coords=200,100;size=50,50;anchor=se;fillcolor=#a0ffa0);
    @figure[sw](type=oval;coords=200,100;size=50,50;anchor=sw;fillcolor=#a0ffa0);
}

