module Arc
{
    @class(ArrangeFigures);
    @display("bgb=1000,1000");

    @figure[ar1](type=arc;pos=10,0;size=40,10;startAngle=0;endAngle=250);
    @figure[ar3](type=arc;pos=10,0;size=40,10;startAngle=0;endAngle=250;lineColor=#ff0000);
    @figure[ar4](type=arc;pos=10,0;size=40,10;startAngle=0;endAngle=250;lineWidth=3);
    @figure[ar5](type=arc;pos=10,0;size=40,10;startAngle=0;endAngle=250;lineStyle=solid);
    @figure[ar6](type=arc;pos=10,0;size=40,10;startAngle=0;endAngle=250;lineStyle=dotted);
    @figure[ar7](type=arc;pos=10,0;size=40,10;startAngle=0;endAngle=250;lineStyle=dashed);
    @figure[ar8](type=arc;pos=10,0;size=40,10;startAngle=0;endAngle=250;lineColor=#ff0000;lineWidth=3;lineStyle=dashed);
}

