module Arc
{
    @class(ArrangeFigures);
    @arrange(startPos=50,100; lineSpacing=120; columnWidth=70);
    @display("bgb=1200,2000");
    
    @addColumn[0](endAngle=-420; lineWidth=2; startArrowhead=simple; endArrowhead=triangle);
    @addColumn[1](endAngle=-360; lineWidth=2; startArrowhead=simple; endArrowhead=triangle);
    @addColumn[2](endAngle=-300; lineWidth=2; startArrowhead=simple; endArrowhead=triangle);
    @addColumn[3](endAngle=-240; lineWidth=2; startArrowhead=simple; endArrowhead=triangle);
    @addColumn[4](endAngle=-180; lineWidth=2; startArrowhead=simple; endArrowhead=triangle);
    @addColumn[5](endAngle=-120; lineWidth=2; startArrowhead=simple; endArrowhead=triangle);
    @addColumn[6](endAngle=-60; lineWidth=2; startArrowhead=simple; endArrowhead=triangle);
    @addColumn[7](endAngle=0; lineWidth=2; startArrowhead=simple; endArrowhead=triangle);
    @addColumn[8](endAngle=60; lineWidth=2; startArrowhead=simple; endArrowhead=triangle);
    @addColumn[9](endAngle=120; lineWidth=2; startArrowhead=simple; endArrowhead=triangle);
    @addColumn[10](endAngle=180; lineWidth=2; startArrowhead=simple; endArrowhead=triangle);
    @addColumn[11](endAngle=240; lineWidth=2; startArrowhead=simple; endArrowhead=triangle);
    @addColumn[12](endAngle=300; lineWidth=2; startArrowhead=simple; endArrowhead=triangle);
    @addColumn[13](endAngle=360; lineWidth=2; startArrowhead=simple; endArrowhead=triangle);
    @addColumn[14](endAngle=420; lineWidth=2; startArrowhead=simple; endArrowhead=triangle);

    @figure[ar01](type=arc; pos=0,0; size=50,100; startAngle=-420);
    @figure[ar02](type=arc; pos=0,0; size=50,100; startAngle=-360);
    @figure[ar03](type=arc; pos=0,0; size=50,100; startAngle=-300);
    @figure[ar04](type=arc; pos=0,0; size=50,100; startAngle=-240);
    @figure[ar05](type=arc; pos=0,0; size=50,100; startAngle=-180);
    @figure[ar06](type=arc; pos=0,0; size=50,100; startAngle=-120);
    @figure[ar07](type=arc; pos=0,0; size=50,100; startAngle=-60);
    @figure[ar08](type=arc; pos=0,0; size=50,100; startAngle=0);
    @figure[ar09](type=arc; pos=0,0; size=50,100; startAngle=60);
    @figure[ar10](type=arc; pos=0,0; size=50,100; startAngle=120);
    @figure[ar11](type=arc; pos=0,0; size=50,100; startAngle=180);
    @figure[ar12](type=arc; pos=0,0; size=50,100; startAngle=240);
    @figure[ar13](type=arc; pos=0,0; size=50,100; startAngle=300);
    @figure[ar14](type=arc; pos=0,0; size=50,100; startAngle=360);
    @figure[ar15](type=arc; pos=0,0; size=50,100; startAngle=420);
}

