module Oval
{
    @class(ArrangeFigures);
    @display("bgb=1000,1200");

    @figure[ov1](type=oval; pos=10,0; size=190,10);
    @figure[ov2](type=oval; pos=10,0; size=190,10; fillColor=#0000ff);
    @figure[ov3](type=oval; pos=10,0; size=190,10; lineColor=#ff0000);
    @figure[ov4](type=oval; pos=10,0; size=190,10; lineWidth=3);
    @figure[ov5](type=oval; pos=10,0; size=190,10; lineStyle=solid);
    @figure[ov6](type=oval; pos=10,0; size=190,10; lineStyle=dotted);
    @figure[ov7](type=oval; pos=10,0; size=190,10; lineStyle=dashed);
    @figure[ov8](type=oval; pos=10,0; size=190,10; fillColor=#0000ff; lineColor=#ff0000; lineWidth=3; lineStyle=dashed);
}

