module Polygon
{
    @class(ArrangeFigures);
    @display("bgb=1000,1200");

    @figure[pgn00](type=polygon; points=10,0,30,18,100,5,200,5,200,0);
    @figure[pgn01](type=polygon; points=10,0,30,18,100,5,200,5,200,0; fillColor=#808080);
    @figure[pgn02](type=polygon; points=10,0,30,18,100,5,200,5,200,0; fillColor=#808080; lineColor=#00ff00);
    @figure[pgn04](type=polygon; points=10,0,30,18,100,5,200,5,200,0; fillColor=#808080; lineStyle=solid);
    @figure[pgn05](type=polygon; points=10,0,30,18,100,5,200,5,200,0; fillColor=#808080; lineStyle=dashed);
    @figure[pgn06](type=polygon; points=10,0,30,18,100,5,200,5,200,0; fillColor=#808080; lineStyle=dotted);
    @figure[pgn09](type=polygon; points=10,0,30,18,100,5,200,5,200,0; fillColor=#808080; lineWidth=3; lineStyle=solid);
    @figure[pgn08](type=polygon; points=10,0,30,18,100,5,200,5,200,0; fillColor=#808080; lineWidth=3; lineStyle=dashed);
    @figure[pgn10](type=polygon; points=10,0,30,18,100,5,200,5,200,0; fillColor=#808080; lineWidth=3; lineStyle=dotted);

    @figure[pgn20](type=polygon; points=10,0,30,18,100,5,200,5,200,0; smooth=true);
    @figure[pgn21](type=polygon; points=10,0,30,18,100,5,200,5,200,0; smooth=true; fillColor=#808080);
    @figure[pgn22](type=polygon; points=10,0,30,18,100,5,200,5,200,0; smooth=true; fillColor=#808080; lineColor=#00ff00);
    @figure[pgn24](type=polygon; points=10,0,30,18,100,5,200,5,200,0; smooth=true; fillColor=#808080; lineStyle=solid);
    @figure[pgn25](type=polygon; points=10,0,30,18,100,5,200,5,200,0; smooth=true; fillColor=#808080; lineStyle=dashed);
    @figure[pgn26](type=polygon; points=10,0,30,18,100,5,200,5,200,0; smooth=true; fillColor=#808080; lineStyle=dotted);
    @figure[pgn29](type=polygon; points=10,0,30,18,100,5,200,5,200,0; smooth=true; fillColor=#808080; lineWidth=3; lineStyle=solid);
    @figure[pgn28](type=polygon; points=10,0,30,18,100,5,200,5,200,0; smooth=true; fillColor=#808080; lineWidth=3; lineStyle=dashed);
    @figure[pgn30](type=polygon; points=10,0,30,18,100,5,200,5,200,0; smooth=true; fillColor=#808080; lineWidth=3; lineStyle=dotted);
}

