module Tags
{
    @display("bgb=800,500");

    @figure[a](type=rectangle;position=100,100;size=50,50;fillColor=green1;tags=green,rect);
    @figure[b](type=oval;     position=200,100;size=50,50;fillColor=green2;tags=green,oval);
    @figure[c](type=rectangle;position=100,200;size=50,50;fillColor=blue1;tags=blue,rect);
    @figure[d](type=oval;     position=200,200;size=50,50;fillColor=blue2;tags=blue,oval);
}

