module Tags
{
    @display("bgb=800,500");

    @figure[a](type=rectangle;coords=100,100;size=50,50;fillColor=#a0ffa0;tags=green,rect);
    @figure[b](type=oval;     coords=200,100;size=50,50;fillColor=#a0ffa0;tags=green,oval);
    @figure[c](type=rectangle;coords=100,200;size=50,50;fillColor=#a0a0ff;tags=blue,rect);
    @figure[d](type=oval;     coords=200,200;size=50,50;fillColor=#a0a0ff;tags=blue,oval);
}

