#! /bin/sh
sed '' header.tcl
for i in `sed '' <$1`; do
  name=`echo $i|sed 's/^.*\///;s/\.gif$//'`
  echo "set icons($name) [image create photo -data {"
  # on Linux, base64 is called mimencode
  # WARNING!!!!! cygwin bash does not like input redirection!!!!!!!
  # data loss!!!!!
  ../scripts/base64 -i $i | sed 's/^/    /'
  echo "}]"
  echo
done
