#! /bin/sh

case "$-" in
*i*) ;;
*)  if [ "$1" != "-f" ]; then # allow use from scripts, as ". setenv -f"
        echo "Error: not a login shell -- run this script as 'source setenv' or '. setenv'"
        exit 1
    fi
esac

if [ ! -f configure.user -o ! -f include/omnetpp.h ]; then
    echo "Error: current working directory does not look like an OMNeT++ root directory"
    # no exit -- it would close the shell
else
    omnetpp_root=`pwd`
    echo $omnetpp_root
    if [ `uname` = "Darwin" ]; then
      if [ ! -d $omnetpp_root/tools/macosx ]; then
          echo "WARNING! We are on Mac OS X, but it seems that you have downloaded the Linux version of the installation package!"
      fi
      export PATH=$omnetpp_root/tools/macosx/bin:$PATH
      export QT_PLUGIN_PATH=$omnetpp_root/tools/macosx/plugins
    fi
    export PATH=$omnetpp_root/bin:$PATH
    export HOSTNAME
    export HOST
fi

