#define yy_create_buffer nedyy_create_buffer
#define yy_delete_buffer nedyy_delete_buffer
#define yy_scan_buffer nedyy_scan_buffer
#define yy_scan_string nedyy_scan_string
#define yy_scan_bytes nedyy_scan_bytes
#define yy_flex_debug nedyy_flex_debug
#define yy_init_buffer nedyy_init_buffer
#define yy_flush_buffer nedyy_flush_buffer
#define yy_load_buffer_state nedyy_load_buffer_state
#define yy_switch_to_buffer nedyy_switch_to_buffer
#define yyin nedyyin
#define yyleng nedyyleng
#define yylex nedyylex
#define yyout nedyyout
#define yyrestart nedyyrestart
#define yytext nedyytext
#define yywrap nedyywrap

/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 114
#define YY_END_OF_BUFFER 115
static yyconst short int yy_accept[368] =
    {   0,
        0,    0,    0,    0,  115,  113,  112,  112,   93,  113,
       96,  105,   95,  113,   82,   83,  103,  101,   79,  102,
       88,  104,   67,   67,   80,   78,  108,   81,  110,   89,
       66,   84,   85,  100,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,   86,   94,   87,   97,   76,   75,   75,   76,
      107,    0,   71,   92,   91,    0,   77,    2,   34,   70,
        1,    0,   67,    0,    0,    0,   98,  109,  106,  111,
       99,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,    9,   66,   66,   66,   66,   66,   66,   66,

       37,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       30,   66,   66,   66,   66,   66,   66,   66,   66,   36,
       66,   66,   66,   73,   90,   74,   72,   32,   35,    0,
        0,   69,   68,   33,   66,   66,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   66,    8,   66,   66,   25,   66,   66,   59,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   12,   66,   66,   66,   66,   66,   66,   66,   44,
        0,   70,   66,   66,   66,   43,   66,   57,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,

       66,   51,   66,   66,   66,   66,   66,   66,   66,   66,
       31,   60,   66,   66,   66,   66,   66,   66,   26,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   10,   66,
       66,   66,   66,   66,   66,   49,   66,   15,   66,   66,
       63,   66,   66,   66,   66,   66,   66,   66,   64,   66,
       11,   66,   23,   66,   38,   14,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   58,   66,   66,   66,   66,
       66,   66,   66,   66,   66,   66,   66,   66,   66,   66,
       66,   61,   66,   21,   66,   66,   66,   66,   53,   66,
        3,   66,    5,   66,   66,   66,   66,   66,   66,   66,

        6,   16,   42,   47,   66,   66,   40,   66,   66,   45,
        7,   66,   66,   66,   29,   66,   66,   66,   66,   52,
       66,   48,    4,   39,   66,   41,   66,   66,   66,   66,
       66,   55,   13,   66,   66,   65,   66,   66,   66,   66,
       66,   66,   66,   66,   56,   66,   62,   66,   46,   66,
       18,   66,   17,   24,   66,   66,   66,   66,   66,   19,
       20,   50,   22,   54,   27,   28,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   19,   19,
       19,   19,   19,   19,   19,   19,   19,   20,   21,   22,
       23,   24,   25,    1,   26,   26,   26,   26,   27,   26,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,
       28,   28,   28,   28,   28,   28,   28,   29,   28,   28,
       30,    1,   31,   32,   28,    1,   33,   34,   35,   36,

       37,   38,   39,   40,   41,   42,   43,   44,   45,   46,
       47,   48,   28,   49,   50,   51,   52,   28,   53,   54,
       55,   56,   57,   58,   59,   60,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[61] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    3,    1,
        1,    1,    1,    1,    1,    3,    3,    4,    4,    1,
        1,    1,    3,    3,    3,    3,    3,    3,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[373] =
    {   0,
        0,    0,   59,   61,  415,  416,  416,  416,  391,  408,
      406,  416,  403,    0,  416,  416,  416,  397,  416,  394,
       49,  391,   53,   57,  416,  416,   55,  384,   62,  416,
        0,  416,  416,  416,   45,  359,   48,   56,   52,   67,
      372,   64,   40,   68,   74,   67,   50,  367,   76,   75,
      357,  357,  344,  342,  416,  416,  416,  416,  416,  340,
      416,  393,  416,  416,  416,  388,  416,  372,  379,  111,
      416,  113,  117,  124,    0,  379,  416,  416,  416,  416,
      416,    0,  343,   90,  345,  358,  357,  343,  344,  336,
      342,  335,  332,   98,  334,  331,  337,  343,  330,  327,

        0,  329,  120,  333,  329,  324,  337,  321,   77,  326,
        0,  319,  320,  321,  108,  320,  102,  317,  331,    0,
      312,  313,  318,  416,  416,  416,  416,  416,  416,  142,
      133,  144,    0,  416,  310,  323,  308,  314,  118,  307,
      103,  304,  322,  321,  305,  318,  131,  306,  303,  312,
      298,  303,    0,  309,  298,  416,  307,  291,    0,  305,
      302,  290,  287,  285,  297,  301,  298,  314,  300,  284,
      295,    0,  281,  281,  291,  118,  282,  289,  284,  288,
      154,  156,  274,  272,  266,    0,  274,    0,  269,  281,
      266,  266,  266,  259,  269,  268,  271,  263,  262,  271,

      266,    0,  257,  259,  267,  267,  252,  252,  246,  248,
        0,    0,  265,  253,  249,  258,  247,  244,  416,  247,
      254,  243,  238,  244,  240,  240,  250,  237,    0,  244,
      235,  248,  229,  231,  241,    0,  242,    0,  228,  242,
        0,  241,  236,  239,  222,  234,  218,  223,    0,  231,
        0,  216,  224,  213,    0,    0,  224,  225,  212,  225,
      225,  217,  220,  207,  209,    0,  217,  215,  213,  200,
      214,  203,  213,  212,  199,  208,  200,  192,  198,  190,
      185,    0,  193,    0,  186,  184,  188,  185,    0,  178,
        0,  196,    0,  189,  188,  188,  194,  177,  176,  182,

        0,    0,    0,    0,  173,  187,    0,  172,  173,    0,
        0,  180,  168,  182,    0,  172,  173,  169,  171,    0,
      177,    0,    0,    0,  176,    0,  175,  170,  155,  165,
      172,    0,    0,  160,  156,    0,  168,  167,  154,  165,
      151,  165,  150,  161,    0,  160,    0,  150,    0,  147,
        0,  137,    0,    0,  128,  128,  115,   54,   24,    0,
        0,    0,    0,    0,    0,    0,  416,  181,  185,  189,
      191,   63
    } ;

static yyconst short int yy_def[373] =
    {   0,
      367,    1,  368,  368,  367,  367,  367,  367,  367,  369,
      367,  367,  367,  370,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      371,  367,  367,  367,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  369,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  372,  367,  367,  367,  367,  367,
      367,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  372,  367,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  367,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      367,  367,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  367,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,

      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,  371,  371,  371,  371,
      371,  371,  371,  371,  371,  371,    0,  367,  367,  367,
      367,  367
    } ;

static yyconst short int yy_nxt[477] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   31,   31,   31,   31,   32,
       33,   34,   35,   36,   37,   38,   39,   40,   41,   31,
       42,   31,   31,   43,   44,   45,   46,   47,   48,   49,
       50,   51,   31,   52,   31,   31,   53,   54,   55,   56,
       58,   59,   58,   59,   69,  133,   70,   70,   72,   76,
       73,   73,   72,  366,   73,   73,   77,   78,   83,   74,
      104,   75,  113,   74,   80,   81,  105,   86,   90,   74,
       84,   87,   91,   74,   88,   89,   92,   94,  114,   97,

       95,  101,   93,  365,  106,   96,   75,   98,  102,  103,
      108,  165,  111,   99,  107,  116,  117,   60,  112,   60,
      109,  120,  166,  121,  136,  110,  118,  119,   70,   70,
       70,   70,   72,  147,   73,   73,  131,  130,  131,  156,
      171,  132,  132,   74,  137,  172,  174,  130,  190,  148,
      132,  132,  191,   74,  181,  157,  181,  175,  226,  182,
      182,  132,  132,  187,  364,  197,  188,  158,  198,  227,
      159,  182,  182,  182,  182,  199,  200,  363,  362,  361,
      201,   57,   57,   57,   57,   62,   62,   62,   62,   66,
      360,   66,   66,   82,   82,  359,  358,  357,  356,  355,

      354,  353,  352,  351,  350,  349,  348,  347,  346,  345,
      344,  343,  342,  341,  340,  339,  338,  337,  336,  335,
      334,  333,  332,  331,  330,  329,  328,  327,  326,  325,
      324,  323,  322,  321,  320,  319,  318,  317,  316,  315,
      314,  313,  312,  311,  310,  309,  308,  307,  306,  305,
      304,  303,  302,  301,  300,  299,  298,  297,  296,  295,
      294,  293,  292,  291,  290,  289,  288,  287,  286,  285,
      284,  283,  282,  281,  280,  279,  278,  277,  276,  275,
      274,  273,  272,  271,  270,  269,  268,  267,  266,  265,
      264,  263,  262,  261,  260,  259,  258,  257,  256,  255,

      254,  253,  252,  251,  250,  249,  248,  247,  246,  245,
      244,  243,  242,  241,  240,  239,  238,  237,  236,  235,
      234,  233,  232,  231,  230,  229,  228,  225,  224,  223,
      222,  221,  220,  219,  218,  217,  216,  215,  214,  213,
      212,  211,  210,  209,  208,  207,  206,  205,  204,  203,
      202,  196,  195,  194,  193,  192,  189,  186,  185,  184,
      183,  180,  179,  178,  177,  176,  173,  170,  169,  168,
      167,  164,  163,  162,  161,  160,  155,  154,  153,  152,
      151,  150,  149,  146,  145,  144,  143,  142,  141,  140,
      139,  138,  135,  134,  129,  128,  127,   63,  126,  125,

      124,  123,  122,  115,  100,   85,   79,   71,   68,   67,
       65,   64,   63,   61,  367,    5,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367
    } ;

static yyconst short int yy_chk[477] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        3,    3,    4,    4,   21,  372,   21,   21,   23,   27,
       23,   23,   24,  359,   24,   24,   27,   27,   35,   23,
       43,   23,   47,   24,   29,   29,   43,   37,   38,   23,
       35,   37,   38,   24,   37,   37,   38,   39,   47,   40,

       39,   42,   38,  358,   44,   39,   23,   40,   42,   42,
       45,  109,   46,   40,   44,   49,   49,    3,   46,    4,
       45,   50,  109,   50,   84,   45,   49,   49,   70,   70,
       72,   72,   73,   94,   73,   73,   74,   70,   74,  103,
      115,   74,   74,   73,   84,  115,  117,   70,  141,   94,
      131,  131,  141,   73,  130,  103,  130,  117,  176,  130,
      130,  132,  132,  139,  357,  147,  139,  103,  147,  176,
      103,  181,  181,  182,  182,  147,  147,  356,  355,  352,
      147,  368,  368,  368,  368,  369,  369,  369,  369,  370,
      350,  370,  370,  371,  371,  348,  346,  344,  343,  342,

      341,  340,  339,  338,  337,  335,  334,  331,  330,  329,
      328,  327,  325,  321,  319,  318,  317,  316,  314,  313,
      312,  309,  308,  306,  305,  300,  299,  298,  297,  296,
      295,  294,  292,  290,  288,  287,  286,  285,  283,  281,
      280,  279,  278,  277,  276,  275,  274,  273,  272,  271,
      270,  269,  268,  267,  265,  264,  263,  262,  261,  260,
      259,  258,  257,  254,  253,  252,  250,  248,  247,  246,
      245,  244,  243,  242,  240,  239,  237,  235,  234,  233,
      232,  231,  230,  228,  227,  226,  225,  224,  223,  222,
      221,  220,  218,  217,  216,  215,  214,  213,  210,  209,

      208,  207,  206,  205,  204,  203,  201,  200,  199,  198,
      197,  196,  195,  194,  193,  192,  191,  190,  189,  187,
      185,  184,  183,  180,  179,  178,  177,  175,  174,  173,
      171,  170,  169,  168,  167,  166,  165,  164,  163,  162,
      161,  160,  158,  157,  155,  154,  152,  151,  150,  149,
      148,  146,  145,  144,  143,  142,  140,  138,  137,  136,
      135,  123,  122,  121,  119,  118,  116,  114,  113,  112,
      110,  108,  107,  106,  105,  104,  102,  100,   99,   98,
       97,   96,   95,   93,   92,   91,   90,   89,   88,   87,
       86,   85,   83,   76,   69,   68,   66,   62,   60,   54,

       53,   52,   51,   48,   41,   36,   28,   22,   20,   18,
       13,   11,   10,    9,    5,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367,  367,  367,  367,  367,
      367,  367,  367,  367,  367,  367
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ned.lex"
#define INITIAL 0
#define cplusplusbody 1

#line 11 "ned.lex"
/*==================================================
 * File: ned.lex
 *
 *  Lexical analyser for OMNeT++ NED.
 *
 *  Author: Andras Varga
 *
 *  Based on code from nedc.
 *
 ==================================================*/

/*--------------------------------------------------------------*
  Copyright (C) 1992,2002 Andras Varga

  This file is distributed WITHOUT ANY WARRANTY. See the file
  `license' for details on this and other legal matters.
*--------------------------------------------------------------*/


#include <string.h>

#if defined(__BORLANDC__)
# include <io.h>
# pragma warn -rch  /*turn off tons of 'Unreachable code' warnings --VA */
#elif defined(_MSC_VER)
# include <io.h>
# define isatty _isatty
# pragma warning(disable:4996) /* disable VC8.0 warnings on fileno(), etc */
#else
//extern "C" { int isatty(int); }
# include <unistd.h>
#endif

#include "nedgrammar.h"
#include "ned.tab.h"

extern YYSTYPE yylval;
extern YYLTYPE yylloc;

void comment(void);
void count(void);
void extendCount(void);

#define WARN(m) \
        sprintf (yyfailure, "! %s", m); \
        yyerror (""); \
        yyfailure [0] = 0;

/* Vars updated by count(): */
LineColumn pos,prevpos;

#define TEXTBUF_LEN 1024
char textbuf[TEXTBUF_LEN];

#line 664 "lex.nedyy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 67 "ned.lex"

#line 817 "lex.nedyy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 368 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 416 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 68 "ned.lex"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 69 "ned.lex"
{ comment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 71 "ned.lex"
{ count(); use_chanattrname_token = 0; return INCLUDE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 72 "ned.lex"
{ count(); use_chanattrname_token = 0; return NETWORK; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 73 "ned.lex"
{ count(); use_chanattrname_token = 0; return MODULE; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 74 "ned.lex"
{ count(); use_chanattrname_token = 0; return SIMPLE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 75 "ned.lex"
{ count(); use_chanattrname_token = 1; return CHANNEL; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 76 "ned.lex"
{ count(); return FOR; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 77 "ned.lex"
{ count(); return DO; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 78 "ned.lex"
{ count(); return TRUE_; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 79 "ned.lex"
{ count(); return FALSE_; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 80 "ned.lex"
{ count(); return REF; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 81 "ned.lex"
{ count(); return ANCESTOR; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 82 "ned.lex"
{ count(); return INPUT_; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 83 "ned.lex"
{ count(); return CONSTDECL; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 84 "ned.lex"
{ count(); return SIZEOF; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 85 "ned.lex"
{ count(); return ENDSIMPLE; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 86 "ned.lex"
{ count(); return ENDMODULE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 87 "ned.lex"
{ count(); return ENDCHANNEL; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 88 "ned.lex"
{ count(); return ENDNETWORK; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 89 "ned.lex"
{ count(); return ENDFOR; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 90 "ned.lex"
{ count(); return PARAMETERS; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 91 "ned.lex"
{ count(); return GATES; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 92 "ned.lex"
{ count(); return GATESIZES; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 93 "ned.lex"
{ count(); return IN; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 94 "ned.lex"
{ count(); return OUT; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 95 "ned.lex"
{ count(); return SUBMODULES; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 96 "ned.lex"
{ count(); return CONNECTIONS; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 97 "ned.lex"
{ count(); return DISPLAY; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 98 "ned.lex"
{ count(); return ON; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 99 "ned.lex"
{ count(); return LIKE; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 100 "ned.lex"
{ count(); return RIGHT_ARROW; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 101 "ned.lex"
{ count(); return LEFT_ARROW; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 102 "ned.lex"
{ count(); return TO; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 103 "ned.lex"
{ count(); return TO; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 104 "ned.lex"
{ count(); return TO; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 105 "ned.lex"
{ count(); return IF; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 106 "ned.lex"
{ count(); return SUBMODINDEX; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 107 "ned.lex"
{ count(); return NOCHECK; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 108 "ned.lex"
{ count(); return XMLDOC; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 110 "ned.lex"
{ count(); return NUMERICTYPE; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 111 "ned.lex"
{ count(); return STRINGTYPE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 112 "ned.lex"
{ count(); return BOOLTYPE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 113 "ned.lex"
{ count(); return XMLTYPE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 114 "ned.lex"
{ count(); return ANYTYPE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 116 "ned.lex"
{ count(); use_chanattrname_token = 0; return CPLUSPLUS; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 117 "ned.lex"
{ count(); use_chanattrname_token = 0; return STRUCT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 118 "ned.lex"
{ count(); use_chanattrname_token = 0; return MESSAGE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 119 "ned.lex"
{ count(); use_chanattrname_token = 0; return CLASS; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 120 "ned.lex"
{ count(); use_chanattrname_token = 0; return NONCOBJECT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 121 "ned.lex"
{ count(); use_chanattrname_token = 0; return ENUM; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 122 "ned.lex"
{ count(); return EXTENDS; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 123 "ned.lex"
{ count(); return FIELDS; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 124 "ned.lex"
{ count(); return PROPERTIES; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 125 "ned.lex"
{ count(); return ABSTRACT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 126 "ned.lex"
{ count(); return READONLY; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 128 "ned.lex"
{ count(); return CHARTYPE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 129 "ned.lex"
{ count(); return SHORTTYPE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 130 "ned.lex"
{ count(); return INTTYPE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 131 "ned.lex"
{ count(); return LONGTYPE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 132 "ned.lex"
{ count(); return DOUBLETYPE; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 133 "ned.lex"
{ count(); return UNSIGNED_; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 135 "ned.lex"
{ count(); return use_chanattrname_token ? CHANATTRNAME : NAME; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 136 "ned.lex"
{ count(); return use_chanattrname_token ? CHANATTRNAME : NAME; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 137 "ned.lex"
{ count(); return use_chanattrname_token ? CHANATTRNAME : NAME; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 139 "ned.lex"
{ count(); return NAME; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 140 "ned.lex"
{ count(); return INTCONSTANT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 141 "ned.lex"
{ count(); return INTCONSTANT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 142 "ned.lex"
{ count(); return REALCONSTANT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 143 "ned.lex"
{ count(); return REALCONSTANT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 145 "ned.lex"
{ count(); return STRINGCONSTANT; }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 146 "ned.lex"
{ count(); return CHARCONSTANT; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 148 "ned.lex"
{ count(); BEGIN(cplusplusbody); }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 149 "ned.lex"
{ extendCount(); BEGIN(INITIAL); return CPLUSPLUSBODY; }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 150 "ned.lex"
{ extendCount(); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 151 "ned.lex"
{ extendCount(); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 153 "ned.lex"
{ count(); return PLUSPLUS; }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 155 "ned.lex"
{ count(); return (';'); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 156 "ned.lex"
{ count(); return (','); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 157 "ned.lex"
{ count(); return (':'); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 158 "ned.lex"
{ count(); return ('='); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 159 "ned.lex"
{ count(); return ('('); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 160 "ned.lex"
{ count(); return (')'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 161 "ned.lex"
{ count(); return ('['); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 162 "ned.lex"
{ count(); return (']'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 163 "ned.lex"
{ count(); return ('{'); }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 164 "ned.lex"
{ count(); return ('}'); }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 165 "ned.lex"
{ count(); return ('.'); }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 166 "ned.lex"
{ count(); return ('?'); }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 168 "ned.lex"
{ count(); return OR; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 169 "ned.lex"
{ count(); return AND; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 170 "ned.lex"
{ count(); return XOR; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 171 "ned.lex"
{ count(); return NOT; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 173 "ned.lex"
{ count(); return BIN_OR; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 174 "ned.lex"
{ count(); return BIN_AND; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 175 "ned.lex"
{ count(); return BIN_XOR; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 176 "ned.lex"
{ count(); return BIN_COMPL; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 177 "ned.lex"
{ count(); return SHIFT_LEFT; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 178 "ned.lex"
{ count(); return SHIFT_RIGHT; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 180 "ned.lex"
{ count(); return '^'; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 181 "ned.lex"
{ count(); return '+'; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 182 "ned.lex"
{ count(); return '-'; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 183 "ned.lex"
{ count(); return '*'; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 184 "ned.lex"
{ count(); return '/'; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 185 "ned.lex"
{ count(); return '%'; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 187 "ned.lex"
{ count(); return EQ; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 188 "ned.lex"
{ count(); return NE; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 189 "ned.lex"
{ count(); return LS; }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 190 "ned.lex"
{ count(); return LE; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 191 "ned.lex"
{ count(); return GT; }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 192 "ned.lex"
{ count(); return GE; }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 194 "ned.lex"
{ count(); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 195 "ned.lex"
{ count(); return INVALID_CHAR; }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 197 "ned.lex"
ECHO;
	YY_BREAK
#line 1470 "lex.nedyy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(cplusplusbody):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 368 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 368 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 367);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 197 "ned.lex"


/***************************************************
* yywrap() -created 11 july 1995 alex paalvast
*    used to signal end of inputstream
*    not used with flex (only with lex) --VA
***************************************************/
//#ifndef yywrap
int yywrap(void)
{
         return 1;
}
//#endif

/***************************************************
* comment() -created 6 july 1995 alex paalvast
* - discards all remaining characters of a line of
*   text from the inputstream.
* - the characters are read with the input() and
*   unput() functions.
* - input() is sometimes called yyinput()...
***************************************************/
#ifdef __cplusplus
#define input  yyinput
#endif

/* the following #define is needed for broken flex versions */
#define yytext_ptr yytext

void comment(void)
{
        int c;
        while ((c = input())!='\n' && c!=0 && c!=EOF);
        if (c=='\n') unput(c);
}

/***************************************************
* count() -created 6 july 1995 alex paalvast; edited by VA
* - counts the line and column number of the current token in `pos'
* - keeps a record of the complete current line in `textbuf[]'
* - yytext[] is the current token passed by (f)lex
***************************************************/

void _count(int updateprevpos)
{
        static int textbuflen;
        int i;

        /* printf("DBG: count(): prev=%d,%d  pos=%d,%d yytext=>>%s<<\n",
               prevpos.li, prevpos.co, pos.li, pos.co, yytext);
        */

        /* init textbuf */
        if (pos.li==1 && pos.co==0) {
                textbuf[0]='\0'; textbuflen=0;
        }

        if (updateprevpos) {
                prevpos = pos;
        }
        for (i = 0; yytext[i] != '\0'; i++) {
                if (yytext[i] == '\n') {
                        pos.co = 0;
                        pos.li++;
                        textbuflen=0; textbuf[0]='\0';
                } else if (yytext[i] == '\t')
                        pos.co += 8 - (pos.co % 8);
                else
                        pos.co++;
                if (yytext[i] != '\n') {
                        if (textbuflen < TEXTBUF_LEN-5) {
                            textbuf[textbuflen++]=yytext[i]; textbuf[textbuflen]='\0';
                        }
                        else if (textbuflen == TEXTBUF_LEN-5) {
                            strcpy(textbuf+textbuflen, "...");
                            textbuflen++;
                        } else {
                            /* line too long -- ignore */
                        }
                }
        }
        /* printf("li=%d co=%d\n", pos.li, pos.co); good for debugging... */
        yylloc.first_line   = prevpos.li;
        yylloc.first_column = prevpos.co;
        yylloc.last_line    = pos.li;
        yylloc.last_column  = pos.co;

}

void count(void)
{
    _count(1);
}

void extendCount(void)
{
    _count(0);
}

/***************************************************
* jar_yyrestart() -created by VA
***************************************************/
void jar_yyrestart(FILE *_yyin)
{
#ifdef FLEX_SCANNER
    yyrestart( _yyin );
#endif
}

