/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header$
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 110
#define YY_END_OF_BUFFER 111
static yyconst short int yy_accept[363] =
    {   0,
        0,    0,    0,    0,  111,  109,  108,  108,   89,  109,
       92,  101,   91,  109,   78,   79,   99,   97,   75,   98,
       84,  100,   66,   76,   74,  104,   77,  106,   85,   65,
       80,   81,   96,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       82,   90,   83,   93,   73,  110,   73,  103,    0,   69,
       88,   87,    0,    2,   36,   68,    1,    0,   66,    0,
        0,   94,  105,  102,  107,   95,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   10,   65,   65,
       65,   65,   65,   65,   65,   39,   65,   65,   65,   65,

       65,   65,   65,   65,   65,   65,   31,   65,   65,   65,
       65,   65,   65,   65,   65,   38,   65,   65,   71,   86,
       72,   70,   34,   37,    0,    0,   67,   35,   65,   65,
       65,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,    9,   65,   65,   26,
       65,   65,   65,   58,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   65,   13,   65,   65,   65,
       65,   65,   65,   65,    0,   68,   65,   65,   65,   44,
       65,   56,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   51,   65,   65,   65,   65,

       65,   65,   65,   65,   65,   32,   59,   65,   65,   65,
       65,   65,   65,   65,   27,   65,   65,   65,   65,   65,
       65,   65,   65,   11,   65,   65,   65,   65,   65,   49,
       65,   16,   65,   65,   62,   65,   65,   65,   65,   65,
       65,   65,   63,   65,   12,   65,   24,   65,   65,   40,
       15,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       57,   65,   65,   65,   65,   65,   65,   65,   65,   65,
       65,   65,   65,   65,   65,   60,   65,   22,   65,   65,
       65,   65,   53,   65,    4,   65,   65,   65,    6,   65,
       65,   65,   65,   65,   65,    7,   17,   43,   47,   65,

       65,   65,   65,   45,    8,   65,   65,   65,   30,   65,
       65,   65,   65,   52,   65,    3,   65,   48,    5,   41,
       65,   42,   65,   65,   65,   65,   55,   14,   65,   65,
       64,   65,   65,   65,   65,   65,   33,   65,   65,   65,
       65,   61,   65,   46,   65,   19,   65,   18,   25,   65,
       65,   65,   65,   65,   20,   21,   50,   23,   54,   28,
       29,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        2,    2,    2,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    7,    8,    9,   10,
       11,   12,   13,   14,   15,   16,   17,   18,   18,   18,
       18,   18,   18,   18,   18,   18,   18,   19,   20,   21,
       22,   23,   24,    1,   25,   25,   25,   25,   26,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       25,   25,   25,   25,   25,   25,   25,   25,   25,   25,
       27,    1,   28,   29,   25,    1,   30,   31,   32,   33,

       34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
       44,   45,   25,   46,   47,   48,   49,   25,   50,   51,
       52,   53,   54,   55,   56,   57,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[58] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    1,    1,
        1,    1,    1,    1,    3,    3,    1,    1,    1,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[367] =
    {   0,
        0,    0,   55,   56,  387,  388,  388,  388,  364,  380,
      378,  388,  375,    0,  388,  388,  388,  388,  388,  367,
       44,  364,   45,  388,  388,   51,  358,   42,  388,    0,
      388,  388,  388,   37,  335,   33,   51,   40,   46,  348,
       57,   31,   63,   54,   53,   64,  343,   67,   62,  333,
      321,  319,  388,  388,  388,  388,  317,  388,  367,  388,
      388,  388,  362,  347,  353,   83,  388,  350,  102,  106,
      352,  388,  388,  388,  388,  388,    0,  319,   35,  321,
      334,  333,  319,  320,  312,  318,  311,  308,   80,  310,
      307,  313,  319,  306,  303,    0,  305,  106,  309,  305,

      315,  299,  312,  296,   90,  301,    0,  294,  295,  296,
      304,  294,   81,  291,  305,    0,  286,  287,  388,  388,
      388,  388,  388,  388,  117,  315,  314,  388,  283,  296,
      281,  287,   94,  280,   84,  277,  295,  294,  278,  291,
      110,  279,  276,  285,  271,  276,    0,  282,  271,  388,
      273,  279,  263,    0,  277,  274,  272,  261,  258,  256,
      268,  272,  269,  283,  271,  255,    0,  253,  253,  263,
      106,  254,  261,  256,  275,  274,  245,  243,  237,    0,
      245,    0,  240,  252,  237,  237,  237,  230,  240,  239,
      242,  234,  233,  242,  237,    0,  228,  230,  238,  238,

      223,  223,  219,  216,  218,    0,    0,  227,  234,  222,
      218,  227,  216,  213,  388,  216,  223,  208,  214,  210,
      210,  220,  207,    0,  214,  219,  200,  202,  212,    0,
      213,    0,  199,  213,    0,  212,  207,  210,  193,  205,
      189,  194,    0,  202,    0,  187,  195,  184,  198,    0,
        0,  187,  193,  194,  181,  194,  194,  186,  189,  176,
        0,  187,  185,  183,  170,  184,  173,  183,  170,  179,
      171,  163,  169,  161,  156,    0,  164,    0,  157,  155,
      159,  156,    0,  149,    0,  167,  166,  165,    0,  158,
      157,  157,  163,  146,  145,    0,    0,    0,    0,  143,

      157,  142,  143,    0,    0,  150,  138,  152,    0,  142,
      143,  139,  141,    0,  147,    0,  133,    0,    0,    0,
      145,    0,  144,  139,  135,  142,    0,    0,  130,  126,
        0,  138,  137,  124,  135,  121,    0,  135,  119,  122,
      116,    0,  106,    0,  107,    0,  107,    0,    0,   98,
       96,   94,   79,   67,    0,    0,    0,    0,    0,    0,
        0,  388,  157,  160,  163,   79
    } ;

static yyconst short int yy_def[367] =
    {   0,
      362,    1,  363,  363,  362,  362,  362,  362,  362,  364,
      362,  362,  362,  365,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  366,
      362,  362,  362,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      362,  362,  362,  362,  362,  362,  362,  362,  364,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,

      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  362,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  362,  362,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,

      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  362,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,

      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,  366,  366,  366,  366,  366,  366,  366,  366,  366,
      366,    0,  362,  362,  362,  362
    } ;

static yyconst short int yy_nxt[446] =
    {   0,
        6,    7,    8,    9,   10,   11,   12,   13,   14,   15,
       16,   17,   18,   19,   20,   21,   22,   23,   24,   25,
       26,   27,   28,   29,   30,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   40,   30,   41,   30,   30,
       42,   43,   44,   45,   46,   47,   48,   49,   50,   30,
       30,   30,   30,   51,   52,   53,   54,   56,   56,   65,
       68,   66,   69,   75,   76,   71,  130,   78,   99,   81,
       70,   72,   73,   82,  100,   92,   83,   84,   70,   79,
       85,   77,   89,   93,   86,   90,  131,  104,   87,   94,
       91,   96,  101,  109,   88,  107,  102,  105,   97,   98,

       66,  108,  106,  112,  113,  116,  103,  117,  125,  110,
       57,   57,  141,  361,  114,  115,  125,   68,  126,   69,
      126,  161,  169,  127,  150,  360,  184,   70,  142,  175,
      185,  175,  162,  170,  176,   70,  181,  151,  152,  182,
      359,  191,  358,  221,  192,  357,  356,  355,  354,  353,
      153,  193,  194,  154,  222,  352,  195,   55,   55,   55,
       59,   59,   59,   63,  351,   63,  350,  349,  348,  347,
      346,  345,  344,  343,  342,  341,  340,  339,  338,  337,
      336,  335,  334,  333,  332,  331,  330,  329,  328,  327,
      326,  325,  324,  323,  322,  321,  320,  319,  318,  317,

      316,  315,  314,  313,  312,  311,  310,  309,  308,  307,
      306,  305,  304,  303,  302,  301,  300,  299,  298,  297,
      296,  295,  294,  293,  292,  291,  290,  289,  288,  287,
      286,  285,  284,  283,  282,  281,  280,  279,  278,  277,
      276,  275,  274,  273,  272,  271,  270,  269,  268,  267,
      266,  265,  264,  263,  262,  261,  260,  259,  258,  257,
      256,  255,  254,  253,  252,  251,  250,  249,  248,  247,
      246,  245,  244,  243,  242,  241,  240,  239,  238,  237,
      236,  235,  234,  233,  232,  231,  230,  229,  228,  227,
      226,  176,  176,  225,  224,  223,  220,  219,  218,  217,

      216,  215,  214,  213,  212,  211,  210,  209,  208,  207,
      206,  205,  204,  203,  202,  201,  200,  199,  198,  197,
      196,  190,  189,  188,  187,  186,  183,  180,  179,  178,
      177,  127,  127,  174,  173,  172,  171,  168,  167,  166,
      165,  164,  163,  160,  159,  158,  157,  156,  155,  149,
      148,  147,  146,  145,  144,  143,  140,  139,  138,  137,
      136,  135,  134,  133,  132,  129,  128,   66,  124,  123,
      122,   60,  121,  120,  119,  118,  111,   95,   80,   74,
       67,   64,   62,   61,   60,   58,  362,    5,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362
    } ;

static yyconst short int yy_chk[446] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    3,    4,   21,
       23,   21,   23,   28,   28,   26,   79,   34,   42,   36,
       23,   26,   26,   36,   42,   39,   36,   36,   23,   34,
       37,  366,   38,   39,   37,   38,   79,   44,   37,   39,
       38,   41,   43,   46,   37,   45,   43,   44,   41,   41,

       66,   45,   44,   48,   48,   49,   43,   49,   66,   46,
        3,    4,   89,  354,   48,   48,   66,   69,   70,   69,
       70,  105,  113,   70,   98,  353,  135,   69,   89,  125,
      135,  125,  105,  113,  125,   69,  133,   98,   98,  133,
      352,  141,  351,  171,  141,  350,  347,  345,  343,  341,
       98,  141,  141,   98,  171,  340,  141,  363,  363,  363,
      364,  364,  364,  365,  339,  365,  338,  336,  335,  334,
      333,  332,  330,  329,  326,  325,  324,  323,  321,  317,
      315,  313,  312,  311,  310,  308,  307,  306,  303,  302,
      301,  300,  295,  294,  293,  292,  291,  290,  288,  287,

      286,  284,  282,  281,  280,  279,  277,  275,  274,  273,
      272,  271,  270,  269,  268,  267,  266,  265,  264,  263,
      262,  260,  259,  258,  257,  256,  255,  254,  253,  252,
      249,  248,  247,  246,  244,  242,  241,  240,  239,  238,
      237,  236,  234,  233,  231,  229,  228,  227,  226,  225,
      223,  222,  221,  220,  219,  218,  217,  216,  214,  213,
      212,  211,  210,  209,  208,  205,  204,  203,  202,  201,
      200,  199,  198,  197,  195,  194,  193,  192,  191,  190,
      189,  188,  187,  186,  185,  184,  183,  181,  179,  178,
      177,  176,  175,  174,  173,  172,  170,  169,  168,  166,

      165,  164,  163,  162,  161,  160,  159,  158,  157,  156,
      155,  153,  152,  151,  149,  148,  146,  145,  144,  143,
      142,  140,  139,  138,  137,  136,  134,  132,  131,  130,
      129,  127,  126,  118,  117,  115,  114,  112,  111,  110,
      109,  108,  106,  104,  103,  102,  101,  100,   99,   97,
       95,   94,   93,   92,   91,   90,   88,   87,   86,   85,
       84,   83,   82,   81,   80,   78,   71,   68,   65,   64,
       63,   59,   57,   52,   51,   50,   47,   40,   35,   27,
       22,   20,   13,   11,   10,    9,    5,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,

      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362,  362,  362,  362,  362,  362,
      362,  362,  362,  362,  362
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ned.lex"
#define INITIAL 0
#define cplusplusbody 1

#line 9 "ned.lex"
/*==================================================
 * File: ned.lex
 *
 *  Lexical analyser for OMNeT++ NED.
 *
 *  Author: Andras Varga
 *
 *  Based on code from nedc.
 *
 ==================================================*/

/*--------------------------------------------------------------*
  Copyright (C) 1992,2002 Andras Varga

  This file is distributed WITHOUT ANY WARRANTY. See the file
  `license' for details on this and other legal matters.
*--------------------------------------------------------------*/


#include <string.h>

#if defined(__BORLANDC__)
# include <io.h>
# pragma warn -rch  /*turn off tons of 'Unreachable code' warnings --VA */
#elseif defined(_MSC_VER)
# include <io.h>
# define isatty _isatty
#else
extern "C" { int isatty(int); }
#endif

#include "nedgrammar.h"
#include "ned.tab.h"

extern YYSTYPE yylval;
extern YYLTYPE yylloc;

void comment (void);
void count (void);

#define WARN(m) \
        sprintf (yyfailure, "! %s", m); \
        yyerror (""); \
        yyfailure [0] = 0;

/* Vars updated by count(): */
LineColumn pos,prevpos;

#define TEXTBUF_LEN 1024
char textbuf[TEXTBUF_LEN];

#line 635 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 62 "ned.lex"

#line 788 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 363 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 388 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 63 "ned.lex"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "ned.lex"
{ comment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 66 "ned.lex"
{ count(); use_chanattrname_token = 0; return INCLUDE; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 67 "ned.lex"
{ count(); use_chanattrname_token = 0; return INCLUDE; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 68 "ned.lex"
{ count(); use_chanattrname_token = 0; return NETWORK; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 69 "ned.lex"
{ count(); use_chanattrname_token = 0; return MODULE; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 70 "ned.lex"
{ count(); use_chanattrname_token = 0; return SIMPLE; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 71 "ned.lex"
{ count(); use_chanattrname_token = 1; return CHANNEL; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 72 "ned.lex"
{ count(); return FOR; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 73 "ned.lex"
{ count(); return DO; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 74 "ned.lex"
{ count(); return TRUE_; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 75 "ned.lex"
{ count(); return FALSE_; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 76 "ned.lex"
{ count(); return REF; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 77 "ned.lex"
{ count(); return ANCESTOR; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 78 "ned.lex"
{ count(); return INPUT_; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 79 "ned.lex"
{ count(); return CONSTDECL; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 80 "ned.lex"
{ count(); return SIZEOF; }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 81 "ned.lex"
{ count(); return ENDSIMPLE; }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 82 "ned.lex"
{ count(); return ENDMODULE; }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 83 "ned.lex"
{ count(); return ENDCHANNEL; }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 84 "ned.lex"
{ count(); return ENDNETWORK; }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 85 "ned.lex"
{ count(); return ENDFOR; }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 86 "ned.lex"
{ count(); return PARAMETERS; }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 87 "ned.lex"
{ count(); return GATES; }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 88 "ned.lex"
{ count(); return GATESIZES; }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 89 "ned.lex"
{ count(); return IN; }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 90 "ned.lex"
{ count(); return OUT; }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 91 "ned.lex"
{ count(); return SUBMODULES; }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 92 "ned.lex"
{ count(); return CONNECTIONS; }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 93 "ned.lex"
{ count(); return DISPLAY; }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 94 "ned.lex"
{ count(); return ON; }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 95 "ned.lex"
{ count(); return LIKE; }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 96 "ned.lex"
{ count(); return MACHINES; }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 97 "ned.lex"
{ count(); return RIGHT_ARROW; }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 98 "ned.lex"
{ count(); return LEFT_ARROW; }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 99 "ned.lex"
{ count(); return TO; }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 100 "ned.lex"
{ count(); return TO; }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 101 "ned.lex"
{ count(); return TO; }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 102 "ned.lex"
{ count(); return IF; }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 103 "ned.lex"
{ count(); return SUBMODINDEX; }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 104 "ned.lex"
{ count(); return NOCHECK; }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 106 "ned.lex"
{ count(); return NUMERICTYPE; }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 107 "ned.lex"
{ count(); return STRINGTYPE; }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 108 "ned.lex"
{ count(); return BOOLTYPE; }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 109 "ned.lex"
{ count(); return ANYTYPE; }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 111 "ned.lex"
{ count(); use_chanattrname_token = 0; return CPLUSPLUS; }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 112 "ned.lex"
{ count(); use_chanattrname_token = 0; return STRUCT; }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 113 "ned.lex"
{ count(); use_chanattrname_token = 0; return MESSAGE; }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 114 "ned.lex"
{ count(); use_chanattrname_token = 0; return CLASS; }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 115 "ned.lex"
{ count(); use_chanattrname_token = 0; return NONCOBJECT; }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 116 "ned.lex"
{ count(); use_chanattrname_token = 0; return ENUM; }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 117 "ned.lex"
{ count(); return EXTENDS; }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 118 "ned.lex"
{ count(); return FIELDS; }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 119 "ned.lex"
{ count(); return PROPERTIES; }
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 120 "ned.lex"
{ count(); return ABSTRACT; }
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 122 "ned.lex"
{ count(); return CHARTYPE; }
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 123 "ned.lex"
{ count(); return SHORTTYPE; }
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 124 "ned.lex"
{ count(); return INTTYPE; }
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 125 "ned.lex"
{ count(); return LONGTYPE; }
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 126 "ned.lex"
{ count(); return DOUBLETYPE; }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 127 "ned.lex"
{ count(); return UNSIGNED_; }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 129 "ned.lex"
{ count(); return use_chanattrname_token ? CHANATTRNAME : NAME; }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 130 "ned.lex"
{ count(); return use_chanattrname_token ? CHANATTRNAME : NAME; }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 131 "ned.lex"
{ count(); return use_chanattrname_token ? CHANATTRNAME : NAME; }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 133 "ned.lex"
{ count(); return NAME; }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 134 "ned.lex"
{ count(); return INTCONSTANT; }
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 135 "ned.lex"
{ count(); return REALCONSTANT; }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 136 "ned.lex"
{ count(); return REALCONSTANT; }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 138 "ned.lex"
{ count(); return STRINGCONSTANT; }
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 139 "ned.lex"
{ count(); return CHARCONSTANT; }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 141 "ned.lex"
{ count(); BEGIN(cplusplusbody); }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 142 "ned.lex"
{ count(); BEGIN(INITIAL); return CPLUSPLUSBODY; }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 143 "ned.lex"
{ count(); /*FIXME*/ }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 145 "ned.lex"
{ count(); return (';'); }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 146 "ned.lex"
{ count(); return (','); }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 147 "ned.lex"
{ count(); return (':'); }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 148 "ned.lex"
{ count(); return ('='); }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 149 "ned.lex"
{ count(); return ('('); }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 150 "ned.lex"
{ count(); return (')'); }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 151 "ned.lex"
{ count(); return ('['); }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 152 "ned.lex"
{ count(); return (']'); }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 153 "ned.lex"
{ count(); return ('{'); }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 154 "ned.lex"
{ count(); return ('}'); }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 155 "ned.lex"
{ count(); return ('.'); }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 156 "ned.lex"
{ count(); return ('?'); }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 158 "ned.lex"
{ count(); return OR; }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 159 "ned.lex"
{ count(); return AND; }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 160 "ned.lex"
{ count(); return XOR; }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 161 "ned.lex"
{ count(); return NOT; }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 163 "ned.lex"
{ count(); return BIN_OR; }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 164 "ned.lex"
{ count(); return BIN_AND; }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 165 "ned.lex"
{ count(); return BIN_XOR; }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 166 "ned.lex"
{ count(); return BIN_COMPL; }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 167 "ned.lex"
{ count(); return SHIFT_LEFT; }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 168 "ned.lex"
{ count(); return SHIFT_RIGHT; }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 170 "ned.lex"
{ count(); return '^'; }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 171 "ned.lex"
{ count(); return '+'; }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 172 "ned.lex"
{ count(); return '-'; }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 173 "ned.lex"
{ count(); return '*'; }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 174 "ned.lex"
{ count(); return '/'; }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 175 "ned.lex"
{ count(); return '%'; }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 177 "ned.lex"
{ count(); return EQ; }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 178 "ned.lex"
{ count(); return NE; }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 179 "ned.lex"
{ count(); return LS; }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 180 "ned.lex"
{ count(); return LE; }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 181 "ned.lex"
{ count(); return GT; }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 182 "ned.lex"
{ count(); return GE; }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 184 "ned.lex"
{ count(); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 185 "ned.lex"
{ count(); return INVALID_CHAR; }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 187 "ned.lex"
ECHO;
	YY_BREAK
#line 1421 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(cplusplusbody):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 363 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 363 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 362);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 187 "ned.lex"


/***************************************************
* yywrap() -created 11 july 1995 alex paalvast
*    used to signal end of inputstream
*    not used with flex (only with lex) --VA
***************************************************/
#ifndef yywrap
int yywrap(void)
{
         return 1;
}
#endif

/***************************************************
* comment() -created 6 july 1995 alex paalvast
* - discards all remaining characters of a line of
*   text from the inputstream.
* - the characters are read with the input() and
*   unput() functions.
* - input() is sometimes called yyinput()...
***************************************************/
#ifdef __cplusplus
#define input  yyinput
#endif
void comment(void)
{
        int c;
        while ((c = input())!='\n' && c!=0 && c!=EOF);
        if (c=='\n') unput(c);
}

/***************************************************
* count() -created 6 july 1995 alex paalvast; edited by VA
* - counts the line and column number of the current token in `pos'
* - keeps a record of the complete current line in `textbuf[]'
* - yytext[] is the current token passed by (f)lex
***************************************************/

void count(void)
{
        static int textbuflen;
        int i;

        /* init textbuf */
        if (pos.li==1 && pos.co==0) {textbuf[0]='\0'; textbuflen=0;}

        prevpos = pos;
        for (i = 0; yytext[i] != '\0'; i++) {
                if (yytext[i] == '\n') {
                        pos.co = 0;
                        pos.li++;
                        textbuflen=0; textbuf[0]='\0';
                } else if (yytext[i] == '\t')
                        pos.co += 8 - (pos.co % 8);
                else
                        pos.co++;
                if (yytext[i] != '\n') {
                        if (textbuflen < TEXTBUF_LEN-5) {
                            textbuf[textbuflen++]=yytext[i]; textbuf[textbuflen]='\0';
                        }
                        else if (textbuflen == TEXTBUF_LEN-5) {
                            strcpy(textbuf+textbuflen, "...");
                            textbuflen++;
                        } else {
                            /* line too long -- ignore */
                        }
                }
        }
        /* printf("li=%d co=%d\n", pos.li, pos.co); good for debugging... */
        yylloc.first_line   = prevpos.li;
        yylloc.first_column = prevpos.co;
        yylloc.last_line    = pos.li;
        yylloc.last_column  = pos.co;

}

/***************************************************
* jar_yyrestart() -created by VA
***************************************************/
void jar_yyrestart(FILE *_yyin)
{
#ifdef FLEX_SCANNER
        if (yy_current_buffer)
              yyrestart( _yyin );
#endif
}

