module Colors
{
    submodules:
        hue0: Dummy {
            parameters:
                @display("p=100,100;b=40,40,,@00ffff");
        };
        hue1: Dummy {
            parameters:
                @display("p=140,100;b=40,40,,@20ffff");
        };
        hue2: Dummy {
            parameters:
                @display("p=180,100;b=40,40,,@40ffff");
        };
        hue3: Dummy {
            parameters:
                @display("p=220,100;b=40,40,,@80ffff");
        };
        hue4: Dummy {
            parameters:
                @display("p=260,100;b=40,40,,@a0ffff");
        };
        hue5: Dummy {
            parameters:
                @display("p=300,100;b=40,40,,@c0ffff");
        };
        hue6: Dummy {
            parameters:
                @display("p=340,100;b=40,40,,@e0ffff");
        };
        hue7: Dummy {
            parameters:
                @display("p=380,100;b=40,40,,@ffffff");

        };
        sat0: Dummy {
            parameters:
                @display("p=100,180;b=40,40,,@ff00ff");
        };
        sat1: Dummy {
            parameters:
                @display("p=140,180;b=40,40,,@ff20ff");
        };
        sat2: Dummy {
            parameters:
                @display("p=180,180;b=40,40,,@ff40ff");
        };
        sat3: Dummy {
            parameters:
                @display("p=220,180;b=40,40,,@ff80ff");
        };
        sat4: Dummy {
            parameters:
                @display("p=260,180;b=40,40,,@ffa0ff");
        };
        sat5: Dummy {
            parameters:
                @display("p=300,180;b=40,40,,@ffc0ff");
        };
        sat6: Dummy {
            parameters:
                @display("p=340,180;b=40,40,,@ffe0ff");
        };
        sat7: Dummy {
            parameters:
                @display("p=380,180;b=40,40,,@ffffff");

        };
        bri0: Dummy {
            parameters:
                @display("p=100,260;b=40,40,,@ffff00");
        };
        bri1: Dummy {
            parameters:
                @display("p=140,260;b=40,40,,@ffff20");
        };
        bri2: Dummy {
            parameters:
                @display("p=180,260;b=40,40,,@ffff40");
        };
        bri3: Dummy {
            parameters:
                @display("p=220,260;b=40,40,,@ffff80");
        };
        bri4: Dummy {
            parameters:
                @display("p=260,260;b=40,40,,@ffffa0");
        };
        bri5: Dummy {
            parameters:
                @display("p=300,260;b=40,40,,@ffffc0");
        };
        bri6: Dummy {
            parameters:
                @display("p=340,260;b=40,40,,@ffffe0");
        };
        bri7: Dummy {
            parameters:
                @display("p=380,260;b=40,40,,@ffffff");

        };
        rgb1: Dummy {
            parameters:
                @display("p=100,340;b=40,40,,#ff0000;t=red");
        };
        rgb2: Dummy {
            parameters:
                @display("p=140,340;b=40,40,,#00ff00;t=green");
        };
        rgb3: Dummy {
            parameters:
                @display("p=180,340;b=40,40,,#0000ff;t=blue");
        };
        rgb4: Dummy {
            parameters:
                @display("p=220,340;b=40,40,,#ffffff;t=white");
        };
        rgb5: Dummy {
            parameters:
                @display("p=260,340;b=40,40,,#f0f0f0;t=lightgray");

        };
        named1: Dummy {
            parameters:
                @display("p=100,420;b=40,40,,red;t=red");
        };
        named2: Dummy {
            parameters:
                @display("p=140,420;b=40,40,,green;t=green");
        };
        named3: Dummy {
            parameters:
                @display("p=180,420;b=40,40,,blue;t=blue");
        };
        named4: Dummy {
            parameters:
                @display("p=220,420;b=40,40,,green1;t=green1");
        };
        named5: Dummy {
            parameters:
                @display("p=260,420;b=40,40,,green2;t=green2");
        };
        named6: Dummy {
            parameters:
                @display("p=300,420;b=40,40,,green3;t=green3");
        };
        named7: Dummy {
            parameters:
                @display("p=340,420;b=40,40,,wheat;t=wheat");

        };
}

