network DisplayStringTest
{
    submodules:
        rangeindicator: rangeindicator;
        colors: Colors;
        icons: Icons;
        textAndTooltip: TextAndTooltip;
        connTextAndTooltip: ConnTextAndTooltip;
        connColors: ConnColors;
        connLabelPlacement : ConnLabelPlacement;
        background: Background;
        nedParams: NedParams;
        emptyStringParams : EmptyStringParams;
        nonemptyStringParams : NonemptyStringParams;
        numericParams : NumericParams;
        paramsWithBraces : ParamsWithBraces;
        scaling: scaling;
        scaling2: scaling2;
        active: Active;
        displayName : DisplayName;
        displayStringOption : DisplayStringOption;
        arrangements: Arrangements;
        layoutGroup: LayoutGroup;
}


