#! /bin/sh
opp_run -s -h latexconfig > config-in.txt
perl stripgrammar.pl ../../../../src/nedxml/ned2.y >ned.txt
perl stripgrammar.pl ../../../../src/nedxml/msg2.y >msg.txt
perl stripeventlog.pl ../../../../src/eventlog/eventlogentries.txt >eventlog.txt
opp_run -s -h nedfunctions >tmp.txt
perl processnedfuncs.pl <tmp.txt >nedfuncs.tex
opp_run -s -h units >units.txt
rm tmp.txt
