import "dummy";

module Colors
    submodules:
        hue0: Dummy display: "p=100,100;b=40,40;o=@00ffff";
        hue1: Dummy display: "p=140,100;b=40,40;o=@20ffff";
        hue2: Dummy display: "p=180,100;b=40,40;o=@40ffff";
        hue3: Dummy display: "p=220,100;b=40,40;o=@80ffff";
        hue4: Dummy display: "p=260,100;b=40,40;o=@a0ffff";
        hue5: Dummy display: "p=300,100;b=40,40;o=@c0ffff";
        hue6: Dummy display: "p=340,100;b=40,40;o=@e0ffff";
        hue7: Dummy display: "p=380,100;b=40,40;o=@ffffff";

        sat0: Dummy display: "p=100,180;b=40,40;o=@ff00ff";
        sat1: Dummy display: "p=140,180;b=40,40;o=@ff20ff";
        sat2: Dummy display: "p=180,180;b=40,40;o=@ff40ff";
        sat3: Dummy display: "p=220,180;b=40,40;o=@ff80ff";
        sat4: Dummy display: "p=260,180;b=40,40;o=@ffa0ff";
        sat5: Dummy display: "p=300,180;b=40,40;o=@ffc0ff";
        sat6: Dummy display: "p=340,180;b=40,40;o=@ffe0ff";
        sat7: Dummy display: "p=380,180;b=40,40;o=@ffffff";

        bri0: Dummy display: "p=100,260;b=40,40;o=@ffff00";
        bri1: Dummy display: "p=140,260;b=40,40;o=@ffff20";
        bri2: Dummy display: "p=180,260;b=40,40;o=@ffff40";
        bri3: Dummy display: "p=220,260;b=40,40;o=@ffff80";
        bri4: Dummy display: "p=260,260;b=40,40;o=@ffffa0";
        bri5: Dummy display: "p=300,260;b=40,40;o=@ffffc0";
        bri6: Dummy display: "p=340,260;b=40,40;o=@ffffe0";
        bri7: Dummy display: "p=380,260;b=40,40;o=@ffffff";

        rgb1: Dummy display: "p=100,340;b=40,40;o=#ff0000;t=red";
        rgb2: Dummy display: "p=140,340;b=40,40;o=#00ff00;t=green";
        rgb3: Dummy display: "p=180,340;b=40,40;o=#0000ff;t=blue";
        rgb4: Dummy display: "p=220,340;b=40,40;o=#ffffff;t=white";
        rgb5: Dummy display: "p=260,340;b=40,40;o=#f0f0f0;t=lightgray";

        named1: Dummy display: "p=100,420;b=40,40;o=red;t=red";
        named2: Dummy display: "p=140,420;b=40,40;o=green;t=green";
        named3: Dummy display: "p=180,420;b=40,40;o=blue;t=blue";
        named4: Dummy display: "p=220,420;b=40,40;o=green1;t=green1";
        named5: Dummy display: "p=260,420;b=40,40;o=green2;t=green2";
        named6: Dummy display: "p=300,420;b=40,40;o=green3;t=green3";
        named7: Dummy display: "p=340,420;b=40,40;o=wheat;t=wheat";

endmodule

