import "dummy";

module Icons
    submodules:
        icon_large_1: Dummy;
            display: "p=351,75;i=block/sink;is=l;t=note: centers should be aligned\, not tops or bottoms";
        icon_normal_1: Dummy;
            display: "p=435,75;i=block/sink;is=n";
        icon_small_1: Dummy;
            display: "p=512,75;i=block/sink;is=s";
        icon_verysmall_1: Dummy;
            display: "p=584,75;i=block/sink;is=vs";
        icon_large_2: Dummy;
            display: "p=354,170;i=block/sink_l";
        icon_normal_2: Dummy;
            display: "p=438,170;i=block/sink";
        icon_small_2: Dummy;
            display: "p=515,170;i=block/sink_s";
        icon_verysmall_2: Dummy;
            display: "p=587,170;i=block/sink_vs";
        icon_plus_box: Dummy;
            display: "p=345,252;i=block/sink;is=s";
        icon_plus_icon2: Dummy;
            display: "p=451,251;i=block/sink;is=s;i2=status/asleep";
        box_plus_icon2: Dummy;
            display: "p=553,245;b=30,24;o=wheat;i2=status/asleep";
endmodule

