//
// This file is part of an OMNeT++/OMNEST simulation example.
//
// Copyright (C) 2006-2015 OpenSim Ltd.
//
// This file is distributed WITHOUT ANY WARRANTY. See the file
// `license' for details on this and other legal matters.
//

#ifndef __QUEUEING_JOIN_H
#define __QUEUEING_JOIN_H

#include <list>
#include "QueueingDefs.h"
#include "Job.h"

namespace queueing {

/**
 * Merges sub-jobs generated by Fork.
 */
class QUEUEING_API Join : public cSimpleModule
{
    protected:
        std::list<Job*> jobsHeld;
    public:
        ~Join();
    protected:
        virtual void initialize() override;
        virtual void handleMessage(cMessage *msg) override;
        virtual void refreshDisplay() const override;
};

}; // namespace

#endif
