//
// This file is part of an OMNeT++/OMNEST simulation example.
//
// Copyright (C) 2006-2008 OpenSim Ltd.
//
// This file is distributed WITHOUT ANY WARRANTY. See the file
// `license' for details on this and other legal matters.
//

//
// @titlepage
//
// <center><h1>Queueing library</h1></center>
// <a href="../../README.txt">See readme.txt</a>
//

package omnetpp.queueing;

// C++ classes of simple modules are in the 'queueing' namespace
@namespace(queueing);
