#=================================================================
#  ICONS.TCL - part of
#
#                     OMNeT++/OMNEST
#            Discrete System Simulation in C++
#
#=================================================================

#----------------------------------------------------------------#
#  Copyright (C) 1992-2008 Andras Varga
#
#  This file is distributed WITHOUT ANY WARRANTY. See the file
#  `license' for details on this and other legal matters.
#----------------------------------------------------------------#

set icons(defaulticon) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABGdBTUEAALGPC/xhBQAAAAFzUkdC
    AK7OHOkAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAAAZiS0dE
    AAAAAAAA+UO7fwAAAAlwSFlzAAAOxAAADsQBlSsOGwAAAmpJREFUWMPNmbGr2kAcxz85fbq8QR4Z
    HB0K9h9wESl0cRaHrh1c80+UDh10Ezo6K+4uHTKXLoKz8BAXzYNQRAgYcl08G436YryoAbnjLp4f
    vr/f93fHCf+fZ+A74ADyTh8HaAMFBWVs2xLwC/hgmqbfarVEuVwWUkoApJSofhAEu7HwXPidOHPh
    daSUzOdzBoPBZrFYPAGvwGfg1dgq9wf4aFkW7XabXC4XWTwIgsjYubm476t+EAT4vk+n06HX67GF
    rGSAb0DDsiy63S5CiLvAKWWr1Srr9ZrxeFwAhAE4pmkWZrNZNp/Px/6xa8cP4Q6VrNfrm+Vy+VcA
    ZqvVEo8CJ6XEMAyazeYTYAoAZYhHgFNtsVgEQBxz273hlMMBsqpzCzNcAqlMIx4RLuzq7LEQ6w5p
    Erh3AdPKt6sV1BHquHDnoPcAdebhe3CXKLqnoI7SkiTPEudg2nBxYE8W6keAO5qDSeqeLrhjsLFd
    nBbcOSW1mUQ3XFi9q02SVqv6J3MwrhnShjup4L3gDneZCGDckJ5znq42ch5Mmm9phXnPxdfCpQUd
    yyQ699fER/5TBtG5K2hRUKcK2hVMA+7aaJwNcRr7a5JSI47VwUeAiyh4q/31UgVTyUEdcHuA0+k0
    kFKKNOEuhXUcZ5eDb8PhMPA8b7eQ7k3/Ujjf97FtewO8ZYAXz/M+rVYrarVa6mGOE/5+v89kMskA
    PzPAb+DLZDJ5cV2XSqWCEOJmh4JD5fr9PqPRSF0Bf41cohcKBb/RaIhSqRS5Mwwnr6r2qj317qnv
    H445joNt2xvXdfcu0Qk9z8APHuNvCFNB/QNdZWqtV/QFlwAAAABJRU5ErkJggg==
}]

set icons(imagetoobig) [image create photo -data {
    R0lGODlhmQF6ALMAAO/v7/f39///////////////////////////////////////////////////
    /////yH5BAEAAAIALAAAAACZAXoAAAT+UMhJq7046827/2AojmRpnmiqrmzrvnAsz3Rt33iu73zv
    /8CgcEgsGo/IpHLJbDqf0Kh0Sq1ar9isdsvter/gsHhMLpvP6LR6zW673/C4fE6v2+/4vH7P7/v/
    gIGCg4SFhoeIiYqLjI2Oj5CRkpOUlZaXmJmam5ydnp+goaKjpKWmp6ipqqusra6vsLGys7S1tre4
    ubq7vL2+v8DBwmkAxcUUxsYBFQHJxxfNycsbAdHK0xXO2sYa297Q1gDVHNXS2B3OH+HiGN7mGeXv
    Fu7pr/US29na7fvw9OzI/j3jJxAAM3rnKKxzljDDPQ75LhQEqPBfwomwHkacsLGitob+EhZuO4fR
    YcmQAhuKZIgumQeRICdSFLCSJceCGV3etEmz4wSY0GRiOynxZE2ePQuC1MetA9B5Mn8K3fkvZ1N8
    yophixauqFadTLVu5fmQRFmqM9cFVObxqkm33bLCxQpXLV2xUqWhzaVRrkG6XQ9y09t2JsdqJMGW
    OJtUq4Vw0yA/Jvx2oIaulPcW/it5HuK1lmv1PXZ18Fy9gfM69oDzA+POYSNnprpU8wbUiu9aRMmW
    tcBYow2ytSYgt2TYxXPf/u1aefK5uqN7DQ0VumDHyJ/vlu67qlXLLrkmXWYcbObg91p3p679b/Vn
    jNsvt16Ydlh3id26Q/vtu3vtjT3+Rx5clKUmH3+lMbfef7bdx52DcdFnH2+hKdjgfrr1Z49iOvl1
    12bejNVbe+Y5F8Jrs90l24ig1fZgUCmBxllZsGF44C3BUdgUh0ZRZmN8IKDIoo4rrlaYizcSZOE9
    yNWoIZD+gaYjQDyq1944qg0E5YJKpoXeOXZFyJ6M9MhopoxYTtmgaFW6ZxNYR/EUZ3pWzjfmnEY2
    tp2YGOJp5ENh6qkgUazkyF2J0AE60VB18unPnlmG2JJ3jNFJYGZ+MmphoW2qpumMQxIJIlIkagiR
    iVOSGqmqXX6TnahJvhjnRY2qYmhjn8J6nWE0rZMmmabaySA48lwGGZL3uZqintP+nPVqPNdMV+Yw
    1FZr7bXYZqvtttx26+234IYr7rjklmvuueimq+667Lbr7rvwxivvvPSOgFBMtUIrDr73JhvslC7q
    +yuCPr03LTPHkpOwtIYtdKqEpebzKrMZPomqGUr569NRtMZIcD/+YsCxxiC3GuzIMEoaMrAPj/lx
    OhN3dtKWZBBK1Jz5eRxxyanyOifJW96s86ofrYxgy8MC3aFzlnoXqxpRvQwnUTK52ehToyJFqME2
    Zpp10QiKSHPQrWXn5KAXl6Goj2lfGemnDIZJM23K2RTo3Oq06aXeYAYnHm8Gdiks0hC+KO0bNLIN
    8av75hx300mnLNyQc+M9qWX+zxKW+YjSJChO22RDHCt6hLtxFuQaBs4nQlJTh1tdHw3ceuSOHjld
    kbxql6vnAA6+ekewIWel5WCcjujBli8KLM/HzVZTQ7XWfqbBhh9qGjvEgZ52nZArDV7bYxjvOfLg
    Vwz27LtO+PVM0QtO/eFPW3+MeOJpD3Gdqc02fPlhiK8l2qJrHcN8UiATIWYk6FvPUuJTDwYeL0Bs
    sZ/LzJe44ehvSfwrXt2ORzsdSWRg9QhU9XaFH2rILYPvqc3ENLcsxf3FQ72TnvsI578OjvAMFfxT
    2szmQvdkZ2wlgdb74ueUZWVJJSwM1dlAtbQJ3vCJR0oREAMohrVxToIU8dX+hXIzReZoUU1QFJkR
    0bQZMkZKSoJqluhC58TlJa2LNqwZ1dTjp+kJyo0hnIrXKAilqAmqhERDIFXQosY2qmdrWMMjB//V
    P+5ZCWd2dBsfm8iePGJwU95zCyRJKMhByi+Oh7xaJxU5PhvJEVI7y+Eon4Y6ZYWKYn+8ICZJCTtA
    TsaWnsRVLivzo1oVbJKlZKQGQ8QvpylkYYU7IjDnt6zgCUx2W6Mle56psGKFxVO7NBnIovlFrlnM
    mPUKpzjHSc5ymvOc6EynOtfJzna6853wjKc850nPetrznvjMpz73yc9++vOfAA2oQAdK0IIa9KAI
    TahCF8rQhjr0oRCNqEQLJ0rRilr0omCIAAAAOw==
}]

set icons(arrowhead) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAAAARnQU1BAACx
    jwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAKlJREFUOE9j/P//PwNVAchAamK4YZS6Euao
    YWBgQOGx/yC8+8QdvLFHtJddUzb9B2HLqLVgjMtgog2EudCr5dp/EMZlMFYD/Rtv/gfhgMbb/4Na
    7qFgrx6ggUAcVA3BMINhqQOrgZpBPf9BWCu4779F1Gow9uy8DDaYLAOxpcXYngf/QRjmsiCgt0EY
    PSxJDkOqRQoslqmWbIjNkkR7edRAnCGAEYbUKmQBP7/KXHRAXrYAAAAASUVORK5CYII=
}]

set icons(apply) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAjAAAbgDsJRPvPy7qRjbc
    VknYZFjlWErnaVzteGrlhXnqpJnkw7vs1Mzp4tzx8OqVHN65AAAAEHRSTlP/////////////////
    //8A4CNdGQAAAENJREFUeJx1zsENACAIQ9E6AhO4/3Y4ASJgE2Lk9PJ7AcbDS8xLHaweiycWT0xG
    7FTk7gQyRsWlSe5BIZfwnTW/T3ZuZHqi/OzMrT4AAAAASUVORK5CYII=
}]

set icons(revert) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEWVIx3zGQbsJRPvPy7qRjbc
    VknYZFjlWErnaVzteGrlhXnqpJnkw7vs1Mzp4tzx8OrYRYc3AAAAEHRSTlP/////////////////
    //8A4CNdGQAAADtJREFUeJxj+A8HDDiZ/HDmBxD3A5TJ//8DP0QBUJgBpo2BgR/G/MDwH1MUSS3C
    hA9Qa2AyH/A5By8TAIMapzuvxOjHAAAAAElFTkSuQmCC
}]

set icons(loadned) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAPVJREFUOE9jYBg2wNzc/D8MU+wpkEHIhsD4
    6OIYFh3uNvuPjPG5hKBr1+ao/EcHIDFshhL0/uFWs/8/XswA4w83Jvx/caHj/4MDFf9vbCj4D5JD
    xwTDcE+r0f8fH05gxd8/HEERB6klbGA90MAXG4jC8+IVCBu4BWTggwUoeG2R/n9iMFbXri3S/v8D
    GHYwDDLoxwNgmOLBoHAGqcNq4FJgbP640QHGYMOgbBiNHKv42HDD58XL/v9xoQJi2IUGDGxrbfm/
    sfMiXoySyPuDJKGGVYANRscgxSQZCHLqvDT1/7gwWQYSymYku5DuBhIT0wRzEDkKAMKT9qk9WAOK
    AAAAAElFTkSuQmCC
}]

set icons(save) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABMAAAATCAYAAAByUDbMAAAAAXNSR0IArs4c6QAAAAZiS0dEAP8A
    /wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9gFFQo0GDhP8kgAAAHKSURBVDjL
    zZMxaBRBFIa/t7FUg5UIamNIIagIksLirNJbJ4q9raIQEMXCwvZAyCGIEgIiaG/KEJSIRRQskouQ
    IleJoMcFbndmfovdnb1lN9YZWHiz879/3nv/P3BUl5XB65VVfd/ejgd/hn+5ODPTSPjR7zN94mTc
    X5qd5c6tBauB7j16ouHoQMPRgbrLPQWfHvp1l3sRe//xU5Ucx8pAJHgvMNjbHzB2ql2miTb29gcR
    qwlYJAsBXFCeBYzSOlVOVnXjQg70vo2MhNQJK9hGaWgMV1T/MhdiXpNM4JwvCyN1WezNyNsxY+I8
    xLwGmfcwdtXNPzfe/NcGWSaE8KGNTAlpJkB05hdYW1s9lKgzv8jYecDwoaVNBUidBxnnTp9i8fZd
    EI3Bl8qmTkgBtVUmIM1CHPWXT+tsbu00qrp2+QJz128UVwjXNrPMQeZUKGZsbu3Qe/6AyjqO3/33
    LL3c5epch1KK1pnJVwqZ5cBXH3cr5PBr5TEfUOnYNp95pnBetRd7/uyZCEx/TU94LBfKDBxT7T7z
    of6Erti7GD/77Fm6eZwP1HGTAkSZur0VbXwboJC/OTMrwILECuMqqmWJ5XvB2xcPjSO9/gGxzhY7
    P6fbbAAAAABJRU5ErkJggg==
}]

set icons(undo) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAAAAAAITGxsYAAP//////
    //////////////////////////////////////////9MSdVzAAAAEHRSTlP//wD/////////////
    ////8qlaxQAAAC5JREFUeJxjUIIDBkqYgoIQppCSIIgAMQUVgUKKEKYQgimIxBSCqQUDIQrdAAYA
    5lYYQC6lU50AAAAASUVORK5CYII=
}]

set icons(redo) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAAAAAAITGxsYAAP//////
    //////////////////////////////////////////9MSdVzAAAAEHRSTlP//wD/////////////
    ////8qlaxQAAACxJREFUeJxjUIIDBvKZgoIwpiKQAyKATCGgiJAgnKmIYAoKwtQqIpiUugEKAPDv
    GF5qge68AAAAAElFTkSuQmCC
}]

set icons(step) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAB4AAAATCAYAAACHrr18AAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAPRJREFUSEvFlTEOgzAMRduLcJlIDEhcgBUk
    epUu7Q1g7NilB0A9Q4feJpUjuTIhTuxkCJKlAOY/fzvA2RhzqnIAuEYUQT/ramloDGSBAfbq+13c
    us5CvJfFSgpQg5/D4ACpSBWgAoPYdZqSUIl7Mfi7bfYxzzvopW0tBtcBru1iMMyUigPwPo7/eUI3
    QnDIQzhdi8G+KBWhrrg8uF4M5qBYANf2LLDkFYk5Zx03TWMxQEB77heWmrebMUBCjuh1Pyd2T9Vq
    6haL8MVjHaE7l75m/hrzDruacxJzrJ2/+yOG5il1nANkHZeIaZ4Vf0A0opLcauAfgkdfhZmm2ZoA
    AAAASUVORK5CYII=
}]

set icons(run) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAB4AAAATCAYAAACHrr18AAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAKFJREFUSEvF1GEKgCAMBeC6iMfxh9A9Ok2n
    6SReyJhgmChsbw8KBhnMb850zzlvvzwCI3EfR5FAcuti0URBr5RqIHNQYASnwVacCltwOqzF6fAZ
    o+pno8JalHacpL0W1AW3s4ugLxxCKC3ahDIe32ffrCttc9Y91iJ9cX0OfHNZVzx2xwVr2jrrDIJ+
    9ni1tyuM0mq0ak8efIF4UMo5Rgt4AE/n/qSTRl1eAAAAAElFTkSuQmCC
}]

set icons(express) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAB4AAAATCAYAAACHrr18AAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAMVJREFUSEvlldENgzAMRMsiGYcPJPboNEzD
    JFmIypGMLHMOvgLqR5EsQk7csx0Lhlrr6yeXgFGs87xJPKVDqMAEukxTiyixK3oKjOA2sW/0NNib
    ezCrU2BrjsCMToPVPAJndRr8Hsc2bBE4q1NgNY3AjJ4GW1MEZvUQHH047tpv4FLKJqFrf/c6etaE
    rOa9bdI72L4YJdDbt5r3Ql06VOwNzipAugVpJz08XfFZR3owBE+dMTK1M4HWvfNtv+K7ppT1+T/w
    B2p3yKTh4IZyAAAAAElFTkSuQmCC
}]

set icons(fast) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAB4AAAATCAYAAACHrr18AAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAMpJREFUSEvF1P0JgzAUBPB2kYzjH4J7dJpO
    00mykOUFItfrvabqgULA5uP9ckZ7r7XeLrkC3ttey7JGy9aNxlvYvWjMj8LPeW5NrR+NW2CFI5xt
    7nRilZxhhdtgLK5gxq1wL57BiFvhxzS1ly2D+7jt5YokWFTBOG6DuSjDPH4YHn37CCt0g0spa2+9
    KP+Ofp6n1uEZZ+gHzCnURlTSmMf9Af5CvxJj2uyeIQWPjiJNjI9QFcY+O8yJs/M8Bf/zaNxzDv1z
    OTZxGfwGFiLriBzs6Q0AAAAASUVORK5CYII=
}]

set icons(until) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAB4AAAATCAYAAACHrr18AAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAALNJREFUSEvllNEJgDAMRHWRLlPoR8E9nMYZ
    OoSTdKHKFSJFNE1KxA+FQGiPvCY5nHPO0ycfwL3Yl6UgejrNfReKYoBuMdbQFOe0arAVfAg8Avfe
    F4rqK8no2lHTyLVwU3AL7+Wm4DWEklKqATCXm4EBlayJNCZgLRTwIbCmM6m2uto5d46N8qcznF81
    rdYEzD2ifbA5mIrfdf86+GkVJmBpZ5wfuN3D0dfdi36ZUsNodP8DH2Ua6fH4zikVAAAAAElFTkSu
    QmCC
}]

set icons(mrun) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABgAAAATCAYAAACKsM07AAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAJNJREFUSEtjvHTpEgNNAcgCWmKaGg4OHVq6
    niQL+ry8/sMwKY7C6QN0Awnx0S3NcHP7j9cHhAzE5yOgXCJWC5CDgFCQYFML8wVIDq8FIAXEhjMW
    n66itQXgxEAwDoj1AbI6ZN+gWIAsQU5SBOoBBwvVLQClFmyOwwgicnwACgJCmKScTE6cjFpAVElM
    lCJywx+kDwDiQgVV/+qK2gAAAABJRU5ErkJggg==
}]

set icons(mfast) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABgAAAATCAYAAACKsM07AAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAKNJREFUSEvtksEJwCAMRdvlPDhJp+nVXRzD
    hWwjBmJQEy25tRCoGPL+//FMKR2mHwAsy3R4ScdS/RLg9j5jjURdzmV+N3TAB0rnd7i3BkQKwP/G
    AY1AioTeg3o441DqpguAZu3ycTgDhKkDDaCqjMxJEUZhW88U1E2qiasAqArpKc6i68X1GVCjClxk
    s4NdB0JUZR9bO9C+sB+gilfVtJI5730Adz35C5MGT3QAAAAASUVORK5CYII=
}]

set icons(stop) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAeRJREFUOE+tlOlOwlAQhfEPD+BzCeKCCKi4
    C0YNhofihzEaH0qhpRsoJqCM54y9FUoLmjjJzd2/nlluVzIJ5pbLkslmM5nRKGlb11bb7ZXUzekN
    wn7blgIXgbxSSbzt7bmPpUJTYbWaOPv74lYq4gKadG4OmggDyEWz63XpnZ+Lc3oq7vGxrmmLhSaC
    psEsAnCRfbzZWOsB7hweintwEMEVOgc0CtB3mk3pXF9L9/JSLCi1oDSC8RxC4VWryUCBfQyH7OTl
    9lZ7Y4QNnp50+vr4KA5gxob391FsVWGPriEen+OxPLdaCuvc3Ej36krvGGUc946OdI3KaB7uaR9m
    X4E23CBw2gijmwoM3ZxMJpEyumns/e5O/I0NZXwD4Q4nRhkPmphxbCP4c8p2d5UXbG1JHzB/ff0H
    aEFJXKF1caGZVTeRSQeZfHt40Dlj5u/s6JiwQT4vwdraD5AwK0y/1WgIYfbZmZaFgbl7exovvha/
    WIyUETbI5SQI20wtOoAxQVoWJydaY1SWCCsUVBlh/TjMUKnURjIYsxkYnlykbHNT+iHsFW4GdBfA
    he+5S3VQxkx6ISxAWQR/hU0rtVBv+oLCP4wPmA9lVNSnMmR1obK4ZHUf2WeNMq7Ruw2fJYFL/4X/
    deALuBEIlHqhVdQAAAAASUVORK5CYII=
}]

set icons(as) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAAAARnQU1BAACx
    jwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAHRJREFUOE9jvHDhAgNVAchAamKqGgb2LTVd
    Rx8DO+3t/1PiagwvgwykxFAGmAHYaHJcitfARBsbkr3PANKEjGEuRTZs9uzZ/y0tLf+DaJCr8fGx
    hiG6y0CGwTDIQHx8DAOxeZMiF5ITEch6hmBOGfUyyZEGAMZ+W/3+qmhjAAAAAElFTkSuQmCC
}]

set icons(asgraphics) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAAAARnQU1BAACx
    jwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAI9JREFUOE9j/P//P8MooH4IPLze959YTNB2
    Yg1CVofXUJoaCExQoESF4X10caJcCDKLagaCDIN5HZkNEsMmRyBiEIahG4puOMwCoryMHjnI3n9w
    pR/ugxtnu/DnXVyxDDMQZBgIgwyCYbJcCLIIm2HnDreQ7kJk1yCzQYYRNBDkfJBr0A2BaUanCWa9
    4a8AAAl81eQA/IZhAAAAAElFTkSuQmCC
}]

set icons(asobject) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAARZJREFUOE/llNsNgkAURLEmGqAI6qAGi7A8
    H/hEUFQE5Z3rDGEN0aBr4oeJJPN7mDO7YBj//TiOM0TkgwxfLkZQXtaSFbVc81qSrJI4rSS6VnJK
    SjnEpYTnQnZRIcGpaF78FpgCZtt2kxig6FLeYfsW5gO2PeZ6wAtamabZhDA0eIplWbI59AAxwkDV
    pkICxTMVATtCM4QmmwXQ9NHKA2gd5rLaZ3oNCVPK3b2o2IUtdj1A66Ehx1fKHL9P2Q00G/IkH8fn
    XitoLqE5B8j1U5luUz1lwpSyB81Nu9cSioTNWtjY0wTyfilljt+nrA3k+FQkjIocn3ux2QSaBKlo
    XewubN7CuNekA/oE+N1v+Td/je5oZHwzN2iJGWWVSzETAAAAAElFTkSuQmCC
}]

set icons(asoutput) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAAAARnQU1BAACx
    jwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAXZJREFUOE+9lF9LAlEQxes77v0APUUEQQTh
    pqIlW5mSKQUZklYUGYl/6MEgqaAHIYhe+wJFgZGB5OrKaea6KyF5dwNp4TBzh8Nvz16WmZwY0wNg
    TCQbw8CxQkcC/elraPFHz2I/hxwJ1GIPWIxkPIv9amD0Hrqxj6em5Sr2aeR3Adbhj+YkrN0hmRZM
    Etd2p0eVxeceAtEDiPW6GihW7xCKH0mgQfcTTFaxYBQwox9ian4PrXaXZKH1ZUmfRn51QuMGka0T
    CWy2ukqxTxi3LglXaljbORsk5JTh1CV8G2XMhU8x7cvJpI3PDta28xCRKxfgchWxdEEC3z5MvNri
    3jnLvmkitluAIL/yk0XoApuZogQ+v5t4aZC4Oj2f7VkiUwL71cBgEclsRSqVLduV+lx/luTZoK9A
    BEtq4GyiBhE4/11+e+5U8rFfmXB4ZcgX6HT5rKX8ADDsUy6HPoR+Cf34R3V6nvflpPtTQq9L7v/W
    l9dEo+7wGyUgTwV4niOTAAAAAElFTkSuQmCC
}]

set icons(parent) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAItJREFUOE/l1FEKgCAMBuC6l+CLFwm6TNep
    i3gjY+FgDLf9gU8VjBDyc/mLa611mfoQOLNeYVcp7ci5eQ3AIGMEeigEasxDQ9DCLNQFLWxLqcmS
    exp2yB9LnDArmI+Aei/hX6aJo+JE+Q2DeuJo3NM9oVAikLDdSfi5aORK+nwNxmZn7MDHBr2Rfgje
    ItRKMM9EiFoAAAAASUVORK5CYII=
}]

set icons(redraw) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAAAAwgAwmZAq1tbXOzs7e
    3t7n3q3n5+fv7+////////////////////////////9FEnkFAAAAEHRSTlP///////8A////////
    ////LGZlgAAAAFFJREFUeJxtzjEOgDAMA8B+wZ0yZ+rLEN9oB+Rnk4gkBQlPN9luR6V9SM/lPMlp
    TkpwAghCtcg1gsLFokV2WRJW99DbRrCr5lrfw1n2evZ3/QZoNUzyBudhawAAAABJRU5ErkJggg==
}]

set icons(fes) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAJFJREFUOE/FU8EJwCAQs6P4dsWO4CwdwUm6
    i1XxROy1l0KgBRGvSUwCbiklR/2qIHNRxVpaprv/BM8Q9rJy3a1EUOQuVgUzS5Dr0HLlvR/OR2QZ
    an2ts/VcucJ3cpB97utppmEEy3do9YP8VztEiAjmFhkhvWGaYLEce6mRIthFzVeAXDZHPuZyEbKG
    gd7yF/ELKDsDXlODlTQAAAAASUVORK5CYII=
}]

set icons(network) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAASNJREFUOE+tlL0OgjAUhXVoSEMijI6OPIKj
    o6Ojo8/gxGTcHH0ERsPkyOjo0Idw9DHwntKSUmj5EZKTG376ce7llGWe54tZDwChKIpKLX1tSm3B
    NFQEgbw3Vj5gKlartQke0oUbyPmNYF/SQ4Th3oT5RlO3ZL8dzqTC8Ei1GA3ErGhh2TUzgGcDKqcn
    qu/BM9SuTIcKFFPNlGLBObq4k86uFDRioYESxvkWrkhwVz8nGNvR+asXaLZDD18kjPPEXqicf6hu
    uuY9KdgEuyq1gu8DYn4yOrYTuCPBZRvoioRcgHCr3aLhRi0QeBtahTcImDVDXIPDlITdkqmPVDt2
    RaizJRVy/TJUmUMpxg6+kPf+TRqtVlF6/gU0Ql87ngVogRPXDH8u+jdf401IRAAAAABJRU5ErkJg
    gg==
}]

set icons(find) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAAAARnQU1BAACx
    jwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAXhJREFUOE+t1D1PwkAYB3D9WMZP4KDRRRcN
    iYObmuhMXF1Q0MVowKiQIrUBCxIbBEErWGZxcMHBpbowQIw14W+fo60I1FKgyaVJL/fL83YdBzA2
    0ofAUaCWMwhYi0zCvz4D0b8M6WAF1eyWzhiBuQUJU+ML+K4l2ZLz9wwdCGzHplZPoKkxfFZDLFLX
    YCf2ZWCNSoCl7wrsTFNTeRZZvbKHD3EJtN8XKOx4QIv3eRDdXmQ1M7HGU8DCaOwcQYLKj2UoRQVy
    4QE5KYugd74rMnOG/wVNjMDiXRH5zC0k8RrJ8wT2N2b/ROYImmnSuySXUMgVkLmSkOJFCGc8AnoD
    qGadt8s2wrfTCTTrPn1fAafXLZu+QVpIIRG5QCzIYXdtuudd7Qm2Y0CTOoeQXrdLLg7+OAruMNw/
    2I0RSEvR6zYH7ihii/Xssvq8yQ63kF+M0qfBtUvVtinvr2EDokRbkRGmvXgdsb7m0O0/sqsp5odh
    39aVGRYyz/8AihCzldqHnaQAAAAASUVORK5CYII=
}]

set icons(config) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAAAARnQU1BAACx
    jwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAPFJREFUOE+llLENgzAQRWGA7BJKSiRGyA5J
    GynQZAYmoMgEVMkGmSNVFmADR9/SR8dhc+BYOgFn8+77wzkfx0+G8T6dHa7HosgO90vukykDwGdd
    OxnfpnHIp8QCRnAqNHtU1UxdSGnXdc4K7sYDY1DksfB6e7m1QLEJiJsQlDlufRdQQ3UBy8+FQsol
    KGTBGjQIlMmYryhclqVjUIgJDPk6DEP039wElNC+7x2C0N0K9QuAa6jsos0KdevFoCZQGq/VSigt
    MIHWoUCo9HXWKXiwepXzWNu2rf9IIQuSjigNRQGEP1ut7a3NE0TY30AqlUV/omWviy1GnRwAAAAA
    SUVORK5CYII=
}]

set icons(newnet) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAUVJREFUOE/VkiFTw0AQhU8xFRE1eFxBMFMH
    Ascf6E9AYnHIDgaJRPInMPwCFDUIDAO9aUobGGAGQ9zx3nVzs4TQJaC4mTe5XPK+vN2sc/9xBYS2
    1KquMHt8SZoWz2Eyewp+WuiP/A6YYHlR3o7zNybPsmxHVbD1E3JMp5ONJ/Pyzj8QyFVvh8lsgpWV
    a0UBVxd7c6WeSbLSe59VrgvnTplyF8J+BHUtYvwBPp8HlMnevStYH4BLqMMzXHl/JUmZtrGn38E6
    AuvXEpk9TcmqUgFimiGl0q7LvQ1kmVIqS4gGmK+hHnQI3YiGB84NrDEKAoxzpwXIPXQMbTC19LGL
    /euyH0Ng48xJ6Z+8ONtmb5cCJRXfiSVvLko+l4R72oyzfRkla3q+PodxDToT8JHq70l7mnIQXO/v
    n4BiNsel7UfSSEmvo/8Dk8gZlTZw9lUAAAAASUVORK5CYII=
}]

set icons(newrun) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAANZJREFUOE+t1N0KwjAMBWB9WF/SK6/6FCod
    7seJKHhjvdIeIRJjktaxQRiD+fW0iVuGEBazXgDnrB8sp316VVpcBYfT9UHVj5fUDufUtGOihTzU
    BTm2i90NIC7cLdQEORYPx7Rv+k9CL6kKatg2dncqSqulVEE6M0oGCEipIe8RlC9hO2iAhW3E+cln
    FeQY0vFFJ4FoAD8zgIC8okXVhBzjCTO4zrWiH8tn8wwlSGhpuyaIjmopJ4PW4E4CtVmrbYi6ZWt4
    axryL/j1QZDbN8em5u/lvfMCYx9U8FAnH8kAAAAASUVORK5CYII=
}]

set icons(restart) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAAAARnQU1BAACx
    jwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAHxJREFUOE9jvHTpEgNVAchAamIMw7Z4e//v
    9fAAY1wWgdSku7hglSfZQJiFVDEQ2fUkG4iuAdkwUHAQbSAs/JA1oBtGkYHYDKPIQJiL0WmKvIzN
    UIoMBKVHqroQlsCRDaXYheiGEm0gSCEM48p6+OSpWjCASy5qljQj1EAAxdJWY10KTyIAAAAASUVO
    RK5CYII=
}]

set icons(finish) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAAAARnQU1BAACx
    jwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAVBJREFUOE/NlD1OAzEQRuFsW1BAR4eExAGA
    I+QEiIYWCSQuQEdDFcmioNsjhBtEW6/RM3pmiDfIBQWRRk7smedvfpzD7fbp4E8/AHft7maVb1cX
    +fHhPi+d/7bXwHAWeH11mc/PTov1ghtgSuuiDhuGodrHZtMFbYCvL88FhioUAmWdpikLTSlljJKw
    N45jvawBqm6e56wBJJDflEPlAPXhwtLgWBvTJQgFQHAEQDDfrSnrl9+67ANugDFdAk6Oj0q6MXV8
    MACcY4AXFdpdnGJaqFBlLEVsGrE/FKqOA1NlVQ0g1XohqigN2TiztYZs0JAI4DvOrARGReyrNo5U
    BZouhyq0oyjjQkeJ/dgQ61dTfn/7HmY2nSsgpufsOT6+ItQ3ClXH4e4TA2QXHW5r6yTEmJIyIFPY
    92ZRHV+Ebx6lDbD34ff4Lf7b9ATu8/n/wE9OgMfb1uAm5AAAAABJRU5ErkJggg==
}]

set icons(findobj) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAnJJREFUOE+l1N1LU2EcB/AJQUGXddNlQf0D
    CjKGCN5owXrBsbQXFlFe+VpeFbuIGombujViYWgvNqYex+Zmo7UdOzseZ9t1etFNMjzo9MYL5/BE
    +/Y8p53jzpos1uB7sZfzOd/f7zysTvcfr12vAW/Tp3Tnzp7WHT9xTHfh/JnaNYplA9fxczcsR+CW
    EH3VhZrEUuxizztI2Vnkf0wi5LyrBXufcVXvUI4dFLHcqgvOvsuH11s9/LaT4/F0ij8SLR9TyjJy
    s73VF9gJ3Qb9Xh758Uth2x4T4E4tw7kkYNDJSaW78I9aQMOMWDA9dEvemYLlvrm0GB3T5ufxPMBh
    eJ6XQ9932/+MT6H01zRSyRSExDIWoywmrObKzZQWD0dZPJmLwxZiYQuz6HbENRgFk3wSXOwLoqFP
    CM8E4X5wVdus/PH2DMWl4c8sBt1RFVNGXRFWkFhMIPYxigUmBP8UAxd5AOrOjjorfS5WfSAb7/Uo
    7I0ASMFH9sZG4oj4FxD0zmF2woexXmPVE6HepxQDCgQFJsne5n0BMG+m4Rv/8O/g3xgFaVJkb9fg
    e+2tjq13dhpI1khyG+Nd+JUXisghRsenB7fqqJnmZophvb0dGaMRmbY27Ho88phKM4pJ360qZjab
    C/39HSgN+QwkdTqCrIkmk4qJLS3YvHJJHlEJxWjokslFJrv9RmF//x7y+ftyEok7FGMUMEdbia2t
    IG0hGgwQ9fqDSlgR1GAUVNvRH5BGj2grBdtqbITY0BCk31FUaVbEZjjOgtJ2DsdNCprVI0KAk2JT
    0xhptUMgaau+PkKir3RWld0NDHRAiaZdTX+GVS76DYYtd2i9SfybAAAAAElFTkSuQmCC
}]

set icons(chan_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAMFBMVEUAAACEhIT/////////////
    //////////////////////////////////////////89O65jAAAAEHRSTlP//wAAAAAAAAAAAAAA
    AAAADwvvhgAAADdJREFUeJxjUIICBjSGAhOEocDAyAClBRigNEgKzAcyILQSA5RWYoDSSjBaiQFK
    A6WYsNuFxAAAc9UMXxHyo/oAAAAASUVORK5CYII=
}]

set icons(cogwheel_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACx
    jwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAK1JREFUOE+1U8ENwjAMhNmyQyX4dgn645cH
    O1RVlvB2KZyls4wbaEVEJCtyfL6c7eRcaz11LRD0WFeyqu+5/X8EKaWVdn8t70fFVgJApRRNXJZB
    DX7Ok+48i2RKMI4XAxDY6g1j3JGnBPN8M8leAYAtnypyvr4TiDzWSOYlk4yYDQECDPqaRcT64zFf
    FXwiwPlGAZoBeb6EIwTWRDSSY9wroTnGOLIIOvSQfv0TT168dPIInVHIAAAAAElFTkSuQmCC
}]

set icons(compound_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAGxJREFUOE9j/P//PwNFAGQAJZhBTk7uPyUY
    bMCdO3fIwiC91DUAl1dwuRDDBSCBxs6LKBjmRXTDQYaSbADMcGRDUcIAlwtgtpNtAMy5FBuAHA44
    wwBbTBAdCzCFxCYunAmJZAMoyguU5ESQXgDj9GhR8mUscgAAAABJRU5ErkJggg==
}]

set icons(placeholder_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAMFBMVEUAAAAAhP/c3Nz/////////
    ///////////////////////////////////////////nj/q/AAAAEHRSTlP///8AAAAAAAAAAAAA
    AAAAMIMH1wAAACtJREFUeJxjMIYCBkyGAYMSCDIzGCiBATODEYShjGDApUhTo8AEgsqYlgIAaT0S
    zHIyPsUAAAAASUVORK5CYII=
}]

set icons(simple_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAEFJREFUOE9j/P//PwNFAGQAJZgizWDXU2I7
    3AA5Obn/5GKwC8jVDNKHYkBj58X/xGKYpaMGDLpAJCc9UCchUZIfAGyaNWbkC6VeAAAAAElFTkSu
    QmCC
}]

set icons(message_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAMRJREFUOE+1ku0GhEAUhndvKpEkEpFIJJJI
    N9Bd7E11Xe/Ps73TlD7NZmycH6Oe9zlzOu9xHF9WDwNsygpW3dvYbwPQdcNUgrYVNI3wfCc6dYC+
    JzDDdS2oKkFRCPJcrkJ2AfC8YbUSLMsVRpoK3x9D9gFs92BFlgmSZK4oOnWxD1isU7sKpFWDCENB
    EBgC9F1XaxwrK0H4Pq9gCOAMLqwE4brmGXBAyri1EnQcVca/sHwwGT/KqkGef96Dp5v5n1V+0sUX
    Ts0ofqimM9gAAAAASUVORK5CYII=
}]

set icons(queue_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACx
    jwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAIZJREFUOE9j/PfvHwNFAGQAIdxpb/8fGSOr
    Z0CXRFeISx5mCE4DQAqOrVwJt/nerVv/QRhmIEgO7H18zocpBmmEqUM2BMQGGzB7tu9/EEZnYzMA
    pAZZfNQAaCDiigmiYgFfQiGUDsDRSG5KhKUNgvkAOd6RvUSSASBDYEkZRsPzAqGcSEgeAEvthurz
    oY+NAAAAAElFTkSuQmCC
}]

set icons(container_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAMFBMVEUAAACEhACEhITGxsb/////
    //////////////////////////////////////////9GEEOiAAAAEHRSTlP/////AAAAAAAAAAAA
    AAAADW2LcQAAACFJREFUeJxjcIECBiwMR0EgEAExjIEAwjBghjAok8JpKQCFmhqioMIOzgAAAABJ
    RU5ErkJggg==
}]

set icons(stat_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACx
    jwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAElJREFUOE9j/PfvHwNFAGQAJZgizWDXU2I7
    UQZsdnH5D8K4LCLoArIMQNZEtAG4NBEyDO6FkW6ApaXlf1IxLF0QTAeEUurAGwAACvmYamLLnngA
    AAAASUVORK5CYII=
}]

set icons(outvect_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAMFBMVEXAAAAAgAAAAP/a0tL/////
    /0D///////////////////////////////////////8Dfx5lAAAAEHRSTlP/////AP8AAAAAAAAA
    AAAAF1YY2wAAAEtJREFUeJx1jbsJwDAMRF/hLCKcPYRQemNy+68S27hIkVz14H7kFl8g6Z5wDVCy
    wQsZZhLDMnVrJYlT6qxwA7NKOocUFWfV34O/pw8hWyAp4RketQAAAABJRU5ErkJggg==
}]

set icons(gate_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAD5JREFUOE9j/P//PwNFAGQAJZgizWDXU2I7
    bQxwcHD4jw+juxjDCyDN37+nYsUguVED6BUGFEUjqSlz4JMyAI6uuXkgcWyIAAAAAElFTkSuQmCC
}]

set icons(param_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAAAARnQU1BAACx
    jwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAANVJREFUOE9j3L59OwNFAGQAJZgizWDX47Nd
    z3fJfxDGpwanAd4ZK/6HTJkHxiA2LkOwGgCy1SJ54f+wRdPABoDYuFyCYYBH+qr/RnGLgJrnwXHI
    orlgMZAcuktQDADZ4tM+D4z9O1AxTFzSCtU7GAZY5M7+D8KOldMhuApCw8TxGgBynkPssv+KPnP/
    e/RM/+/VNQ2MQWwl37n/QXJ4vQCTVHdb8l8zePZ/r2lAA5qmgNkgMWwxgTMaPZMXwQ0AsUmKRphi
    kH/R/UyUF0jJG7TNC8S4BADaZQ4nNafa9AAAAABJRU5ErkJggg==
}]

set icons(tree) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEVAAADGxsaAAAD////AAAAA
    AACAgIAAgAD////////////////////////////////GxcxdAAAAEHRSTlP/AP//////////////
    ////0XJbHgAAAEBJREFUeJxjEIQDBkHBRCKYogGhgUBmWlqioKixaSiQmZiYKChgbGwAFk1LgzJB
    oqLGxqYwtQGhoVQ3DMnpMAAAQhIfb/Voq10AAAAASUVORK5CYII=
}]

set icons(unknown) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAMFBMVEUAAAD/AACAAACAgID///+A
    ////gP8AgIAAwAD//8CA/4D//8CAgP8AAP+AgIDAwMB6idRUAAAAEHRSTlP/////////////////
    //8A4CNdGQAAAKZJREFUeJxtkkEOxCAIRVnMvoELmMwFvMIs3Pf+txgS9xSoFjQlaWJev/+jAu0H
    H/8aQNMFnLLU/w3gCg6mkkBXIBsQrsKo9QASQZykq6mBarBGrK35AaogA5QUVhMcE+B3pgzBDtB3
    BBgC7yMsuUSKCwg3UDgAuQXlPsyo3ilcNkDpEh2ol/Y1Fad7jZOM0+qPkZJAPMPby2VFXxp7B/cg
    2ESAT8QFuTKHjk1mSQUAAAAASUVORK5CYII=
}]

set icons(1pixtransp) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAABlBMVEUAAAD///+l2Z/dAAAAAnRS
    TlMA/1uRIrUAAAAKSURBVHicY2AAAAACAAFIr6RxAAAAAElFTkSuQmCC
}]

set icons(16pixtransp) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUAAAD///+l2Z/dAAAAAnRS
    TlMA/1uRIrUAAAAMSURBVHicY2AgDQAAADAAARaJmtEAAAAASUVORK5CYII=
}]

set icons(modtype) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAAAARnQU1BAACx
    jwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAYJJREFUOE+tlM1Lw0AQxfVfEwRRUBQPIooe
    9NaLePEgqKeCRWyh9ashKhJaiiVQaYNBsa1aUEsRingQPQT0IIJHKQTGfQu7xDQfUDPwWHYz/PJm
    Jpv+DcvqizQAjFKRwni1wp277Ffrlio3cVL1eaY5LuxxHtgiL2C1ucMBOSNGZ7U1Kexxjue+UDcQ
    ybv5SSpdrVO9tUcPbU3KbGyTkC/UCfz4fKa0NkbXLYVEPL1UONAZAor8LqdOIHqklWN0ai7T5V2K
    MzqdH74XUAHLG0vcbSAQA8gWpkgpznIJoPX+KPeAKIVpLuQHAlFuQh2izeygBJRrcbJtm7AiBAwr
    8kMdZliS0yHKhUOUjkArANtSh8MdopyMNkHJo1HpEEBIAO/bOdaWGZ7nOWnnUL6+31jJA1Q0V/5M
    FcBqc1+eAYi80CmjHygpdTJCx6VF0i9WuwRYWhvnpXt+3F43RUAP9QVyCy/zheENQXfZYN/lARsA
    BoX1vJHo7S7/6//o57BnaNTAX9fnY38wi/BuAAAAAElFTkSuQmCC
}]

set icons(channel) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAAADGxsaAgID/////////
    ///////////////////////////////////////////WYDUgAAAAEHRSTlP/AP//////////////
    ////0XJbHgAAAClJREFUeJxjEIQDBlKYAkpQwMggwAAFjAyCMCZOExAKkLQhGUamcxBMAJaCC0ur
    kZPoAAAAAElFTkSuQmCC
}]

set icons(props) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAAADGxsb/////////////
    ///////////////////////////////////////////TdTWlAAAAEHRSTlP/AP//////////////
    ////0XJbHgAAAClJREFUeJxjEIQDBhxMAQYwADOVQEABzFQACSpgE1XCKkqZWoQbCLgXAJGwDaRR
    Yr5VAAAAAElFTkSuQmCC
}]

set icons(cut) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABMAAAATCAMAAABFjsb+AAAAAXNSR0IArs4c6QAAAwBQTFRF////
    2NvmvsPNnae5tr7MFzJdeYedTWB7Youzc5W4rsXdYYuzK22jR32rSH2rEV6bEl+cEl+bAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAd4ngqAAAAAF0Uk5TAEDm2GYAAAABYktHRACIBR1IAAAA
    CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH2AUVCjYzpsVpigAAAGNJREFUGNOVjksOgCAMRAut
    Han4u/9lFTBR6MrZ9SXTN0T/w9GhAHEsqq9qYTJUmUTxXCmlYgBDJTS0GNlMOuHjWIlsUwWH91E2
    syzcLznO/RbCL5Fm6tJMfappYNU0lqvpVy5+VAJUiVmQ7QAAAABJRU5ErkJggg==
}]

set icons(copy) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABMAAAATCAMAAABFjsb+AAAAAXNSR0IArs4c6QAAAwBQTFRF////
    8/X7+Pn8Y3qn7vL68vX7+fr8+Pn7XnajZn6oaoKsbYStcYixc4myfJK4fpO6jKDD8PT7gZe8hJq/
    iZ7BkaXH3uj43ef33+j35Oz55+757fL68/b73Of33+n43uj34er46vD59vj75u758PX78vb79fj7
    9/n7mpqQmJiRnZyNmpmQoZ6KqqSEpqGHop6KnpuNxLRzwbJ1va93tKp9tap+sKeBqqOFpqCHx7Vx
    xLNzwrJ0wbF1vq93vq94uax6uq17sKaBq6OE4MiP1LJo1LJp2r181bJpAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMOlcgwAAAAF0Uk5TAEDm2GYAAAABYktHRACIBR1IAAAA
    CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH2AUVCjUm4DXeogAAAKxJREFUGNON0NkagVAUhmFC
    ZjJsaaKEZCihzDLm/u/I2kvhcdS3zt7nP1qJROy2Ub/Gsuw/7wwmSx16RLgfkroDbjBM8HTetszI
    gwV4Mde7BfcD2rlPuBO4nJShI5orSWkfvFEpF1I1H83TCLcClzAXbaaL4kULd5qHZgmEW4PTdPGK
    ZququhHCnWChjTukOVWjbLSJovDUq6V8u9uao5kQdXq8Mvr8wfwW/6EvBlEaopGOlEcAAAAASUVO
    RK5CYII=
}]

set icons(paste) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABMAAAATCAMAAABFjsb+AAAAAXNSR0IArs4c6QAAAwBQTFRF////
    9vf68/X6h5Suh5St8vX7+Pn7XnajbYStX3OWYHOWcYKgh5Wu3+j44ur47/P67vL5gZe8gJS0gZS0
    kaXHgpGqh5Wtl6fAmKfAjpuwjZiqr7rM3uj45u348/b7jJiqrrrM3uj34er44uv46vD53+n34uv3
    5e348/b6kpum3un3kpym8vb6q8HU9fj6mp+hmaChoaScqKiXr62Su7SKtrCOsKyS4MiP2r188sZx
    8cZx8sl58ch58syD8s2D8tCO8tGO9NWZ89Wa9Nml9N2w9eG69eTC8cVx8sh588yD89CO9NSZ89Sa
    9dil9Nil9d2w9uG69uPC9uTC9ubI2K5szKh10Kx41LB7zqx5xZphw5pkzql2x6JyyqV00656wZts
    xJ5vvphrrYFSr4RWsYlcs41jvJZqtZBn5NbG1MGvAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAZEjVUgAAAAF0Uk5TAEDm2GYAAAABYktHRACIBR1IAAAA
    CXBIWXMAAAsTAAALEwEAmpwYAAAAB3RJTUUH2AUVCjYXmsaNWwAAAL9JREFUGNNjYCANSOrqSqIJ
    iSooSCuIIglkREZyS4iLS3AnRWbAxMKDuYSFhYSFhTmDIxBicBAKE4sLCnQLMgGDKJhYmKtrgKsJ
    GxBYmMLEol38XfxN9UTYGc3hgrG+fs7OZnKsOhoaTMZQsRgnH0dvI34RQQ52ASOoWIKDvZeXoQoY
    GELF4m3tPD0NZEHq1PWhYok21h7W2kpqfMpKfJpQsbQQd0sreRlVXi0tRSmoWGZ6akoyM48YCwsQ
    kRCWAE2wIld3Fw63AAAAAElFTkSuQmCC
}]

set icons(down_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAAUAAAATBAMAAACqztpQAAAAMFBMVEUAAAD/////////////////
    //////////////////////////////////////////87TQQwAAAAEHRSTlP/AAAAAAAAAAAAAAAA
    AAAAE1gGDAAAABhJREFUeJxjEBQUYMCFQUAACAUZcatBwgB/EQNjxeU9+wAAAABJRU5ErkJggg==
}]

set icons(node_xs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAAYAAAAHCAYAAAArkDztAAAAAXNSR0IArs4c6QAAAARnQU1BAACx
    jwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAADVJREFUGFdj/P37NwNWkJ196D82zAATzMxc
    9R8ZgyXQBUF8rBLp6RP/MyCrBgnAMAMyB5kNAHL8XDUQQ11rAAAAAElFTkSuQmCC
}]

set icons(modnames) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAADAFBMVEUAAAAlJSU8PDxRUVFjY2N0
    dHSAgICFhYWUlJSjo6Otra2xsbG0tLS/v7/BwcHMzMzZ2dne3t4AAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAC7h23zAAABAHRSTlMA//////////////////////8AAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAWHyGPAAA
    AG9JREFUeJyFzksOgDAIBFAppbVaS73/YbGiqDF+ZsHiZSahk4d0bxjmuViG8I3lActw5sB8WjbM
    4ZL89ZIGbsisuF6pXBV7olYDxHY9RtyalUHnjivYnHw0ZGcIozZ5dZh2TM6TFyRMIpND/PvzFxdu
    XvEgWbY14gAAAABJRU5ErkJggg==
}]

set icons(zoomin) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAADAFBMVEVCazlKczlKc0pSQilSazlS
    e0pahFpjWkpje5RjjGNrc3NrhKVrlGNzc2tzc3Nze4xzhIRzjJxzjK17c3N7hJR7jIx7nGuEa1qE
    c1qEnKWEpXuEpbWMc1qMlJSMnJyMnK2MpYSMrb2Uc2OUe2OUe2uUnJyUpZyUpa2Utb2Utcace2Oc
    jHuclIyclJSctb2cvc6ljHOllHulraWltbWlvcalxs6lxtalztatpZStxtatxt6tzt6t1t61nIS1
    pYy1tca1vb21vca1xs611ue13ue9tbW9xs69zta9zt69zue91t7GpYzGvaXGztbG1u/O1t7O5/fO
    7/fW1s7W3t7W5/fexq3e7+/e9/fnxqXn5+fv7+/v7/fv9//v///3////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    //////////////+MBfgOAAABAHRSTlP/////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    ////AP//////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////8q7QIgAA
    ALZJREFUeJxjiMMCGHAKhmhKK+o5RaII2strWJmZmhhHIgl6SJpY87BJOXvIRyEEpRW9AjmBggFO
    bghBbjMeTh4eRjGxMFUkQStWVqAwC0uILEKQw5qHk5OHQUEhHEmloImlMycTT2yMgwNC0Jff04+H
    iTM2issf2Z387gEhMW58wrquSD7ylxUQFTAKshBX0cbwu49BqJYKRoBoe4cqKWGEkrZhqJYMRtDp
    WNgxY4YnL7sEjkAGACd4cD2Fo8KaAAAAAElFTkSuQmCC
}]

set icons(zoomout) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAADAFBMVEVSQilSazlSe0pjWkpje5Rr
    c3NrhKVrlGNzc2tzc3Nze4xzhIRzjJxzjK1zlHt7c3N7hJR7jIyEa1qEc1qEnKWEpbWEtYSMc1qM
    lJSMnJyMnK2MrYyMrb2Uc2OUe2OUe2uUnJyUpZyUpa2Utb2Utcace2OcjHuclIyclJSctb2cvc6c
    xtaljHOllHulraWltbWlvcalxs6lxtalztatpZStxtatxt6tzt6t1t61nIS1pYy1tca1vb21vca1
    xs611ue13ue9tbW9xs69zta9zt69zue91t695+/GpYzGvaXGztbG1u/G5/fO1t7O5/fO5//O7/fW
    1s7W3t7W5/fW7//W9//W///exq3e7+/e9/fnxqXn5+fn9//v7+/v7/fv9//v///3////////////
    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    //////////////8c2/2kAAABAHRSTlP/////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    ////////AP//////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////////NF1uiQAA
    ALFJREFUeJxjSMQCGHAKBquIymjaRaMIWkspmxkZGuhHIwm6iBiYO1ho27tIxSIERWXcAkId3O39
    7JwQgmxG7Ox8IBChgCRoxsTECAIREghBFnMxaWkxIIhBEuQxMLL3CQiJibaxQQh6cbl6+/jHxEez
    BiG7k8vFLzjGiZNfwxHJR74S3ILceoEmQvJqGH731AlXlccIEF2PcFlZjFBS0w2XE8cIOnUTKwbM
    8ORgFsYRyADbo3SgHWkVkQAAAABJRU5ErkJggg==
}]

set icons(toolbarsep) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAAkAAAATCAYAAABC3CftAAAABGdBTUEAALGPC/xhBQAAABh0RVh0
    U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAEBJREFUKFNjYKAJuHb+2P/NG1b/f//6+X+c
    FmzesPh/b0fVfxDAqej58+dgBf9/41FElB9G3URUMDEMxnDC5XIAtLR9uTyVSNcAAAAASUVORK5C
    YII=
}]

