#=================================================================
#  ICONS.TCL - part of
#
#                     OMNeT++/OMNEST
#            Discrete System Simulation in C++
#
#=================================================================

#----------------------------------------------------------------#
#  Copyright (C) 1992-2008 Andras Varga
#
#  This file is distributed WITHOUT ANY WARRANTY. See the file
#  `license' for details on this and other legal matters.
#----------------------------------------------------------------#

set icons(defaulticon) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABGdBTUEAALGPC/xh
    BQAAAAFzUkdCAK7OHOkAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAAAZiS0dEAAAAAAAA+UO7fwAAAAlwSFlzAAAOxAAADsQBlSsO
    GwAAAmpJREFUWMPNmbGr2kAcxz85fbq8QR4ZHB0K9h9wESl0cRaHrh1c80+UDh10
    Ezo6K+4uHTKXLoKz8BAXzYNQRAgYcl08G436YryoAbnjLp4fvr/f93fHCf+fZ+A7
    4ADyTh8HaAMFBWVs2xLwC/hgmqbfarVEuVwWUkoApJSofhAEu7HwXPidOHPhdaSU
    zOdzBoPBZrFYPAGvwGfg1dgq9wf4aFkW7XabXC4XWTwIgsjYubm476t+EAT4vk+n
    06HX67GFrGSAb0DDsiy63S5CiLvAKWWr1Srr9ZrxeFwAhAE4pmkWZrNZNp/Px/6x
    a8cP4Q6VrNfrm+Vy+VcAZqvVEo8CJ6XEMAyazeYTYAoAZYhHgFNtsVgEQBxz273h
    lMMBsqpzCzNcAqlMIx4RLuzq7LEQ6w5pErh3AdPKt6sV1BHquHDnoPcAdebhe3CX
    KLqnoI7SkiTPEudg2nBxYE8W6keAO5qDSeqeLrhjsLFdnBbcOSW1mUQ3XFi9q02S
    Vqv6J3MwrhnShjup4L3gDneZCGDckJ5znq42ch5Mmm9phXnPxdfCpQUdyyQ699fE
    R/5TBtG5K2hRUKcK2hVMA+7aaJwNcRr7a5JSI47VwUeAiyh4q/31UgVTyUEdcHuA
    0+k0kFKKNOEuhXUcZ5eDb8PhMPA8b7eQ7k3/Ujjf97FtewO8ZYAXz/M+rVYrarVa
    6mGOE/5+v89kMskAPzPAb+DLZDJ5cV2XSqWCEOJmh4JD5fr9PqPRSF0Bf41cohcK
    Bb/RaIhSqRS5Mwwnr6r2qj317qnvH445joNt2xvXdfcu0Qk9z8APHuNvCFNB/QNd
    ZWqtV/QFlwAAAABJRU5ErkJggg==
}]

set icons(imagetoobig) [image create photo -data {
    R0lGODlhmQF6ALMAAO/v7/f39///////////////////////////////////////
    /////////////////yH5BAEAAAIALAAAAACZAXoAAAT+UMhJq7046827/2AojmRp
    nmiqrmzrvnAsz3Rt33iu73zv/8CgcEgsGo/IpHLJbDqf0Kh0Sq1ar9isdsvter/g
    sHhMLpvP6LR6zW673/C4fE6v2+/4vH7P7/v/gIGCg4SFhoeIiYqLjI2Oj5CRkpOU
    lZaXmJmam5ydnp+goaKjpKWmp6ipqqusra6vsLGys7S1tre4ubq7vL2+v8DBwmkA
    xcUUxsYBFQHJxxfNycsbAdHK0xXO2sYa297Q1gDVHNXS2B3OH+HiGN7mGeXvFu7p
    r/US29na7fvw9OzI/j3jJxAAM3rnKKxzljDDPQ75LhQEqPBfwomwHkacsLGitob+
    EhZuO4fRYcmQAhuKZIgumQeRICdSFLCSJceCGV3etEmz4wSY0GRiOynxZE2ePQuC
    1MetA9B5Mn8K3fkvZ1N8yophixauqFadTLVu5fmQRFmqM9cFVObxqkm33bLCxQpX
    LV2xUqWhzaVRrkG6XQ9y09t2JsdqJMGWOJtUq4Vw0yA/Jvx2oIaulPcW/it5HuK1
    lmv1PXZ18Fy9gfM69oDzA+POYSNnprpU8wbUiu9aRMmWtcBYow2ytSYgt2TYxXPf
    /u1aefK5uqN7DQ0VumDHyJ/vlu67qlXLLrkmXWYcbObg91p3p679b/VnjNsvt16Y
    dlh3id26Q/vtu3vtjT3+Rx5clKUmH3+lMbfef7bdx52DcdFnH2+hKdjgfrr1Z49i
    Ovl112bejNVbe+Y5F8Jrs90l24ig1fZgUCmBxllZsGF44C3BUdgUh0ZRZmN8IKDI
    oo4rrlaYizcSZOE9yNWoIZD+gaYjQDyq1944qg0E5YJKpoXeOXZFyJ6M9MhopoxY
    TtmgaFW6ZxNYR/EUZ3pWzjfmnEY2tp2YGOJp5ENh6qkgUazkyF2J0AE60VB18unP
    nlmG2JJ3jNFJYGZ+MmphoW2qpumMQxIJIlIkagiRiVOSGqmqXX6TnahJvhjnRY2q
    Ymhjn8J6nWE0rZMmmabaySA48lwGGZL3uZqintP+nPVqPNdMV+Yw1FZr7bXYZqvt
    ttx26+234IYr7rjklmvuueimq+667Lbr7rvwxivvvPSOgFBMtUIrDr73JhvslC7q
    +yuCPr03LTPHkpOwtIYtdKqEpebzKrMZPomqGUr569NRtMZIcD/+YsCxxiC3GuzI
    MEoaMrAPj/lxOhN3dtKWZBBK1Jz5eRxxyanyOifJW96s86ofrYxgy8MC3aFzlnoX
    qxpRvQwnUTK52ehToyJFqME2Zpp10QiKSHPQrWXn5KAXl6Goj2lfGemnDIZJM23K
    2RTo3Oq06aXeYAYnHm8Gdiks0hC+KO0bNLIN8av75hx300mnLNyQc+M9qWX+zxKW
    +YjSJChO22RDHCt6hLtxFuQaBs4nQlJTh1tdHw3ceuSOHjldkbxql6vnAA6+ekew
    IWel5WCcjujBli8KLM/HzVZTQ7XWfqbBhh9qGjvEgZ52nZArDV7bYxjvOfLgVwz2
    7LtO+PVM0QtO/eFPW3+MeOJpD3Gdqc02fPlhiK8l2qJrHcN8UiATIWYk6FvPUuJT
    DwYeL0BssZ/LzJe44ehvSfwrXt2ORzsdSWRg9QhU9XaFH2rILYPvqc3ENLcsxf3F
    Q72TnvsI578OjvAMFfxT2szmQvdkZ2wlgdb74ueUZWVJJSwM1dlAtbQJ3vCJR0oR
    EAMohrVxToIU8dX+hXIzReZoUU1QFJkR0bQZMkZKSoJqluhC58TlJa2LNqwZ1dTj
    p+kJyo0hnIrXKAilqAmqhERDIFXQosY2qmdrWMMjB//VP+5ZCWd2dBsfm8iePGJw
    U95zCyRJKMhByi+Oh7xaJxU5PhvJEVI7y+Eon4Y6ZYWKYn+8ICZJCTtATsaWnsRV
    Livzo1oVbJKlZKQGQ8QvpylkYYU7IjDnt6zgCUx2W6Mle56psGKFxVO7NBnIovlF
    rlnMmPUKpzjHSc5ymvOc6EynOtfJzna6853wjKc850nPetrznvjMpz73yc9++vOf
    AA2oQAdK0IIa9KAITahCF8rQhjr0oRCNqEQLJ0rRilr0omCIAAAAOw==
}]

set icons(apply) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAjAAAbgDs
    JRPvPy7qRjbcVknYZFjlWErnaVzteGrlhXnqpJnkw7vs1Mzp4tzx8OqVHN65AAAA
    EHRSTlP///////////////////8A4CNdGQAAAENJREFUeJx1zsENACAIQ9E6AhO4
    /3Y4ASJgE2Lk9PJ7AcbDS8xLHaweiycWT0xG7FTk7gQyRsWlSe5BIZfwnTW/T3Zu
    ZHqi/OzMrT4AAAAASUVORK5CYII=
}]

set icons(revert) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEWVIx3zGQbs
    JRPvPy7qRjbcVknYZFjlWErnaVzteGrlhXnqpJnkw7vs1Mzp4tzx8OrYRYc3AAAA
    EHRSTlP///////////////////8A4CNdGQAAADtJREFUeJxj+A8HDDiZ/HDmBxD3
    A5TJ//8DP0QBUJgBpo2BgR/G/MDwH1MUSS3ChA9Qa2AyH/A5By8TAIMapzuvxOjH
    AAAAAElFTkSuQmCC
}]

set icons(loadned) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    APVJREFUOE9jYBg2wNzc/D8MU+wpkEHIhsD46OIYFh3uNvuPjPG5hKBr1+ao/EcH
    IDFshhL0/uFWs/8/XswA4w83Jvx/caHj/4MDFf9vbCj4D5JDxwTDcE+r0f8fH05g
    xd8/HEERB6klbGA90MAXG4jC8+IVCBu4BWTggwUoeG2R/n9iMFbXri3S/v8DGHYw
    DDLoxwNgmOLBoHAGqcNq4FJgbP640QHGYMOgbBiNHKv42HDD58XL/v9xoQJi2IUG
    DGxrbfk/P/8IXoySyPuDJKGGVYANRscgxSQZCHLqvDT1/7gwWQYSymYku5DuBhIT
    0wRzEDkKAJzP7cEIHfqHAAAAAElFTkSuQmCC
}]

set icons(save) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAADAFBMVEX4+Pxaeatb
    eatbeqtbeapee6phfanc4+/s7/Rbeqpgfqlkf6hkgKhogqeXstm1zvK3yeO6y+S+
    zuXE0ufJ1unO2uvP2uvP2urw8vVshaa6zOSyw9u7zOSyw9q+z+a/z+XD0ufD0ubI
    1unJ1ujP2+vO2urV3+3V3+zb4+7i6PBng6drhaZwiKXI1ujP2+rn7PLP09i5xdPb
    5O7h6PDm7PNzi6R3jaPs8PRYdZF3jqN8kKLi7fd7kKLh7ffs8/nb6PLh7fZ/k6Hc
    6fLs8/jw8/Xb6fLr8/iClaCDlqDz9faFl5+GmJ+ImZ+ImZ63w8Zxg4aKm56xvb+K
    m5z2+fn3+fmls67+/frkz53///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABlycU6AAAB
    AHRSTlP/////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////AP//
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////pKxGFgAAANxJREFUeJxdzdtaglAQQOGJMKUm
    ThrZUZLUTBOTjI7bIxWVOhnGvP+TuP24679adwv4H+AuES1+NhayusCzOJ7/ZeZx
    /A38WZ5SIv0mCZWnX8AfYYGEEJM3ISgM34FHdz69Ss/DIfn+CPilGVA0iMaDcURB
    8AR83+tRmqH81SNwv944o8xJo94Hbnccp3NYc6SDy1ob+MgreSXc8G6qXgt4v3jh
    Ikgpuq57Dbxn2xXUdX25xMq5jcA7lnWMhmGsVmhZp7vAOdM0UT4fUpSVA77dVjVF
    UbcUTVMVTV0DYu00iiVrVdQAAAAASUVORK5CYII=
}]

set icons(undo) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAAAAAAITG
    xsYAAP////////////////////////////////////////////////9MSdVzAAAA
    EHRSTlP//wD/////////////////8qlaxQAAAC5JREFUeJxjUIIDBkqYgoIQppCS
    IIgAMQUVgUKKEKYQgimIxBSCqQUDIQrdAAYA5lYYQC6lU50AAAAASUVORK5CYII=
}]

set icons(redo) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAAAAAAITG
    xsYAAP////////////////////////////////////////////////9MSdVzAAAA
    EHRSTlP//wD/////////////////8qlaxQAAACxJREFUeJxjUIIDBvKZgoIwpiKQ
    AyKATCGgiJAgnKmIYAoKwtQqIpiUugEKAPDvGF5qge68AAAAAElFTkSuQmCC
}]

set icons(step) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAB4AAAATCAYAAACHrr18AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AOxJREFUSEvlkzEOgzAMRduzRWJA4gKsINGrdGlvAGPHLj0A6hk69DaujGRkDMZO
    MjAUyRKQxM//2zmHEE6HPAg+IrKgn2EAHjECksAIe1XVIm5lCRjvvgdPAdHgZ11P
    ACusAqLAmOzatibUo94N/o4jPLpuAb0UBVBoDmi2u8HYU54cgfemmfuJbmzBcR/B
    +bsbLJPyJFyVtg//Z4M1KBWg2Z4E9lyRPeWqYj4omCD2WxZm9XvqsWadNhjyjDwf
    ZTUp5JVLMN8jHeGTy9fkO+1bTbWmUqqyBsyaidnqFMVW8r119z3OgWyd/T/wD4lt
    dmEueZ47AAAAAElFTkSuQmCC
}]

set icons(run) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAB4AAAATCAYAAACHrr18AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AKBJREFUSEvF1GEKgCAMBeA6m+APoXt0mk7TSbyQMcEwUdjeHhQMMpjfnOmec95+
    eQRG4j6OIoHk1sWiiYJeKdVA5qDACE6DrTgVtuB0WIvT4TNG1c9GhbUo7ThJey2o
    C25nF0FfOIRQWrQJZTy+z75ZV9rmrHusRfri+hz45rKueOyOC9a0ddYZBP3s8Wpv
    Vxil1WjVnjz4AvGglHOMFvAA6+wNcaj1cBwAAAAASUVORK5CYII=
}]

set icons(express) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAB4AAAATCAYAAACHrr18AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AMRJREFUSEvllVEKhDAMRNezFfwQvMeextN4kl7IJYVIiJOaWZX9WCFYOzgvSYMO
    tdbXTy4Bo1jneZN4SodQgQl0maYWUWJX9BQYwW1i3+hpsDf3YFanwNYcgRmdBqt5
    BM7qNPg9jm3YInBWp8BqGoEZPQ22pgjM6iE4+nDctd/ApZRNQtf+7nX0rAlZzXvb
    pHewfTFKoLdvNe+FunSo2BucVYB0C9JOeni64rOO9GAInjpjZGpnAq1759t+xXdN
    Kevzf+APXxPiOSK2cIAAAAAASUVORK5CYII=
}]

set icons(fast) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAB4AAAATCAYAAACHrr18AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AMlJREFUSEvF1GsKgzAQBOD2bAF/CN6jp+lpepJcyLKByHQ621QdUAjYPPbLGO29
    1nq75Ap4b3styxotWzcab2H3ojE/Cj/nuTW1fjRugRWOcLa504lVcoYVboOxuIIZ
    t8K9eAYjboUf09Retgzu47aXK5JgUQXjuA3mogzz+GF49O0jrNANLqWsvfWi/Dv6
    eZ5ah2ecoR8wp1AbUUljHvcH+Av9Soxps3uGFDw6ijQxPkJVGPvsMCfOzvMU/M+j
    cc859M/l2MRl8BuM0PuTFfR9IwAAAABJRU5ErkJggg==
}]

set icons(until) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAB4AAAATCAYAAACHrr18AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AK5JREFUSEvllN0JwCAMhNvZBB+E7tFpOoNDdBIXsiQghCLmh4M+VDiQNuYzF3Vv
    rW2fDAJruo+jk7Q4z38VSskIepXC8iRfxbrBKHgIHIGnlPoQnyuLddLqYbkXDgVL
    uDaHgs+ce62VReDVHAYmqKVNIwYC9kIJHgJ7KrPG8qmm3UhLVt/klRjr5HoIeJZY
    2yQELHvzdkS6Aq94BYOArZVFez9zxPRkWvvmifsf+AGKGPyWl7USBQAAAABJRU5E
    rkJggg==
}]

set icons(mrun) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABgAAAATCAYAAACKsM07AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAJNJREFUSEtj
    vHTpEgNNAcgCWmKaGg4OHVq6niQL+ry8/sMwKY7C6QN0Awnx0S3NcHP7j9cHhAzE
    5yOgXCJWC5CDgFCQYFML8wVIDq8FIAXEhjMWn66itQXgxEAwDoj1AbI6ZN+gWIAs
    QU5SBOoBBwvVLQClFmyOwwgicnwACgJCmKScTE6cjFpAVElMlCJywx+kDwDiQgVV
    /+qK2gAAAABJRU5ErkJggg==
}]

set icons(mfast) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABgAAAATCAYAAACKsM07AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAKNJREFUSEvt
    ksEJwCAMRdvlPDhJp+nVXRzDhWwjBmJQEy25tRCoGPL+//FMKR2mHwAsy3R4ScdS
    /RLg9j5jjURdzmV+N3TAB0rnd7i3BkQKwP/GAY1AioTeg3o441DqpguAZu3ycTgD
    hKkDDaCqjMxJEUZhW88U1E2qiasAqArpKc6i68X1GVCjClxks4NdB0JUZR9bO9C+
    sB+gilfVtJI5730Adz35C5MGT3QAAAAASUVORK5CYII=
}]

set icons(stop) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AnhJREFUOE+tlPdO40AQxpPnuFei9957Db2JjpAACRAIkJAQD4AQiFdap9iOEzvh
    cn9wx3czE69JPd1JN9LK6/X6529mvnU4VCHU7S2C5c/PUBiQEaK5jm+RSLjSu2Vr
    6uEB6uwM6uAAancXxs4OoltbiG5sILa2hvjKChI0N8/Pvz5ajaweH6FOT6H29qAI
    YtCLUYLECBJbXEQ8EkFifh7m7CyshQVYtLeqSnV/XwxbX0d0dVVgcYYRKEEgc2YG
    1uQkrIkJ2LSWPDoqhwrs5ASK0guUMWx5uRg2PQ2TYWNjsEdGkKTh0L1DpQmUxi4u
    8so0TCtbWkKc0pI0WRnBWFUAGxqCMzCAVF8fLLpaU1N5qLq7g9rfh7G5CaMEltAw
    2lwG6+9HqrcX6e5upDo7C4A3NzC2t8HxM5eTKysrDIZl395k6f31FQ7BdOSen5Fq
    b4dNe0ShcX0Ngzr66+MDMT/NxNycFJ9DK+N5cnBQ1lgZR5qUybWlBTbVVYDRqyvx
    WGEwzKQ0Beg3gOdaGaep48fTE9zGRmlQHnh5mTcspcnKOBjGyjhsKn6Zso4OeeY1
    NyNDMLe+XvYIkLvM7i8Ma3wcFn1R0qQOOtTJ7y8vcs81c9vaZM6wbF0dvJoaOIVA
    OUrasASzR0eRZGU+LNXTI/VKU/Hd1tZAGcOytbXw/BF40Tw+zh8lDRseFo+xsoqw
    hgZRxrBMKUxTrcND2KSSa1YE6+r6UtbUhIwPe6c0PU6XgFXPs0l/GJPVkTLuZNqH
    eWQL719h+is2HUGLCszuZ8Oyx1yCuaSMFWVYGXX1j8pKJdtkGxnkQfYXN0jOLR83
    Ggz8q5/r/9j0G+jYI3vCkWPrAAAAAElFTkSuQmCC
}]

set icons(as) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AHRJREFUOE9jvHDhAgNVAchAamKqGgb2LTVdRx8DO+3t/1PiagwvgwykxFAGmAHY
    aHJcitfARBsbkr3PANKEjGEuRTZs9uzZ/y0tLf+DaJCr8fGxhiG6y0CGwTDIQHx8
    DAOxeZMiF5ITEch6hmBOGfUyyZEGAMZ+W/3+qmhjAAAAAElFTkSuQmCC
}]

set icons(asgraphics) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AI9JREFUOE9j/P//P8MooH4IPLze959YTNB2Yg1CVofXUJoaCExQoESF4X10caJc
    CDKLagaCDIN5HZkNEsMmRyBiEIahG4puOMwCoryMHjnI3n9wpR/ugxtnu/DnXVyx
    DDMQZBgIgwyCYbJcCLIIm2HnDreQ7kJk1yCzQYYRNBDkfJBr0A2BaUanCWa94a8A
    AAl81eQA/IZhAAAAAElFTkSuQmCC
}]

set icons(asobject) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAARZJREFUOE/l
    lNsNgkAURLEmGqAI6qAGi7A8H/hEUFQE5Z3rDGEN0aBr4oeJJPN7mDO7YBj//TiO
    M0TkgwxfLkZQXtaSFbVc81qSrJI4rSS6VnJKSjnEpYTnQnZRIcGpaF78FpgCZtt2
    kxig6FLeYfsW5gO2PeZ6wAtamabZhDA0eIplWbI59AAxwkDVpkICxTMVATtCM4Qm
    mwXQ9NHKA2gd5rLaZ3oNCVPK3b2o2IUtdj1A66Ehx1fKHL9P2Q00G/IkH8fnXito
    LqE5B8j1U5luUz1lwpSyB81Nu9cSioTNWtjY0wTyfilljt+nrA3k+FQkjIocn3ux
    2QSaBKloXewubN7CuNekA/oE+N1v+Td/je5oZHwzN2iJGWWVSzETAAAAAElFTkSu
    QmCC
}]

set icons(asoutput) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AXZJREFUOE+9lF9LAlEQxes77v0APUUEQQThpqIlW5mSKQUZklYUGYl/6MEgqaAH
    IYhe+wJFgZGB5OrKaea6KyF5dwNp4TBzh8Nvz16WmZwY0wNgTCQbw8CxQkcC/elr
    aPFHz2I/hxwJ1GIPWIxkPIv9amD0Hrqxj6em5Sr2aeR3Adbhj+YkrN0hmRZMEtd2
    p0eVxeceAtEDiPW6GihW7xCKH0mgQfcTTFaxYBQwox9ian4PrXaXZKH1ZUmfRn51
    QuMGka0TCWy2ukqxTxi3LglXaljbORsk5JTh1CV8G2XMhU8x7cvJpI3PDta28xCR
    KxfgchWxdEEC3z5MvNri3jnLvmkitluAIL/yk0XoApuZogQ+v5t4aZC4Oj2f7Vki
    UwL71cBgEclsRSqVLduV+lx/luTZoK9ABEtq4GyiBhE4/11+e+5U8rFfmXB4ZcgX
    6HT5rKX8ADDsUy6HPoR+Cf34R3V6nvflpPtTQq9L7v/Wl9dEo+7wGyUgTwV4niOT
    AAAAAElFTkSuQmCC
}]

set icons(parent) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAItJREFUOE/l
    1FEKgCAMBuC6l+CLFwm6TNepi3gjY+FgDLf9gU8VjBDyc/mLa611mfoQOLNeYVcp
    7ci5eQ3AIGMEeigEasxDQ9DCLNQFLWxLqcmSexp2yB9LnDArmI+Aei/hX6aJo+JE
    +Q2DeuJo3NM9oVAikLDdSfi5aORK+nwNxmZn7MDHBr2RfgjeItRKMM9EiFoAAAAA
    SUVORK5CYII=
}]

set icons(redraw) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAAAAwgAwm
    ZAq1tbXOzs7e3t7n3q3n5+fv7+////////////////////////////9FEnkFAAAA
    EHRSTlP///////8A////////////LGZlgAAAAFFJREFUeJxtzjEOgDAMA8B+wZ0y
    Z+rLEN9oB+Rnk4gkBQlPN9luR6V9SM/lPMlpTkpwAghCtcg1gsLFokV2WRJW99Db
    RrCr5lrfw1n2evZ3/QZoNUzyBudhawAAAABJRU5ErkJggg==
}]

set icons(fes) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAJFJREFUOE/F
    U8EJwCAQs6P4dsWO4CwdwUm6i1XxROy1l0KgBRGvSUwCbiklR/2qIHNRxVpaprv/
    BM8Q9rJy3a1EUOQuVgUzS5Dr0HLlvR/OR2QZan2ts/VcucJ3cpB97utppmEEy3do
    9YP8VztEiAjmFhkhvWGaYLEce6mRIthFzVeAXDZHPuZyEbKGgd7yF/ELKDsDXlOD
    lTQAAAAASUVORK5CYII=
}]

set icons(network) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAATlJREFUOE+t
    lK8OwkAMxocgmUQiwaHQyJPIEzzAHoGgkDgkj4BEIpFI5AjJgpycHA45vi4tKeN2
    /MmRNGN37S/ffe2tk2VZFPRHQAprbSUha/8832ACPVvbCwY0xlQXKEbsAJ7+cgqn
    QgUUcK4t8VlTA8VDAlHQO5QNoHCNKEhtEyh5TVueQJ9fAC6CAaE0AbAUlfoULhGt
    CqnLgGy5OeTlNrV2zO937Pe/BiJ5gsKrKk6kGGt7WkfO3AvUHilVJxSOdCGNEe/n
    rUDXSKBo09Yo7KWs0jq7rIEzHIfn8AY1S9eNoeOyysMbEBsv95jgjcEuAFhxkyLK
    x/8YzzurfLGkTkB0BcSwITfmqPwsBez7mNRAl1coFjUGORp8813DjzdFgWmUarDv
    1nwEinoNDgJU4JhmU3uuLXsAKdwmSdQegxUAAAAASUVORK5CYII=
}]

set icons(find) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AXhJREFUOE+t1D1PwkAYB3D9WMZP4KDRRRcNiYObmuhMXF1Q0MVowKiQIrUBCxIb
    BEErWGZxcMHBpbowQIw14W+fo60I1FKgyaVJL/fL83YdBzA20ofAUaCWMwhYi0zC
    vz4D0b8M6WAF1eyWzhiBuQUJU+ML+K4l2ZLz9wwdCGzHplZPoKkxfFZDLFLXYCf2
    ZWCNSoCl7wrsTFNTeRZZvbKHD3EJtN8XKOx4QIv3eRDdXmQ1M7HGU8DCaOwcQYLK
    j2UoRQVy4QE5KYugd74rMnOG/wVNjMDiXRH5zC0k8RrJ8wT2N2b/ROYImmnSuySX
    UMgVkLmSkOJFCGc8AnoDqGadt8s2wrfTCTTrPn1fAafXLZu+QVpIIRG5QCzIYXdt
    uudd7Qm2Y0CTOoeQXrdLLg7+OAruMNw/2I0RSEvR6zYH7ihii/Xssvq8yQ63kF+M
    0qfBtUvVtinvr2EDokRbkRGmvXgdsb7m0O0/sqsp5odh39aVGRYyz/8AihCzldqH
    naQAAAAASUVORK5CYII=
}]

set icons(config) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    APFJREFUOE+llLENgzAQRWGA7BJKSiRGyA5JGynQZAYmoMgEVMkGmSNVFmADR9/S
    R8dhc+BYOgFn8+77wzkfx0+G8T6dHa7HosgO90vukykDwGddOxnfpnHIp8QCRnAq
    NHtU1UxdSGnXdc4K7sYDY1DksfB6e7m1QLEJiJsQlDlufRdQQ3UBy8+FQsolKGTB
    GjQIlMmYryhclqVjUIgJDPk6DEP039wElNC+7x2C0N0K9QuAa6jsos0KdevFoCZQ
    Gq/VSigtMIHWoUCo9HXWKXiwepXzWNu2rf9IIQuSjigNRQGEP1ut7a3NE0TY30Aq
    lUV/omWviy1GnRwAAAAASUVORK5CYII=
}]

set icons(newnet) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAOdJREFUOE/V
    ksEOwiAMhjl58qF9k72KD2LMmjE3NHrwIjekhJKuwmDGi02ajAW+/v1bpf4xnBdd
    y019uen6SDmauxumm4PR8CLfARNMG3vq9ROV+9ixDprAQR1X1g+zPcMFgRjSjio0
    B7Ps1XYgeRaVWQDYE/DIFOK3z0NNYhgA6Nn5NtG7F4dFYGLwAiVwM6zV06SMWo2t
    oXe5qHrqsE3WKj1YwHyRjhXK3qEHBAx7J1IxUCcGVZwNArM7FxUlEBJigcU/SZby
    w5mUycty6rUVKvlGila9a4aL3fsNNDewZkUrFz/UvQFvZBRC0yHuzgAAAABJRU5E
    rkJggg==
}]

set icons(newrun) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAANZJREFUOE+t
    1N0KwjAMBWB9WF/SK6/6FCod7seJKHhjvdIeIRJjktaxQRiD+fW0iVuGEBazXgDn
    rB8sp316VVpcBYfT9UHVj5fUDufUtGOihTzUBTm2i90NIC7cLdQEORYPx7Rv+k9C
    L6kKatg2dncqSqulVEE6M0oGCEipIe8RlC9hO2iAhW3E+clnFeQY0vFFJ4FoAD8z
    gIC8okXVhBzjCTO4zrWiH8tn8wwlSGhpuyaIjmopJ4PW4E4CtVmrbYi6ZWt4axry
    L/j1QZDbN8em5u/lvfMCYx9U8FAnH8kAAAAASUVORK5CYII=
}]

set icons(restart) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEVAAADGxsaA
    AAD////AAAAAAACAgID///////////////////////////////////94SCxHAAAA
    EHRSTlP/AP//////////////////0XJbHgAAAD5JREFUeJyNzrERACAIQ1HYwHAs
    IKNk/6G04ECtTPNfGUFNLnICrkUWPZIKJkM9imxG05o4aE0kZWfoe+ebCy5ODkVK
    Y0tJAAAAAElFTkSuQmCC
}]

set icons(finish) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AVBJREFUOE/NlD1OAzEQRuFsW1BAR4eExAGAI+QEiIYWCSQuQEdDFcmioNsjhBtE
    W6/RM3pmiDfIBQWRRk7smedvfpzD7fbp4E8/AHft7maVb1cX+fHhPi+d/7bXwHAW
    eH11mc/PTov1ghtgSuuiDhuGodrHZtMFbYCvL88FhioUAmWdpikLTSlljJKwN45j
    vawBqm6e56wBJJDflEPlAPXhwtLgWBvTJQgFQHAEQDDfrSnrl9+67ANugDFdAk6O
    j0q6MXV8MACcY4AXFdpdnGJaqFBlLEVsGrE/FKqOA1NlVQ0g1XohqigN2TiztYZs
    0JAI4DvOrARGReyrNo5UBZouhyq0oyjjQkeJ/dgQ61dTfn/7HmY2nSsgpufsOT6+
    ItQ3ClXH4e4TA2QXHW5r6yTEmJIyIFPY92ZRHV+Ebx6lDbD34ff4Lf7b9ATu8/n/
    wE9OgMfb1uAm5AAAAABJRU5ErkJggg==
}]

set icons(findobj) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AWtJREFUOE/N0j9PwkAYBnDY/SR8A+MncNDgoC4aEgc3NXE3ri4o1cU/AaPSFKkE
    LEhsEKSKxTIamVlYGkPCUGJE08feaQ1p2uRaFpu8S+/6e597r6HQf3n6/BQSG7OQ
    EiuQD1fRqW4jcDaC6flFfPaLtBr1R4oGAkex6bUzDPUs3jspmtQTPErzYbdFJ/bx
    iw3aHD2+r4TOYw51kSYz2vt4k5ZB1pnA3G4MpMR4DJmdJTozGxu8cv6x1nMLmqqh
    oTyhJleR3FoInoxgpNQHFfXKPWTpFsXLAg42o/6T2UdtNppQagoqNzJKooTchQjO
    ugDmmZHBds8nYRpxABoEa27V8h3KuRIK/BWySQF76zNsF+DEANNCgZQ1t2shD/E0
    A+E4zQZ2DSP8FZ2HXT+YXZo1tzkIJzwbRpKNYqOoaWp/Tch7pn/NDWxFInSGbo2Y
    UOeHBPRqxASSTQSx66XXmxgb9Ors1og55bgbvwGyqrOIprDFfwAAAABJRU5ErkJg
    gg==
}]

set icons(chan_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAMFBMVEUAAACEhIT/
    //////////////////////////////////////////////////////89O65jAAAA
    EHRSTlP//wAAAAAAAAAAAAAAAAAADwvvhgAAADdJREFUeJxjUIICBjSGAhOEocDA
    yAClBRigNEgKzAcyILQSA5RWYoDSSjBaiQFKA6WYsNuFxAAAc9UMXxHyo/oAAAAA
    SUVORK5CYII=
}]

set icons(cogwheel_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AK1JREFUOE+1U8ENwjAMhNmyQyX4dgn645cHO1RVlvB2KZyls4wbaEVEJCtyfL6c
    7eRcaz11LRD0WFeyqu+5/X8EKaWVdn8t70fFVgJApRRNXJZBDX7Ok+48i2RKMI4X
    AxDY6g1j3JGnBPN8M8leAYAtnypyvr4TiDzWSOYlk4yYDQECDPqaRcT64zFfFXwi
    wPlGAZoBeb6EIwTWRDSSY9wroTnGOLIIOvSQfv0TT168dPIInVHIAAAAAElFTkSu
    QmCC
}]

set icons(compound_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AHtJREFUOE9j/P//PwNFAGQAJZhBTk7uPyUYbMCdO3fIwiC91DUAl1dwuRDDBSCB
    5Wvfo2CYF9ENBxlKsgEww5ENRQkDdBcsXH4RJYZIMgCkGWYAzLnYxLC6AKYQ3QDk
    cMAZBthiguhYgCkkNnHhTEgkG0BRXqAkJ4L0AgAN7XGRNyO/AAAAAABJRU5ErkJg
    gg==
}]

set icons(placeholder_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAMFBMVEUAAAAAhP/c
    3Nz////////////////////////////////////////////////////nj/q/AAAA
    EHRSTlP///8AAAAAAAAAAAAAAAAAMIMH1wAAACtJREFUeJxjMIYCBkyGAYMSCDIz
    GCiBATODEYShjGDApUhTo8AEgsqYlgIAaT0SzHIyPsUAAAAASUVORK5CYII=
}]

set icons(simple_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAJ5JREFUOE+t
    k0EKgzAQRfUiObvGpNGqeJaSjVDcCIJ00yP8mkBES6KSMTDL9+bPMEkBJKRnBJQi
    wTY9pfsqYIwhtmyCWNhwO4Fqv9hW2X0g6tlW0Y6Q9QTZjBDNsCb2Co5A8RyQq4Dg
    CsirHvzx9ifwRXUdHcgrjUxqv2A7YwjkSi8jvAIJluWcgQYOCsxy/qO6jg48FMTc
    wz2HRPkPP4jQTVslZ+LsAAAAAElFTkSuQmCC
}]

set icons(message_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAMRJREFUOE+1
    ku0GhEAUhndvKpEkEpFIJJJIN9Bd7E11Xe/Ps73TlD7NZmycH6Oe9zlzOu9xHF9W
    DwNsygpW3dvYbwPQdcNUgrYVNI3wfCc6dYC+JzDDdS2oKkFRCPJcrkJ2AfC8YbUS
    LMsVRpoK3x9D9gFs92BFlgmSZK4oOnWxD1isU7sKpFWDCENBEBgC9F1XaxwrK0H4
    Pq9gCOAMLqwE4brmGXBAyri1EnQcVca/sHwwGT/KqkGef96Dp5v5n1V+0sUXTs0o
    fqimM9gAAAAASUVORK5CYII=
}]

set icons(queue_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AIZJREFUOE9j/PfvHwNFAGQAIdxpb/8fGSOrZ0CXRFeISx5mCE4DQAqOrVwJt/ne
    rVv/QRhmIEgO7H18zocpBmmEqUM2BMQGGzB7tu9/EEZnYzMApAZZfNQAaCDiigmi
    YgFfQiGUDsDRSG5KhKUNgvkAOd6RvUSSASBDYEkZRsPzAqGcSEgeAEvthurzoY+N
    AAAAAElFTkSuQmCC
}]

set icons(container_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAMFBMVEUAAACEhACE
    hITGxsb///////////////////////////////////////////////9GEEOiAAAA
    EHRSTlP/////AAAAAAAAAAAAAAAADW2LcQAAACFJREFUeJxjcIECBiwMR0EgEAEx
    jIEAwjBghjAok8JpKQCFmhqioMIOzgAAAABJRU5ErkJggg==
}]

set icons(stat_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AElJREFUOE9j/PfvHwNFAGQAJZgizWDXU2I7UQZsdnH5D8K4LCLoArIMQNZEtAG4
    NBEyDO6FkW6ApaXlf1IxLF0QTAeEUurAGwAACvmYamLLnngAAAAASUVORK5CYII=
}]

set icons(outvect_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAMFBMVEXAAAAAgAAA
    AP/a0tL//////0D///////////////////////////////////////8Dfx5lAAAA
    EHRSTlP/////AP8AAAAAAAAAAAAAF1YY2wAAAEtJREFUeJx1jbsJwDAMRF/hLCKc
    PYRQemNy+68S27hIkVz14H7kFl8g6Z5wDVCywQsZZhLDMnVrJYlT6qxwA7NKOocU
    FWfV34O/pw8hWyAp4RketQAAAABJRU5ErkJggg==
}]

set icons(gate_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AD5JREFUOE9j/P//PwNFAGQAJZgizWDXU2I7bQxwcHD4jw+juxjDCyDNr17lYcUg
    uVED6BUGFEUjqSlz4JMyAEpstxX6D6D/AAAAAElFTkSuQmCC
}]

set icons(param_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAMFBMVEUAAAAAgAAA
    AIAAgIDAwMCAgIAA/wAAAP/AwMD///8AAAD////AwMCcnJyAgIBTxsZ2xO1jAAAA
    EHRSTlP///////////8A/wD/////lXM/KAAAADhJREFUeJxjmAkFDNgZP6GMKV+g
    jPnxUMbVqzfBDP9Y33hPIGP+1ysuV/8jiyDUIHTBzYGbjGopALFITScD1ANBAAAA
    AElFTkSuQmCC
}]

set icons(tree) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEVAAADGxsaA
    AAD////AAAAAAACAgIAAgAD////////////////////////////////GxcxdAAAA
    EHRSTlP/AP//////////////////0XJbHgAAAEBJREFUeJxjEIQDBkHBRCKYogGh
    gUBmWlqioKixaSiQmZiYKChgbGwAFk1LgzJBoqLGxqYwtQGhoVQ3DMnpMAAAQhIf
    b/Voq10AAAAASUVORK5CYII=
}]

set icons(unknown) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAMFBMVEUAAAD/AACA
    AACAgID///+A////gP8AgIAAwAD//8CA/4D//8CAgP8AAP+AgIDAwMB6idRUAAAA
    EHRSTlP///////////////////8A4CNdGQAAAKZJREFUeJxtkkEOxCAIRVnMvoEL
    mMwFvMIs3Pf+txgS9xSoFjQlaWJev/+jAu0HH/8aQNMFnLLU/w3gCg6mkkBXIBsQ
    rsKo9QASQZykq6mBarBGrK35AaogA5QUVhMcE+B3pgzBDtB3BBgC7yMsuUSKCwg3
    UDgAuQXlPsyo3ilcNkDpEh2ol/Y1Fad7jZOM0+qPkZJAPMPby2VFXxp7B/cg2ESA
    T8QFuTKHjk1mSQUAAAAASUVORK5CYII=
}]

set icons(1pixtransp) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAABlBMVEUAAAD///+l
    2Z/dAAAAAnRSTlMA/1uRIrUAAAAKSURBVHicY2AAAAACAAFIr6RxAAAAAElFTkSu
    QmCC
}]

set icons(16pixtransp) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUAAAD///+l
    2Z/dAAAAAnRSTlMA/1uRIrUAAAAMSURBVHicY2AgDQAAADAAARaJmtEAAAAASUVO
    RK5CYII=
}]

set icons(modtype) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AYJJREFUOE+tlM1Lw0AQxfVfEwRRUBQPIooe9NaLePEgqKeCRWyh9ashKhJaiiVQ
    aYNBsa1aUEsRingQPQT0IIJHKQTGfQu7xDQfUDPwWHYz/PJmJpv+DcvqizQAjFKR
    wni1wp277Ffrlio3cVL1eaY5LuxxHtgiL2C1ucMBOSNGZ7U1Kexxjue+UDcQybv5
    SSpdrVO9tUcPbU3KbGyTkC/UCfz4fKa0NkbXLYVEPL1UONAZAor8LqdOIHqklWN0
    ai7T5V2KMzqdH74XUAHLG0vcbSAQA8gWpkgpznIJoPX+KPeAKIVpLuQHAlFuQh2i
    zeygBJRrcbJtm7AiBAwr8kMdZliS0yHKhUOUjkArANtSh8MdopyMNkHJo1HpEEBI
    AO/bOdaWGZ7nOWnnUL6+31jJA1Q0V/5MFcBqc1+eAYi80CmjHygpdTJCx6VF0i9W
    uwRYWhvnpXt+3F43RUAP9QVyCy/zheENQXfZYN/lARsABoX1vJHo7S7/6//o57Bn
    aNTAX9fnY38wi/BuAAAAAElFTkSuQmCC
}]

set icons(channel) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAAADGxsaA
    gID////////////////////////////////////////////////////WYDUgAAAA
    EHRSTlP/AP//////////////////0XJbHgAAAClJREFUeJxjEIQDBlKYAkpQwMgg
    wAAFjAyCMCZOExAKkLQhGUamcxBMAJaCC0urkZPoAAAAAElFTkSuQmCC
}]

set icons(props) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAAADGxsb/
    ///////////////////////////////////////////////////////TdTWlAAAA
    EHRSTlP/AP//////////////////0XJbHgAAAClJREFUeJxjEIQDBhxMAQYwADOV
    QEABzFQACSpgE1XCKkqZWoQbCLgXAJGwDaRRYr5VAAAAAElFTkSuQmCC
}]

set icons(cut) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAADAFBMVEXY2+a+w82d
    p7m2vswXMl15h51NYHtii7Nzlbiuxd1hi7MrbaNHfatIfasRXpsSX5wSX5v///8A
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACoo4XSAAAB
    AHRSTlP//////////////////////wD/////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////AU6eVwAAAGVJREFUeJxdztsSgCAIRVGEOEl2
    4/9/Ni81pjw5y3EL+TTUjxxGIMgIQacnWkA6ENhFUSDGWJJgqFCGzdxW1wVfdHe3
    QxVMbzSZWRJu9/WX6z5zHtOm0tIdWvoHNf2Hmh5Wr+k8D2R2DfxrIR1XAAAAAElF
    TkSuQmCC
}]

set icons(copy) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAADAFBMVEXz9fv4+fxj
    eqfu8vry9fv5+vz4+ftedqNmfqhqgqxthK1xiLFzibJ8krh+k7qMoMPw9PuBl7yE
    mr+JnsGRpcfe6Pjd5/ff6Pfk7Pnn7vnt8vrz9vvc5/ff6fje6Pfh6vjq8Pn2+Pvm
    7vnw9fvy9vv1+Pv3+fuampCYmJGdnI2amZChnoqqpISmoYeinoqem43EtHPBsnW9
    r3e0qn21qn6wp4Gqo4WmoIfHtXHEs3PCsnTBsXW+r3e+r3i5rHq6rXuwpoGro4Tg
    yI/UsmjUsmnavXzVsmn///8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADvbg3HAAAB
    AHRSTlP/////////////////////////////////////////////////////////
    /////////////////////////////////////wD/////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////WUsdygAAAKxJREFUeJxdz9cWwVAQheEJohPl
    II0T0UsiiE508/5vZI4VZfnn7lv7ZgD/Aly/+4Asyz8GuOlKcYHUbS1g22FFj7Ar
    SfeHRzCLGe0pYTrRvNyvO8BjiykHQgMMag/o63o0ICzlsqlIIQBcWEyZE+qvfMCx
    rWknK1xYC0BHZcqSUGRrZ0CXc75Sw4XqAA7qrDzi71zAoWlWBeYzyVqjMgHsUwLF
    Vc0evF7sf3sCzoUm2mm9lbwAAAAASUVORK5CYII=
}]

set icons(paste) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAADAFBMVEX29/rz9fqH
    lK6HlK3y9fv4+ftedqNthK1fc5Zgc5ZxgqCHla7f6Pji6vjv8/ru8vmBl7yAlLSB
    lLSRpceCkaqHla2Xp8CYp8COm7CNmKqvusze6Pjm7fjz9vuMmKquusze6Pfh6vji
    6/jq8Pnf6ffi6/fl7fjz9vqSm6be6feSnKby9vqrwdT1+Pqan6GZoKGhpJyoqJev
    rZK7tIq2sI6wrJLgyI/avXzyxnHxxnHyyXnxyHnyzIPyzYPy0I7y0Y701Znz1Zr0
    2aX03bD14br15MLxxXHyyHnzzIPz0I701Jnz1Jr12KX02KX13bD24br248L25ML2
    5sjYrmzMqHXQrHjUsHvOrHnFmmHDmmTOqXbHonLKpXTTrnrBm2zEnm++mGutgVKv
    hFaxiVyzjWO8lmq1kGfk1sbUwa////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADVhWziAAAB
    AHRSTlP/////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    //////////////////8A////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////SWKbrAAAAMJJREFUeJxjyEQDDBBKQkdHAllA
    RF5eSl4EJpAeEcElLiYmzpUYkQ4WCAviFBISFBIS4ggKhwrAQQhYIDYwwDXQGAwi
    wQKhLi7+LsasQGBuAhaIcvZz9jPRFWZjMAOKAAVifHydnExlWbTV1RmNQALRjt4O
    XoZ8wgLsbPyGIIF4eztPTwNlMDAACcTZ2Hp46MuAVKjpgQQSrK3crbQUVXmVFHk1
    QAKpwW4WlnLSKjyamgqSIIGMtJTkJCZuUWZmIMoEAFeMQ0vtgg8RAAAAAElFTkSu
    QmCC
}]

set icons(down_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAAUAAAATBAMAAACqztpQAAAAMFBMVEUAAAD/////
    //////////////////////////////////////////////////////87TQQwAAAA
    EHRSTlP/AAAAAAAAAAAAAAAAAAAAE1gGDAAAABhJREFUeJxjEBQUYMCFQUAACAUZ
    catBwgB/EQNjxeU9+wAAAABJRU5ErkJggg==
}]

set icons(node_xs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAAYAAAAHCAYAAAArkDztAAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    ADVJREFUGFdj/P37NwNWkJ196D82zAATzMxc9R8ZgyXQBUF8rBLp6RP/MyCrBgnA
    MAMyB5kNAHL8XDUQQ11rAAAAAElFTkSuQmCC
}]

set icons(modnames) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAADAFBMVEUAAAAlJSU8
    PDxRUVFjY2N0dHSAgICFhYWUlJSjo6Otra2xsbG0tLS/v7/BwcHMzMzZ2dne3t4A
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7h23zAAAB
    AHRSTlMA//////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAWHyGPAAAAG9JREFUeJyFzksOgDAIBFAppbVa
    S73/YbGiqDF+ZsHiZSahk4d0bxjmuViG8I3lActw5sB8WjbM4ZL89ZIGbsisuF6p
    XBV7olYDxHY9RtyalUHnjivYnHw0ZGcIozZ5dZh2TM6TFyRMIpND/PvzFxduXvEg
    WbY14gAAAABJRU5ErkJggg==
}]

set icons(zoomin) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAADAFBMVEVCazlKczlK
    c0pSQilSazlSe0pahFpjWkpje5RjjGNrc3NrhKVrlGNzc2tzc3Nze4xzhIRzjJxz
    jK17c3N7hJR7jIx7nGuEa1qEc1qEnKWEpXuEpbWMc1qMlJSMnJyMnK2MpYSMrb2U
    c2OUe2OUe2uUnJyUpZyUpa2Utb2Utcace2OcjHuclIyclJSctb2cvc6ljHOllHul
    raWltbWlvcalxs6lxtalztatpZStxtatxt6tzt6t1t61nIS1pYy1tca1vb21vca1
    xs611ue13ue9tbW9xs69zta9zt69zue91t7GpYzGvaXGztbG1u/O1t7O5/fO7/fW
    1s7W3t7W5/fexq3e7+/e9/fnxqXn5+fv7+/v7/fv9//v///3////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    //////////////////////////////////////////////////////+MBfgOAAAB
    AHRSTlP/////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////AP//////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////8q7QIgAAALZJREFUeJxjiMMCGHAKhmhKK+o5
    RaII2strWJmZmhhHIgl6SJpY87BJOXvIRyEEpRW9AjmBggFObghBbjMeTh4eRjGx
    MFUkQStWVqAwC0uILEKQw5qHk5OHQUEhHEmloImlMycTT2yMgwNC0Jff04+HiTM2
    issf2Z387gEhMW58wrquSD7ylxUQFTAKshBX0cbwu49BqJYKRoBoe4cqKWGEkrZh
    qJYMRtDpWNgxY4YnL7sEjkAGACd4cD2Fo8KaAAAAAElFTkSuQmCC
}]

set icons(zoomout) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAADAFBMVEVSQilSazlS
    e0pjWkpje5Rrc3NrhKVrlGNzc2tzc3Nze4xzhIRzjJxzjK1zlHt7c3N7hJR7jIyE
    a1qEc1qEnKWEpbWEtYSMc1qMlJSMnJyMnK2MrYyMrb2Uc2OUe2OUe2uUnJyUpZyU
    pa2Utb2Utcace2OcjHuclIyclJSctb2cvc6cxtaljHOllHulraWltbWlvcalxs6l
    xtalztatpZStxtatxt6tzt6t1t61nIS1pYy1tca1vb21vca1xs611ue13ue9tbW9
    xs69zta9zt69zue91t695+/GpYzGvaXGztbG1u/G5/fO1t7O5/fO5//O7/fW1s7W
    3t7W5/fW7//W9//W///exq3e7+/e9/fnxqXn5+fn9//v7+/v7/fv9//v///3////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    //////////////////////////////////////////////////////8c2/2kAAAB
    AHRSTlP/////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////AP//////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////NF1uiQAAALFJREFUeJxjSMQCGHAKBquIymja
    RaMIWkspmxkZGuhHIwm6iBiYO1ho27tIxSIERWXcAkId3O397JwQgmxG7Ox8IBCh
    gCRoxsTECAIREghBFnMxaWkxIIhBEuQxMLL3CQiJibaxQQh6cbl6+/jHxEezBiG7
    k8vFLzjGiZNfwxHJR74S3ILceoEmQvJqGH731AlXlccIEF2PcFlZjFBS0w2XE8cI
    OnUTKwbM8ORgFsYRyADbo3SgHWkVkQAAAABJRU5ErkJggg==
}]

