#=================================================================
#  icons.tcl - part of
#
#                     OMNeT++/OMNEST
#            Discrete System Simulation in C++
#
#=================================================================

#----------------------------------------------------------------#
#  Copyright (C) 1992-2014 Opensim Ltd.
#
#  This file is distributed WITHOUT ANY WARRANTY. See the file
#  `license' for details on this and other legal matters.
#----------------------------------------------------------------#

set icons(logo128m) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAABHNCSVQICAgIfAhk
    iAAAAAlwSFlzAABYXgAAWF4BikzXIQAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3Nj
    YXBlLm9yZ5vuPBoAABQYSURBVHic7Z13eFRFv8e/c7ZkN1uyCWFDQhooRVEsXGwJ
    RbCgggpKUQE7FtRHuer72u4TH/V6fbyAYHk1CoIFEbiASEd9IgRRkBaMlARI79ns
    brKbLeecuX/womFLdvfs2ZJwPv9lZs7Mjz1fzsz85jczgISEhITEeQqJtQESvum4
    ekCaW87nEQZDQZEJQAUQNwAzCF8OigNJ6VWHyGpw4bQjCSCOaM4bolMynQ9QSmYD
    GIHA78cE0NUgpNCwq/KAkDYlAcQBdMQIhUXdPA8g/wCQLKgSgs0Mz8zT7z59PLTH
    JGJK+6jsizlKvgVwiQjVuUDxStLuyvkEoME8IAkghljycm6lBKsAaMStmaxO0sln
    kS3lzoAlxW1YIljaRuXeSShdBUARoSa2JrVp7yClpa7uCjERalyiGyz5uVcTSr9B
    5F4+AEywprQXBiokfQGiTNvYXANh6SEAOdFojwIPJxdXLvWXL30Bog1L30SUXj4A
    EGChbVROur98SQBRxDI6cxABHo9ys3oXxSv+MkXrAh5b9PEgG0vHcRRJYtXZk1HK
    mNLlzz22qWuaOT/7Y4A8FgNzHDKiyNbtKm/2zJCHW/OsRYWzSmrM7315qDaFp0FN
    Pc8Lxg8ybgLwlwDo2FyVhaXTY2SOiodrBoD3PTPC6gLu+p+PPlhfUv3F8War9PI9
    SE5IWN/1bytHxwMwxMgcUEom+0oXLIBZiwpnbS+rn+vmpBfvSYKcgV7NruyaRoGx
    MTLnLNfSWy5M8EwULIA/atsWSi/fNwZ1gvujuXM7zkmk9NIYmXMWlcnqutAzUZAA
    Hv2gcPDx5o4+4dvUO0lUyHx430jUpn7+UBAM8EwTJACbgx0r9fn+SVQwds80Auhj
    YUtXKIiXDYIE4OZJSvjm9F6oj8k1Hw9eV+ptg+QIigCdLj7RM40A1ljY0hWOUC8b
    JAFEALubU3qn0oqoG+JpAcUpzzRJABHA3OlUPPnhh9pzEgk5EiNzzuJI0SvLPRMl
    AUQAJ8vD2imf0TWNAEUxMucse3wFiEgCiBBml+uOrn/rZeRHAOYYmQNC6Dpf6WGv
    BQTLw1cNxBBjzGdCUcPYUJ2xscvfpKjCYc7P/jZWi0EMlCt9ZURNABf00WJEf2EB
    rz0NhnXjws+/uLL0tblXD3vjw9/OphOGn0952SMAZNG0hxJ85mslEJC6gIhg2FME
    hcUEbWvDm13Tk3bWlFHg4yibY1UC/+0vUxKAyDCsG31/3goA0JYfG3f8lcf7n1NA
    Tl4FUBkteyjwnGZXZb2/fEkAIpP8axHkljYAgMzewahNzd+ck19UYSYg0wE4Im0L
    IXR5d/GAgCQAUWGcDqT+uPGcNO2xklFVr865qWtaUnHFbxS4FwAbMWMI3a436eYE
    KiYJQERSi7ZA3tF+ThrjdkH1x+H1rQX3nTMFSi6uXMeATgZgi4Apa5K0ytsD7QkA
    JAGIhtxqRp+d233mKVsa1PYa8y+e6friqo0cpVcToFQkM1wgeDGpuHJaMLuCAEkA
    omHctg6My/9vrjv2x7CqJybv9Ezvs7uqVN+mvRKUvIzwHEVbGY5cZthV+W6w+wIB
    SQCikNBQA8O+3QHL6Y8cGFX15JQiWlBwzu9OSktdht0Vb/MqWS4F/hPAoSCbNgNY
    Snj+KkNx5S36PRXHQrU9ao6gXgulSF//NQjlgyquL9k/pm6grfJ4wZwrhhQUtnTN
    S/nhlAXAAgALmvOyMhSQjSKEH0rBZAAwEMJ3gjJmgJ4AJQf0iorfSVF4A0lJAGGS
    vG8XNCdD2pIPzaljmcq25trTz9//woD/Xb7YV5m+u6vrAHwrho3dIXUBYSC3tSNt
    02pBzyraWpXJv/28qObhW4+deu2JUSKbFjTSFyAM0jZ+C5k9jFkcpdAeLx1Cy47t
    rHlgQoXbmL7Qntjx8bCC1QGnb1155L1PhzMyuavw6QelMUC00Jw8DsP+PaLURXgO
    2vKjuSg/ukiv0Sxc+e4bO1ewfWq0CUyRRsnsMhvrKlZPK3ABwKSCTxKTk8h1dpbL
    s3a6xtdZOi9bcbhSP/HizJcBvB1q25IABMC4HMhYswwQOTKalyvQMHEGU9N38Njt
    W48AwMyzeYZHCqib48iOimpR25QEIID0dV9B2dIoap1uQzKqZz+FzqwBQGWLV76D
    ZSMSVSwJIER0pQdh+N3LqRcW9oFDUD3rSbBanaj1BoMkgBCQd7Sf+fSLSNs1Y1F/
    532gsqjGiPyFJIBgoRQZq5Z4LfYIhZcrUHf3bFhG5IlSn1AkAQRJSvEP0B0tEaUu
    V5++qLr/aTjTM0WpLxwkAQRBYkUZ+m1eJUpd9gGDUT17bkz6e19IAgiAwmpG5pf/
    AmHDOpMZQOz7e19IAugGhmORtex9KKzhhfPzMjnq75oF88iYeXz9IgmgG/qt/Qrq
    6tNh1cHqDaiePRf2nAtEskpcJAH4IWVPEZL3esVvhISjfw6qHngGbkP87oeQBOAD
    Tfkx9NvwdVh1mEfmo/6u2eBl8f0Tx7d1MSChoQZZyz8QPOijjAxNEyaj5fpbRbYs
    MkgC6IKirQW5ny6AzOF1wktQsLok1Nz3OGwXDBHZssghCeDfyGwdyPlsIeQCR/z2
    AYNQPfMJsPqYHQUoCEkAAIjbhexl7yOhye8Oqm6Jx/l9sJz3AiCUR9aKQiRWlIX8
    LJ+gQu20B2EdPjIClkWH81sAPEXG6qXQ/RH6hVvOfpmonj0Xzr5pETAsepy3AiCU
    R8bqpYLW9s1XXou6u2aDKr1OXu1xnJcCIJRH/28/R9L+0F4+L5Oj8bapMI26MUKW
    RZ/zTgCE8shYuQRJB0IL6HQbklEzay7s2QMjZFlsOK8EcOblfwbDgV9Deq79ouGo
    nfEouESRb3eLA84bARCOQ+bXn0B/5Pegn6EyGZomTEHLmAkAif1Jr5HgvBAAw7HI
    /PJf0JUeDPoZV2oaau6dcyZKtxfT6wUgc9iRtez9kPbvWYePRN3U+8GpvI787XX0
    agHILW3IWfoeVHXBbabgE1SonzwT5hHXRdiy+KHXCiChoQa5n70HucUUVPnOrAGo
    uXcOXKk927ETKr1SAJqyP5H9xQdgHIEP4qKMDK1jbkbTTZNB5T3Plx8uvU4Aht93
    I2PNMhAu8Hq+KyUVtdMfgX3g4IjZw1IOJzoacNRaj5pOE2rtbWh12+Dk3LBzZzYB
    a+QqqBg5jCod+qtSwDmVkKkd4DpVEbPrLL1HAJSi744NMO74LnBZQtB29Rg0TJoG
    Xin+j+ziWewznUZRyzEcsdTAxXd/iIeNdcAGoNXVgaPWMyuS2kEA5WRg23VwtRnA
    dmhDOPkneHqFABjWjfQ1y2EIwrXL6g2onf4QOgZfIrodFncnvq8/iG2NR2BjQ9ri
    7xMi46AwmKEwmMG7FXA2p8JtSgblxTvXo8cLQGFuQ9YXHwQVvWsdPhJ1U2aB02gD
    lg0FB+fG6tp92Fx/GM4A/9uFwijcUGfUQ2VsgrMpDc7WFFG+CD1aANoTpchc8Qlk
    to5uy7FaHRrumAnL5eKv2//edhqFp35Gi0ucPYOBIHIOqow6KJJN6KzpD65THVZ9
    PVMAlCK1aAuMW9YGPJ3LOnwk6qfMBKsRdysWR3msqP4V62sPgEaicw6ATO2AdtAp
    OOqNcLb0FVxPjxMA43Sg/6ql0Jd079N3J6ei7u7ZEenr292dePPYRpR1NIhed2hQ
    qNIbIVM7wCNN0LvsUQJQV59G5orC7k/nYAhMeTegccLkiIzwm53teP3P71DnaBO9
    bqEoDBbsw54HUhbfssj0zJaQrqfrGQKgFCnFP6Df5lXdxut3Zuai4c77IrYNy+Sy
    4bXStWhyxvwKQC8csA9UcgmbMhdMvalm3urOYJ+LewHI2y3ov3IJtCf+8FuGS9Sg
    6YbbYcq7AWAis2xrY1146+j3Ib98o0oPDZOA6k4TWBr+DuPuoBT5brhXoWDsZBQU
    BTUdiWsB6P44gP5rlvkf5TME5iuuReOk6aIP8rpCQbH45A6ctvu8dscnapkSz154
    I0amnIkganPZ8FnFTuxp9bq6T2wmpiUlv9kI/DOYwnEpAJndhvQNK5G03/8BzLZB
    F6Nh4nQ4MrIibs+62v3YZ/K6dLNbZufk/fXyASBZqcELg2/B1oYj+LxyF9x8BL8G
    lL6YtmDynsZ56wK6ReNOALo/DyFj7Zd/XbviidOYjqab74xaLH6FvQXfVP8WuKAH
    1/bxPQ6Z0O9SDNWnY/6JrajtjNhAkgC0MPvt23ZWvbSp20biRgDydivSNq3y685l
    k5LRdMMkmK8eDUqic8QxBcWS0zvBBXkSeFcSZf5DxnMTUzF/+Ax8VfULNtYfDsfE
    7jA6EhRvApjbXaHYC4BSJB34BekbVvo8d5dL1KB1zAS05N8IqvRxJ3ME2dVShlJr
    raBnAw1FlYwcD+WOxkCNEYWniuDg3YLaCWDD48b3bv+k6dkNfk+3iqkAEprqkb7+
    a2jK/vTK4xNUMF03Di3jbo1JaBYFxdqa4ANIvZ8PjrF9h2KwLg3zj28LaZAZJAzh
    mVcATPdXICYCYBydMG5bj5RffgLxGAzxShVMeePQcv0t4NSxC8P+zXQKVZ2tgp9n
    QogizlAl453hU/FF5W5sqi8R27V8d8Z7tw+pe3aDz6DI6AqAUhj270Ha5lWQt587
    n+bUGpjyxsGUf0NEp3TBsr3Rv98hEsiJDA/ljsYl+kx8cPIHdLBB3fkUDAzLk4cB
    vOizXbFaCYSqvgoD130IdU3FOemsTg/TNdfDNPrGuInCNblsKDGHeSo3JYEHAj64
    KmUgFmjvwcIT23C0Xdh2dU8IIfdh1dSXMG2119wzagIwblkLte3vAZXTmI6WsRNg
    ueK6uIvF+6W1HHy4n2FCIUgBAFKVOrw+bApWVO3Bd3UHw+8SKDL61bD5DcDPnlnR
    7QIIQcegYWgdfRM6Bg+L2902JZbwz+QP918mJwxm5+ThckM2FpXvQJsrzPslKR2P
    WArAduFFKL/hcTj79Q9cOIbwoDjaLmzqFwmGJ2VhwfB7sLhsBw5ahN85TQnGA/gv
    z/SoXRrVOvrmuH/5ANDgMIsTzxf2N+BvkhRqvHrxJDycOxpy4U6wK+BxXyEg3Rrm
    Ra09ftb5u0JAcFv6ZXjrkrtgTNAHfsAbdbq2xGvhRBKAB7WO8M4FjjSDtP3w7qXT
    8B/JuSE/yzG81/l1IQmgOW+IzpKf8+TdO1c9F3LrPYQONvBuolijU6jx0tCJmNBv
    eEjPEYI+nmlBDQKt1+YO5WV4AHDMoYDVpEkuB2AMqfUeQicXvk9ezP6/uzYezMlH
    ccvxUJxGXh42v1+A9usuMFpGZT9tzs/Zw8voelDKUQbjDcWVuT+NuPF7oYbHO4F2
    8cQTCkaGbHVq8A/w8PK0nfMFaLgpTaO2qe7kCe7h4O5LeWYrlbFzUnbWHAnf3J6B
    kgl/ZkxIdMLEKWho+xEYeJ2BK6e3XJhgtbrHg2A8tVMNGFos5xQP6X452SSmsT0F
    tUwRaxOC5ufm46HGKHqpRW7tcM2hDNmdtKvyeRKR7Yc9C61chFByGtkxAAXFxvpD
    +LIytGPuKIXX8qY8aVfV+6JZ1gvIUIV/2DOJoIvbxrrw0akfBQWXMgQnPNOi5go+
    2doBuSz+3Q5md3wtTHWlrKMR88u2oskhZF8CdTT0V3otckRNAEv2hhZVGzso9Jcw
    IEzocYBnEfv/PwXF5voSLK8sBisgPvEM5GBMl4N7DgSsTQOFLjq7fQNhZTuxqGwH
    DpqFLwT9mx99JUoC8AHbrg1PACJ9AkqttVhYtg2mcJeCARDK/+QrXRKAD9wWPdTp
    9eJ/y4OEB8Wq6r1YU7sXvDjzsvqGrASfV6BJAvABdSvA2rSQa7s/eMJ/BcKVY3bb
    sah8Ow6HG5LWBQKs8NX/A5IA/OJqTREuAIEctlRjcfl2tLmEXVrlB54QssRfprBD
    BRhFi3B7egZuix6cQwWZKvTVwVDdACzl8XXVHmwQI/7PAwqytv65dUf95QsSgFbF
    72QIAU97t+PQ2ZyKxKyaiLbR6uzAgrKtokUAe8BTQt/qroAgz8ynT805MdSoE75r
    oofgNhvA2UIPVQ92OXiv6RSeK1kRqZcPEPJp83PrD3VXRLBr7pJ0/bMKJv49e2FB
    AXtdBkKdDvCU7/ZTzlIOn53eiXeObxZzA4gnLQoqfzlQIcF+z8NbN5bcce+01NOt
    9qt6c1dA2TO9pFwb/FycB8U1KRfAoPT+etQ7zHjj6AbsbYuoZ5RSgpn189YGvCAh
    LMf3nzs2b5lx/z0nKcWYVrsrsbfKgLNpIE+0g0kIPlq4prMNeamDzoniLW4pw9vH
    NqLJGVkvIwEWNM5bvzjIsuLwzKLPB5lZ1zg35ZPEqjOecMCp+p359XEXHOnBPpOh
    SsLYvhdDLVNgv7kCh8xVkTTxLJsbreY7gj0jKD635sQpfRZM7C+HfDeAnFjb4oe9
    fIJifPPc1UE7MHr5KE5cWudtrAXHXU/gva4ee+ivciW5NZSXD0gCCJnGF74/zTP8
    aADCT48QGQL8n9qafH3tU+tCnppLAhBA07MbGnVyZz5AgxpoRRCWULzeYL18WkXB
    MkEbGqQxQJgYF06eQigWAzTKGx9JCRh+TuOz34V+hFkX4jf+qYdg23bsqHrc4E9l
    MqIEMAKRX2AzgeLlxnbzI7Z/bgt7yVD6AohI6ju3Z8gUsucB+igAcW+lABoJpQtZ
    ln7U8o8NojkSJAFEgL4fTtUSl3syoZgJYAwAoffMt4NgM3jyVaO27zY8Vij6WXKS
    ACJMxieTEtl2eR7D8PmUkItAMRgE2aDQ4+8u2AXAAooKEBwHSCkl+LnJ0rYvWIeO
    RA8kc8FU9bCCqdE9/VJCQkJCQuIM/w+s+lMDkY/11gAAAABJRU5ErkJggg==
}]

set icons(logo128w) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAIAAAACACAYAAADDPmHLAAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAJcEhZcwAADsMAAA7DAcdvqGQAAAAZdEVYdFNvZnR3
    YXJlAFBhaW50Lk5FVCB2My41LjOg6VnVAAAdyklEQVR4Xu2dB3BV55mGnWx2Z7Oz
    GSfjycZ2aHYSJ561sTHucYztdbDjYMcGF9hgEAYEQiCJXiQhmmlCHVXUUO+9t6ve
    ey8giWqBAWMcO3bszbvf9597rq4aukXVHGbeue3cwnmfr/z/+c/RXXcp/5Q9oOwB
    ZQ8oe2CK7YHGUPcFV5e/ZHfj7Xmqm395HH9/4X7848mf4tt5PxH3P3/zUfStff3W
    zUWP2HW62C6YYj9f+TmG7oHuAxvsri174db//fe/AQ/dpbM+WzwffesX2Rn6vcr7
    JnkPdNuuXfDZO/Nu6WP6cNt+8dpD6NlvtmWS/zvK1+uzB87tMlF9N/c/dI720SD5
    5+/+BZRFVPr8BmXbSdoDNxY/qRrNUENfv0kZpTbptNIfTJK3o37teJovQ/P5W3Oh
    QDCqFRO/Qd+a18ct8gdnjC9fmqWUg4m3eORv7LVZY8d12tDUbsj7zm9eqkAwFSCo
    zol94qsFMyfUfAbmu7k/RvexzUo/MNkQ9K1/M8mQCB6L99xa+JuxzwLueWkLDqcl
    2Ckaug+Gg+2bZ+6Z8OiX4eGyM2azhnOdHe0etD+Ou2xsFA2zD35oawMODm0IeKZu
    LCLZmM+4uuIV47IA/6cecXJQTB8F/N862mNwBqCdb/RMnzHm83u/fHnOkN+lV1lU
    zNct481zcRwSad88PXnpXxucVr9jhjWDnPaVlK8bAHNOHB9wYKYmwX+LsdE7Vu+/
    aPGuYQeNfut4Qkn9OvY8bwX6DtjJ3XtNJ73+ywB99cL9hgGgRL9u0c/7ySQiaMBO
    vrripSkDAIGgPwA8zFMA0B2Aoxm0v7T+0by/AsCdBJCSAXSsld9XKL53PYBSAnRP
    /wz1924UoACgHwBTex7AQf95AAUA/QD43s0EKgDoB8CP9u6dmscCTAw8FmAoACcy
    ExFSmHnHKT7UE+dNXh0y3p7M6WA+Gth9bLv+6Z+Hs4YCwOYX1hTeceoz/TOuL3th
    yIGXabseQAFAd4gr0yPA0SYijtb7a08IiRVBL07SiqBBv0Wvo4AKALoDwNEvz7sP
    twpnMtYEXjR2TaACgG4AyNGvvQrnstmiIXX3yqpXJ2xV8Fcv3GfcIhClB9DNfO51
    Pl35ypAlX58vemTYRRi3Xn9o3CEYs/MClAwwOgS1sb4jrvfrM100bBSO58khn737
    1NidFKIAMDoAn73zxIgAcEPItX+4xuv89uUqfc8GHm1xyI33njU+7Wv/WAWA2wPQ
    7Hd81NW+vDb/xttPDjsOP7952QKO2NGMHe11PjuYTzHXq8PXZWMFgJEBKKpSQdeT
    PfgCD7de/fWIkzGcJXj+QN8zh27+5TFc/Wjh2Bsvw6EAMDIA3fvN9IpccZbOAfOk
    2wUeL9y8SYtI6BzCW3w1EL4qiBz9Xz/3C3CkX1nzOv628CG7xlC38b8egALA8ACU
    58TRaVeGndt/8625qmlz5q4CwPAAfLriZb2if3AN//sL902PS7soAAwFQJfGb7Sm
    TX6dUzpfFIqninXpySZ8GwWAgQAUl2bh6+f+y6joHw6Of8z/KT5/42FV4Zbldh+n
    JY165I7P1Ho3yN/ucToR5WeHDhp31s/tqFIAGAgAnVwx5ubLQHBZ8PSUzru85+ND
    eNTZEa/6eAzQ465OuO/o4aHnaYxXalAA6AegIdRt3My/8f6zKC1IgX1GgmEn4SgA
    jD5jZ8z6hJKi9HFJ/Rz953avQlGlSqydUACYootIeOyta2On63Y8L9DqdWjAohkF
    gCkIQJvHgTE3n+t9dVLQkBVTCgBTDIDKtAiDJ3xGygQ898/1friSpAAwhQAoKs/B
    FwsfGtPov0SjCLneKwBMIbOHM+Oy+TtjZr64To/jrlEXySoZYIpA0eFiM2bm85Lw
    hnCPUc1XRgFTxPya+IAxq/tcQsqz43QyXwFgCgBQlpc4ZuN9HjqWlOp3foRSAiYR
    Al7g8flbjxmd+rne9+w11TnqtfsPBYBJBGAsJnt45U9ToINB5islYBLNpyVZRkf+
    3159EJVp4QabrwAwSQCMRcfPC0T0rffKPMAkGa694zld67sQU3uGz5h6rwAwyQDU
    09jc0HV9DAEv4mgMcjYq5Q+GQGkCJwiKqpRQ8ff4dD1yN3i7L/70O1RkRo+p+UoP
    MIHmG3P59k/M3kIxHScwZn3BSO9VMsA4Q8DLuQ01n4/fdzhbj4vxMhAKAOMIAM/y
    ffnybIPS/lcvzgBPEY9H1CsTQeNourxzjTH/6qpXx2SIpws8SgYYBxh4UYchkc9n
    7nbZbx/3qFcywDiYLu9U7vYNqfkTlfKVYeAUNN+Qo3i6pHddtlFKwBgBwZM8fGBG
    n3H+RHT5o0GgADAGAPC5e/rO8PHCDWMP5Ixmri6vKwAYCUC7m53ec/sXtv7vbRdq
    6mLcWG2jAGAEALwIQ5+Uzyd5jvVcvrEgKAAYAACv5OHpWX3M58O3pUVpEzrE0wUO
    BQA9AeDTtfW5yBI3huM9nauL0cqxAD2NHm6H6TvBc5Mu5zYeR/CMMVyZBzAQhMZg
    F50P5/KM3tmDG6dculcWhBhoftexrTp3+rfocq08GziWUTqen6X0ALeBgs/V61vX
    f0Xu2zV9ctTf7jy88TTS0M9WABgBAK7dup6oaWzUF1QXILciHxllqgnXoeQ4/GCP
    rd6aY+Zx92DNMnW7e4aJ/U/uXbLzX+/9i9UPDLqIyFS4REyLzxGdpnV5KvfMYUuj
    J3WyyvLglZCInX5R2OobM6H6wCUYd285qrfIfOvBmrXOzXrGqhOW971vM+++93b/
    +7QDgMf3FzZ/oNP4/vqy349Jh6+qKsC+oGg8v9MHvzb3wK82eNCt54TpQfrO2Wbu
    WjqJ2etH15z17l9rZEb3zTy+nk3Pkb6cudYl55cmx1+9/8PDP9IbgsnKADzEu0UL
    L0eb3OHZvMGXWTG0/vL7gjIz8OeDgXjIwgtzdwVj/t5wPGkXMSl62iYEL+/wwp+2
    ueENPbRw20k8vycA823D8MiO03hgg+f12aZuzrPWut4zLQDodNw96sEcXo9/fseH
    Y75SZ19wLJ7a7oOnbcPxUUgpdqc0wjatidSss2xo2wFKbaLH+qoR++LKERyWgNzQ
    UKhCw3RSHm2bHBwKh+g87EisxTL/QszdEfjNnHWuxTNXO/5qSgPAl03R5RKsPPM3
    XkO75cf88JsNJ/HK0XjYZbQgufUTZHVeRbZafF+jjqvIHEEZ9LxQu6T09itI7xio
    NHosRK/JSqX7qW19SKXvTa3uQnVODnoSY3AuIRq98VE4ExWKtrDTkkIDxW17eBB6
    4iLRy9uQ2pJikF1cg9Cac9gYV4tn9ob/c/Zapy9mrDw6f8oCwIdwR1u5w6t0eDtj
    Uvxo7118wBsPrHfFH48n4kBmKwHQh0wyRVZGG5ko1CeUJou2SyOlslokpZCS1Upq
    +QRCzf1KpPushCbWZcST4liNlxDXcAnx5e2ozMxGDxnfGxuJ7uhwNPp5o5wuHlkT
    Foya4EBUBwWiwsMVXeHB6ImNEGohCFLzqxBQ0QOLuDo8vy8Cc9Y6YsbKI89MOQD4
    +nujje15/p5n8iZiTL/koDceJABePZYI29QWhFRfRETtJYSzaiSF1VwUCqXXWLwN
    K7iKdUEoqPICTqsVSLesALX8Ky7Aj1V+XuhU+TmcKpPkU9YLb1ZpD/xym1CQnIqu
    iCB0hZ5GJ0V8g/dJVJHx7ZVV6KpvQHN2NioJgLbTfmIbVn1kKELTSmCf1wHz6Fo8
    ty9cADBzqgHAzdvtrrvLkzl8rH4ij9ppAKAMYE0ABFVfQBiZH8qGk2SzQ+j5YFIQ
    m006TQqUpWW4fwWZrJYv3fqS4axTauN9hOnnyPBeeKnlSeZ7lPTAJ6cReTHxaD11
    Ei0ezmhxd0ajmwNKnR1Qn5uLnq4elFMGqHE8juaTTuL1Fg8XVAf4ICipEMdyO7Ah
    hgGQMsCUAYBPzrhdrecGr8/0jTEZ1o2W8ge/LgPwP5QB9hAAbGwoRb0wXw1AMEf7
    IPMFANpRTvf9SWy+MF5tvmT8efhQ1AuR+bLxfOtZ0ivMdy/uhndWPbKo+as7dhC1
    B/ei5oANSveT/H3RUFKO5soaVKemofj4EVTus6bXbVFD25W6noBvbC4OZbVhA2cA
    GsVMCQB4XM8TNbdbq3dt+Yvj1uDpAoMGgKOJNAJoJlPP96d4jnp1xMtRz2le23hO
    85oUrzZeNp1TvSbi1aleMr1HyL24B25F3XAuOAuH/C44p9UgxT8QlXY7Ub5jM4q3
    WiDXegeKA/xR6OONXPujKAkORt6JY8jfugml2y1pOyvkHz0I57B07EhpwrqoGgKA
    SsCaSc4AdVHeNK5/eMRxPRs/EWfejAaBDMArRxOwK7mJGqlzw0a7HPGy+RztA9K9
    SPVU19WSjRfpnsz3Uqd5VzLcMf8MjuV14lBOB/ZndcAmow27U1thG1uBGB9/lFtv
    QymZX7TZHHmWG5DNIGzZBBU9ztlqiWyrjcin50voOd4u78h+2IekwSqxEWsjq/Hs
    ZALAZ+RcWfPalDdeBoMB4FEAA7CTAPAnADTRzrWeMgJnhQBZ2jWezGbTNcarmzpu
    7ERzR9HuQVHuXHgWx1VdwnC7rHZYp7dStLZgS3ILNic1w4pkmdiMbTFV8PUNRf7H
    tiimLMAq2rsDhSS+HXxfvL5vF5IcHXAwLAcWCQ1YHVHFw8CJzwBheSniQknDrc7l
    Gn9l9WtTIuKH6wE0ACQ1wo9MlLp5LePJ9AASw+FHhsvypW1ZAzp6Su0eVM+dKcqP
    53XhIEW4LRm+kwzfSkaz4bJk49l8y8QmWMXXY18YHZfwi4QfgaCLfH3D4BCYhO3R
    FdgU34jV4QQATWpNeAloeumBIVHPXf2lTUvAf2d3tFQ8Wa9rMsCRBOygCDpFqdqf
    I7mkG57FZzXyKDoL96IzcC88g5PaKjgDN7VcyfQTuZTaM9tgQw3ldjJ1c0IjrIZT
    PBveCEu1LOjWIo7VAItYVj02sWIGaiM9J0u8rnncQM9TBgitxDM2kwBA69M/1wDA
    V8rstV4NLgeTZayu3ysD8PLheGxPqIcXRa9DTisOxFdif2yJpBhZxXS/GPu0FU2P
    1bKNKsLOsAJsDs6HVZAKm1nBKlgNJ3rNKkjaTpYl3bcMyiPxrQoWdH9EnabX1NoY
    VgLzqFpsIABWhUwiAPwHkToddo3bxRR0NVWf7WQAXjoch23xdXBUdcA6vAAHAxLg
    EpEGt8h0nFTLLVJ63C9+PIz4fTrIlbaRlDpQ4fR4WKXQ8ylwkRWWAseQJOzxTYB5
    aBHMYupgElKOp23CJr4EJITodm1cfcyZiG21AdhK8+hHs6gbP52KhPQ8dJzpQfe5
    i/qr9yLO9l64vXou4IzQ+UE6h67uoeo8ew6dZ3v7daYX7TQxVNfUhlMRSbAKzIJZ
    dA1MgssmB4CQQv0ukToR5uryHRoAPo7FlphqHMlopvUBacgtrkDfp9dx7bObuHZj
    ZH1Kr316/TNJ1z7DVaEbuKKlgY+v4wp97mDxdwld1dY16fGV6/jkyjWhy1c+xeU+
    SZc+uSogC03IwhYCYH1UFVYGleApm9CJzwDTHYAFBIAVAXA4owl2BEBmQRl6L/bh
    /OWrOCfr0hWck0WvnSPxNr0XP9Go58Jl9Jy/hO6RdO4SzrK0X6fH3fLzA245k9C2
    lFG6KFt0nj2PdsoCbRT5rZ3daO44i/qWDgTG0BwAAbCWhoDLTxsJwPG4MDv+M2b6
    aroD8CIBYBldjY/TCQAqAemqEjLqsjC53+g+9JDZPRdYbPTlAUYLY6lksGGsM1qS
    nxvpVmzboxZFdQel/HZK862dPWgho5vbz6Kp/Qwa20itXWgg1ZH5VQ2t8ItKhmVA
    JgFQaTgA7W62W26++aiq5fcz9DafYZnWAKxzxR8OxcKCUuihtEbsDUxBeh4BQNHX
    S2bLEqaTullq8zWmk/EawzX1Xa7zo992dp8Xprd19aKFTB9gOJsu1CXMlwDolACo
    b5EA8M/AmrAK/DWgGE9Z61gC+M+X3lj8hN3nix4VQzi+EGKx+ZI7E4CDMdgUWYkD
    KfXYG5CCtLxiYahsuna03850TtVd1NgNlfQ8N33ya7LprZTSOZ2LCFcbLG41xg8F
    oJEA4PRfVd8M38gkWPilYzWNAJb5F+FJ65Db9wBnjm6x42jngzQ8Zuc/YXp+l4n4
    m/STtSZQl4ZtPLYRTSBnAALALKwc1gm1sPZLQmpekai72rVcTu+DI11jOkUxm9pJ
    XfxgddHzsrij76Ba3tJ5Fo3tXahXRzPfcmRrIOCIHywNIARAcz8AG33TsYpGAEt9
    C/HknmEAaPY/seXaXxckffnKHLqA0hxcX/qcqvvQRmG69r87FYDf74/GioASrKMo
    2uGTiNScQmGmMF1d16U6LaVzYbraVI3ZwtihkoZwkjqornNNb2jpRG1zu0aczutb
    OwQAGghGAaCBAaijDBCRCHOfNKw4XYr3fQoxnwCYPfhoIC+j/tvCh+waQ922KH87
    uP+vjsoZ4HkCYCmlz5WBJdjmnYAUAoDNHNDUaY3dOY2z8R2sEYyXn9c2vp6Mr2ls
    QzWN32vUYhBkAAZkgeEA0O4DGIDaJviGJ2CDGoD3fArwxO5hANB1bdidmQFc8Pz+
    KCz1K8SqwGJs94pHSlaBiFZNLdeOdnUK5y6dxcMybfEEDUt+Tor4DlRTx15JTVtl
    fSuqG1sFCKza5jbUEQRc0zkzsKQeQFIT9QKy+htB2k5kgCacIgDMvVOwkoaA7/nk
    KwDo0ytIGYAA2EcA+BbAJLAI27zikJyZL0zkNC+neK7bQmIWTm08jcfbSDwub6Wa
    3iakfo6M52atho2nVF1R2yxuGQIevlVzJmAAKBP0A9CBRjUATYPMlyBQg8GlgptA
    GQAvAoDgfc9bRQAEUwlwmNglYTsSIsUfQp5uetnGTQDwHANwKh8mAYXY5hmLpEyV
    MFVjuIh2rchmw8lgWS0dZ6i2n6HHktgonqatJNPLaxrVaiIImgQEVQ0tIiNwJugH
    oF2YKgAQ5qujn0YHzWrJEAgQaNtKAsAnLB4bPJOxMqAI73rl4gk6wWXCAdB34miq
    bH/P+gMSAHZR+MA7HyupDGz1iEViRp5o1oaYro50Nl6YLozp6lcbR2Y7qml4VlZd
    j9IqVgPdJwhIFQSDAICywEAA2qgEDA+AbL72rQCAsoAMgJlHEv32IizxUADQax5D
    BuDZvZH4wFOFlTSM2uIeQweDckUESuldjnQpytn0FjZdE6UcqZ1CHPUVtY0oqaxF
    cUWNuC2prBMQlFezCADKAjx+r1ZngdqmVioBAwGQo182Xc4wfNufDTpFCfAJjcN6
    dwKAfvti91zMUzKA7lPZmgywN4IAyMMq6gM2EwDxqTkUYR2alC7teG3TuVHjdN2v
    WkrnpVV1KCyrFioqr5YgqKgVz5eJTNAgAGEApDLQQiVAAoAzRwN/JkU2AzDYfC4t
    GhA489A21fUSAGbuiTBhANxyMG9nkFICdC0x/RlABiAfm09GIy41W5grm95M0S0M
    57G66NbJLI5aFg/nGpqF2So6iphfUilUWFalhqBaZAIuB2UkqQz0ZwFtAPjzmwgA
    /l6Rabin4AykaS6l+62dEpAMgLfIAImUAQrwjls25u1QANC5DGgAoHV073vkUBTR
    Kh63KMSmZAlz5dTOpgjT1ZKMp8glVdU1CrPzisoIgHIJAjUIMgQlBEcplQIGoLym
    QSoDohdoHpAB9AGAy1BNAwMQi3Un4wmAfLzjmkUAnFYygD4ZYA41gc/QqdXvumdj
    5SlakkUAxCRnglO6lOIl49l0TtUcsfxaTSON6Smds8m5BaXIIeUWlkKlBoEhKCit
    RBG9XkzlQIaAe4HRAODol0cUg4eX0lBTakK52fQKIQDcCIBTKrzlkonHFQD06wEY
    gKcJgCXuOWInWrpGIjopg6KrRUrx6miXTCdx7aYdL8wvrRLGZ6mKkZ1fTPdLkEcQ
    yNkgv6RCUwokAGpFH8Dv5QZOZAD6TP4OhkzOADIA2vMK/RNM/fMMMgCmBMAK+u1v
    OmfiMWMA4BnDH9rqvgN1jbSpuh2XgH4AKAP40mJL1whEJaYLgzjFs0G1FO3CeGE+
    jeVrG4T52WR8Zl4hqYggKEJOfokQQ8CZIJ9KQgH1A0XUFMpZQO4DRgSA+g2p9p+R
    Jpa6uqXhqCx5ppFeq+EMQNc4WOsWRwDkYZFzhvEA/NbxhM41dKoaq+vv0gBACymX
    nMyCyalcWLpEIDI+TUQpm84NHu9oNp7rfUVNPZlZhYzcAmTkqEX3GQSGgKHIVWcC
    AYE6C/B7SiqqqQ+oo89QZwH6XM4q8ihAZAACQKR/YT7NRZDhPPuoPRPJ6xV5iFpL
    v88rOEYAwOVrkXM6ARBoeA/AGeBFLw+DVgXputOn0nYCAFMqAdYEgFsmTLxzYeEc
    joi4FGrW6qU0zemaxFHP5nMq53SfmpmHtCwV0rJVSCcxDAIC0gAIRBao0PQCXAY0
    ANDncy/B8wcNdDygiQDgEQcDwNHfTtHPZvOCUO3FovyYwdAA4ByLld4EgGMaHttu
    JAAMwc8Pf6yaSkaN12/RALCHAKAGaqVXDjY5hSE8NllEKpteSdHKhpXzzB6Zx+md
    zU/OyEUKKTVLDQLBwFkhk5RFJSGHIJFLQQE1hEVllSJzlNJZvuXqLMCAcZbhUsMA
    aGeAfgCk1cBdPbRaWBYfhSQwuDR5BVEGcCIAaBr4zw4MQIBxGYABcM9LW3Df0cPf
    ewhkAJ7aE4rFBMAKzxxsJADCYpJQSpFeQaaz8WxYGRlXQNHM0Z6cnq1WjgSBOhuk
    Z+cLADJzORMUiVKgKiqVeoFSKQvw55ZVSVmASwoDwH0GzyvwqIOHnFIGoNrP6Z+X
    g5Ph2kvIORtwWeDs4UkArHGKwQoC4I0TaZg7FgDIh48X+nrZzXdzxo/37fte9gUy
    AE/uDsU71EGvoLn0DSdCERgeK6KXU3cBnZvPxqvocUZuPpLSspCYmqkW3U/LpucY
    CG0YpKyQkSMBIZUFOSswFGXiMwvp8zkrcIPImaGMMgzDxllHlB4ChHsP7kM43cvi
    x9WUPXiY6UznB37kSAB45uJP9gTAtjHIALquH5ju281ceTiaewAG4G2nDIqiPJjY
    R8LGyQ+OPsFwPhUCZ74lOXoH4YRnIOw9AnB8BNl70Ou0zQnP0/3yOg0HjYLgQJ/D
    n81yYtF3OJ0KFXJm0YmhLkJhcPFjhcPVfxjRaw5eQdhq74cPHRMEAK/bpyoA6AOl
    DMB8WkXztlM6PqKZwJXuGVjpEIWPHMKxmrTWMRymjhFY5xiJ9U4k5yiYsVyiYO4a
    hY2u0djoFo1NJAuaRrYUihGyouMKfGxBW1budA4C6yQtRadtLEib3GLEZ4jPIm2g
    z+bP5+9Z7xyJdSRT+u61ThH0eyKwhn7XRyfCYUL60JHqv0eWaAJfs0/Bo0oG0B2B
    GSsOR842dfknL6N6yymNAMjDGr98AcIaPxVM/fNhFlgI89OFsAguhlVoCbaGl2J7
    RBl2RZVjD52WbRtbCbu4KuyPr8LBxBocSq7FYdKRlDoco1XGx9MacIKVLul4aj2O
    pdbhKL1+OLkOh+j6fgfoffsSqrGXPseGPm83fe5O+nz+Hv4+/t5NIcUwDyqEWUAB
    TEmr6feZ0NBvFYl/74fUAyw8niwAmLXa4bsZK448rfueuEO3nLHquPXsdW59j9LQ
    6Y90naB3XDPwrlsG3j+ZiaXuWVjmkY2/emZjuVc2Vvjkih3OkKymHb6W4DANyMf6
    wAKCpEBAspEM2hRcBAsyy5LExm0mbaEzeGXxYyv167zNpqAiel+ReD9/Dn8eg7eW
    DGaT2WAT+u4V3jlksvR7lpH4971Hv/NdGr4upt/NAPNZzg9v9vt21lrnthmr7B++
    Q23V/b9Nl1P9w+x1J0t+vcn7u8d2BWE+TQhNVz1BJ4TMpWngB829btH/KYCuHv4L
    3ffEHbrljFWOP5u52ukAXWn7/Gwzj3/MMff89gFzr2mpORs8v6X/wzezTF1r6f+0
    YsZHjj++Q23V77/9yw8/fmCGybENs9a6+NHVtkPoytvTUrPWnQyZucbJ55crji69
    /8NDv7h/+SHD/maAfrtv+m9975IdP7xv6d676eLKMwmAOQTAtBSl/DlU92fc+97u
    /7x38bYfTn9nlP+BsgeUPTA2e+D/ASKhl34ml36lAAAAAElFTkSuQmCC
}]

set icons(defaulticon) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAACgAAAAoCAYAAACM/rhtAAAABGdBTUEAALGPC/xh
    BQAAAAFzUkdCAK7OHOkAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAAAZiS0dEAAAAAAAA+UO7fwAAAAlwSFlzAAAOxAAADsQBlSsO
    GwAAAmpJREFUWMPNmbGr2kAcxz85fbq8QR4ZHB0K9h9wESl0cRaHrh1c80+UDh10
    Ezo6K+4uHTKXLoKz8BAXzYNQRAgYcl08G436YryoAbnjLp4fvr/f93fHCf+fZ+A7
    4ADyTh8HaAMFBWVs2xLwC/hgmqbfarVEuVwWUkoApJSofhAEu7HwXPidOHPhdaSU
    zOdzBoPBZrFYPAGvwGfg1dgq9wf4aFkW7XabXC4XWTwIgsjYubm476t+EAT4vk+n
    06HX67GFrGSAb0DDsiy63S5CiLvAKWWr1Srr9ZrxeFwAhAE4pmkWZrNZNp/Px/6x
    a8cP4Q6VrNfrm+Vy+VcAZqvVEo8CJ6XEMAyazeYTYAoAZYhHgFNtsVgEQBxz273h
    lMMBsqpzCzNcAqlMIx4RLuzq7LEQ6w5pErh3AdPKt6sV1BHquHDnoPcAdebhe3CX
    KLqnoI7SkiTPEudg2nBxYE8W6keAO5qDSeqeLrhjsLFdnBbcOSW1mUQ3XFi9q02S
    Vqv6J3MwrhnShjup4L3gDneZCGDckJ5znq42ch5Mmm9phXnPxdfCpQUdyyQ699fE
    R/5TBtG5K2hRUKcK2hVMA+7aaJwNcRr7a5JSI47VwUeAiyh4q/31UgVTyUEdcHuA
    0+k0kFKKNOEuhXUcZ5eDb8PhMPA8b7eQ7k3/Ujjf97FtewO8ZYAXz/M+rVYrarVa
    6mGOE/5+v89kMskAPzPAb+DLZDJ5cV2XSqWCEOJmh4JD5fr9PqPRSF0Bf41cohcK
    Bb/RaIhSqRS5Mwwnr6r2qj317qnvH445joNt2xvXdfcu0Qk9z8APHuNvCFNB/QNd
    ZWqtV/QFlwAAAABJRU5ErkJggg==
}]

set icons(imagetoobig) [image create photo -data {
    R0lGODlhmQF6ALMAAO/v7/f39///////////////////////////////////////
    /////////////////yH5BAEAAAIALAAAAACZAXoAAAT+UMhJq7046827/2AojmRp
    nmiqrmzrvnAsz3Rt33iu73zv/8CgcEgsGo/IpHLJbDqf0Kh0Sq1ar9isdsvter/g
    sHhMLpvP6LR6zW673/C4fE6v2+/4vH7P7/v/gIGCg4SFhoeIiYqLjI2Oj5CRkpOU
    lZaXmJmam5ydnp+goaKjpKWmp6ipqqusra6vsLGys7S1tre4ubq7vL2+v8DBwmkA
    xcUUxsYBFQHJxxfNycsbAdHK0xXO2sYa297Q1gDVHNXS2B3OH+HiGN7mGeXvFu7p
    r/US29na7fvw9OzI/j3jJxAAM3rnKKxzljDDPQ75LhQEqPBfwomwHkacsLGitob+
    EhZuO4fRYcmQAhuKZIgumQeRICdSFLCSJceCGV3etEmz4wSY0GRiOynxZE2ePQuC
    1MetA9B5Mn8K3fkvZ1N8yophixauqFadTLVu5fmQRFmqM9cFVObxqkm33bLCxQpX
    LV2xUqWhzaVRrkG6XQ9y09t2JsdqJMGWOJtUq4Vw0yA/Jvx2oIaulPcW/it5HuK1
    lmv1PXZ18Fy9gfM69oDzA+POYSNnprpU8wbUiu9aRMmWtcBYow2ytSYgt2TYxXPf
    /u1aefK5uqN7DQ0VumDHyJ/vlu67qlXLLrkmXWYcbObg91p3p679b/VnjNsvt16Y
    dlh3id26Q/vtu3vtjT3+Rx5clKUmH3+lMbfef7bdx52DcdFnH2+hKdjgfrr1Z49i
    Ovl112bejNVbe+Y5F8Jrs90l24ig1fZgUCmBxllZsGF44C3BUdgUh0ZRZmN8IKDI
    oo4rrlaYizcSZOE9yNWoIZD+gaYjQDyq1944qg0E5YJKpoXeOXZFyJ6M9MhopoxY
    TtmgaFW6ZxNYR/EUZ3pWzjfmnEY2tp2YGOJp5ENh6qkgUazkyF2J0AE60VB18unP
    nlmG2JJ3jNFJYGZ+MmphoW2qpumMQxIJIlIkagiRiVOSGqmqXX6TnahJvhjnRY2q
    Ymhjn8J6nWE0rZMmmabaySA48lwGGZL3uZqintP+nPVqPNdMV+Yw1FZr7bXYZqvt
    ttx26+234IYr7rjklmvuueimq+667Lbr7rvwxivvvPSOgFBMtUIrDr73JhvslC7q
    +yuCPr03LTPHkpOwtIYtdKqEpebzKrMZPomqGUr569NRtMZIcD/+YsCxxiC3GuzI
    MEoaMrAPj/lxOhN3dtKWZBBK1Jz5eRxxyanyOifJW96s86ofrYxgy8MC3aFzlnoX
    qxpRvQwnUTK52ehToyJFqME2Zpp10QiKSHPQrWXn5KAXl6Goj2lfGemnDIZJM23K
    2RTo3Oq06aXeYAYnHm8Gdiks0hC+KO0bNLIN8av75hx300mnLNyQc+M9qWX+zxKW
    +YjSJChO22RDHCt6hLtxFuQaBs4nQlJTh1tdHw3ceuSOHjldkbxql6vnAA6+ekew
    IWel5WCcjujBli8KLM/HzVZTQ7XWfqbBhh9qGjvEgZ52nZArDV7bYxjvOfLgVwz2
    7LtO+PVM0QtO/eFPW3+MeOJpD3Gdqc02fPlhiK8l2qJrHcN8UiATIWYk6FvPUuJT
    DwYeL0BssZ/LzJe44ehvSfwrXt2ORzsdSWRg9QhU9XaFH2rILYPvqc3ENLcsxf3F
    Q72TnvsI578OjvAMFfxT2szmQvdkZ2wlgdb74ueUZWVJJSwM1dlAtbQJ3vCJR0oR
    EAMohrVxToIU8dX+hXIzReZoUU1QFJkR0bQZMkZKSoJqluhC58TlJa2LNqwZ1dTj
    p+kJyo0hnIrXKAilqAmqhERDIFXQosY2qmdrWMMjB//VP+5ZCWd2dBsfm8iePGJw
    U95zCyRJKMhByi+Oh7xaJxU5PhvJEVI7y+Eon4Y6ZYWKYn+8ICZJCTtATsaWnsRV
    Livzo1oVbJKlZKQGQ8QvpylkYYU7IjDnt6zgCUx2W6Mle56psGKFxVO7NBnIovlF
    rlnMmPUKpzjHSc5ymvOc6EynOtfJzna6853wjKc850nPetrznvjMpz73yc9++vOf
    AA2oQAdK0IIa9KAITahCF8rQhjr0oRCNqEQLJ0rRilr0omCIAAAAOw==
}]

set icons(arrowhead) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AKlJREFUOE9j/P//PwNVAchAamK4YZS6EuaoYWBgQOGx/yC8+8QdvLFHtJddUzb9
    B2HLqLVgjMtgog2EudCr5dp/EMZlMFYD/Rtv/gfhgMbb/4Na7qFgrx6ggUAcVA3B
    MINhqQOrgZpBPf9BWCu4779F1Gow9uy8DDaYLAOxpcXYngf/QRjmsiCgt0EYPSxJ
    DkOqRQoslqmWbIjNkkR7edRAnCGAEYbUKmQBP7/KXHRAXrYAAAAASUVORK5CYII=
}]

set icons(apply) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAjAAAbgDs
    JRPvPy7qRjbcVknYZFjlWErnaVzteGrlhXnqpJnkw7vs1Mzp4tzx8OqVHN65AAAA
    EHRSTlP///////////////////8A4CNdGQAAAENJREFUeJx1zsENACAIQ9E6AhO4
    /3Y4ASJgE2Lk9PJ7AcbDS8xLHaweiycWT0xG7FTk7gQyRsWlSe5BIZfwnTW/T3Zu
    ZHqi/OzMrT4AAAAASUVORK5CYII=
}]

set icons(revert) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEWVIx3zGQbs
    JRPvPy7qRjbcVknYZFjlWErnaVzteGrlhXnqpJnkw7vs1Mzp4tzx8OrYRYc3AAAA
    EHRSTlP///////////////////8A4CNdGQAAADtJREFUeJxj+A8HDDiZ/HDmBxD3
    A5TJ//8DP0QBUJgBpo2BgR/G/MDwH1MUSS3ChA9Qa2AyH/A5By8TAIMapzuvxOjH
    AAAAAElFTkSuQmCC
}]

set icons(loadned) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAPVJREFUOE9j
    YBg2wNzc/D8MU+wpkEHIhsD46OIYFh3uNvuPjPG5hKBr1+ao/EcHIDFshhL0/uFW
    s/8/XswA4w83Jvx/caHj/4MDFf9vbCj4D5JDxwTDcE+r0f8fH05gxd8/HEERB6kl
    bGA90MAXG4jC8+IVCBu4BWTggwUoeG2R/n9iMFbXri3S/v8DGHYwDDLoxwNgmOLB
    oHAGqcNq4FJgbP640QHGYMOgbBiNHKv42HDD58XL/v9xoQJi2IUGDGxrbfm/sfMi
    XoySyPuDJKGGVYANRscgxSQZCHLqvDT1/7gwWQYSymYku5DuBhIT0wRzEDkKAMKT
    9qk9WAOKAAAAAElFTkSuQmCC
}]

set icons(save) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABMAAAATCAYAAAByUDbMAAAAAXNSR0IArs4c6QAA
    AAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAALEwAACxMBAJqcGAAAAAd0SU1FB9gF
    FQo0GDhP8kgAAAHKSURBVDjLzZMxaBRBFIa/t7FUg5UIamNIIagIksLirNJbJ4q9
    raIQEMXCwvZAyCGIEgIiaG/KEJSIRRQskouQIleJoMcFbndmfovdnb1lN9YZWHiz
    879/3nv/P3BUl5XB65VVfd/ejgd/hn+5ODPTSPjR7zN94mTcX5qd5c6tBauB7j16
    ouHoQMPRgbrLPQWfHvp1l3sRe//xU5Ucx8pAJHgvMNjbHzB2ql2miTb29gcRqwlY
    JAsBXFCeBYzSOlVOVnXjQg70vo2MhNQJK9hGaWgMV1T/MhdiXpNM4JwvCyN1WezN
    yNsxY+I8xLwGmfcwdtXNPzfe/NcGWSaE8KGNTAlpJkB05hdYW1s9lKgzv8jYecDw
    oaVNBUidBxnnTp9i8fZdEI3Bl8qmTkgBtVUmIM1CHPWXT+tsbu00qrp2+QJz128U
    VwjXNrPMQeZUKGZsbu3Qe/6AyjqO3/33LL3c5epch1KK1pnJVwqZ5cBXH3cr5PBr
    5TEfUOnYNp95pnBetRd7/uyZCEx/TU94LBfKDBxT7T7zof6Erti7GD/77Fm6eZwP
    1HGTAkSZur0VbXwboJC/OTMrwILECuMqqmWJ5XvB2xcPjSO9/gGxzhY7P6fbbAAA
    AABJRU5ErkJggg==
}]

set icons(undo) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAAAAAAITG
    xsYAAP////////////////////////////////////////////////9MSdVzAAAA
    EHRSTlP//wD/////////////////8qlaxQAAAC5JREFUeJxjUIIDBkqYgoIQppCS
    IIgAMQUVgUKKEKYQgimIxBSCqQUDIQrdAAYA5lYYQC6lU50AAAAASUVORK5CYII=
}]

set icons(redo) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAAAAAAITG
    xsYAAP////////////////////////////////////////////////9MSdVzAAAA
    EHRSTlP//wD/////////////////8qlaxQAAACxJREFUeJxjUIIDBvKZgoIwpiKQ
    AyKATCGgiJAgnKmIYAoKwtQqIpiUugEKAPDvGF5qge68AAAAAElFTkSuQmCC
}]

set icons(step) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAB4AAAATCAYAAACHrr18AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAPRJREFUSEvF
    lTEOgzAMRduLcJlIDEhcgBUkepUu7Q1g7NilB0A9Q4feJpUjuTIhTuxkCJKlAOY/
    fzvA2RhzqnIAuEYUQT/ramloDGSBAfbq+13cus5CvJfFSgpQg5/D4ACpSBWgAoPY
    dZqSUIl7Mfi7bfYxzzvopW0tBtcBru1iMMyUigPwPo7/eUI3QnDIQzhdi8G+KBWh
    rrg8uF4M5qBYANf2LLDkFYk5Zx03TWMxQEB77heWmrebMUBCjuh1Pyd2T9Vq6haL
    8MVjHaE7l75m/hrzDruacxJzrJ2/+yOG5il1nANkHZeIaZ4Vf0A0opLcauAfgkdf
    hZmm2ZoAAAAASUVORK5CYII=
}]

set icons(run) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAB4AAAATCAYAAACHrr18AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAKFJREFUSEvF
    1GEKgCAMBeC6iMfxh9A9Ok2n6SReyJhgmChsbw8KBhnMb850zzlvvzwCI3EfR5FA
    cuti0URBr5RqIHNQYASnwVacCltwOqzF6fAZo+pno8JalHacpL0W1AW3s4ugLxxC
    KC3ahDIe32ffrCttc9Y91iJ9cX0OfHNZVzx2xwVr2jrrDIJ+9ni1tyuM0mq0ak8e
    fIF4UMo5Rgt4AE/n/qSTRl1eAAAAAElFTkSuQmCC
}]

set icons(express) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAB4AAAATCAYAAACHrr18AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAMVJREFUSEvl
    ldENgzAMRMsiGYcPJPboNEzDJFmIypGMLHMOvgLqR5EsQk7csx0Lhlrr6yeXgFGs
    87xJPKVDqMAEukxTiyixK3oKjOA2sW/0NNibezCrU2BrjsCMToPVPAJndRr8Hsc2
    bBE4q1NgNY3AjJ4GW1MEZvUQHH047tpv4FLKJqFrf/c6etaErOa9bdI72L4YJdDb
    t5r3Ql06VOwNzipAugVpJz08XfFZR3owBE+dMTK1M4HWvfNtv+K7ppT1+T/wB2p3
    yKTh4IZyAAAAAElFTkSuQmCC
}]

set icons(fast) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAB4AAAATCAYAAACHrr18AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAMpJREFUSEvF
    1P0JgzAUBPB2kYzjH4J7dJpO00mykOUFItfrvabqgULA5uP9ckZ7r7XeLrkC3tte
    y7JGy9aNxlvYvWjMj8LPeW5NrR+NW2CFI5xt7nRilZxhhdtgLK5gxq1wL57BiFvh
    xzS1ly2D+7jt5YokWFTBOG6DuSjDPH4YHn37CCt0g0spa2+9KP+Ofp6n1uEZZ+gH
    zCnURlTSmMf9Af5CvxJj2uyeIQWPjiJNjI9QFcY+O8yJs/M8Bf/zaNxzDv1zOTZx
    GfwGFiLriBzs6Q0AAAAASUVORK5CYII=
}]

set icons(until) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAB4AAAATCAYAAACHrr18AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAALNJREFUSEvl
    lNEJgDAMRHWRLlPoR8E9nMYZOoSTdKHKFSJFNE1KxA+FQGiPvCY5nHPO0ycfwL3Y
    l6UgejrNfReKYoBuMdbQFOe0arAVfAg8AvfeF4rqK8no2lHTyLVwU3AL7+Wm4DWE
    klKqATCXm4EBlayJNCZgLRTwIbCmM6m2uto5d46N8qcznF81rdYEzD2ifbA5mIrf
    df86+GkVJmBpZ5wfuN3D0dfdi36ZUsNodP8DH2Ua6fH4zikVAAAAAElFTkSuQmCC
}]

set icons(mrun) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABgAAAATCAYAAACKsM07AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAJNJREFUSEtj
    vHTpEgNNAcgCWmKaGg4OHVq6niQL+ry8/sMwKY7C6QN0Awnx0S3NcHP7j9cHhAzE
    5yOgXCJWC5CDgFCQYFML8wVIDq8FIAXEhjMWn66itQXgxEAwDoj1AbI6ZN+gWIAs
    QU5SBOoBBwvVLQClFmyOwwgicnwACgJCmKScTE6cjFpAVElMlCJywx+kDwDiQgVV
    /+qK2gAAAABJRU5ErkJggg==
}]

set icons(mfast) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABgAAAATCAYAAACKsM07AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAKNJREFUSEvt
    ksEJwCAMRdvlPDhJp+nVXRzDhWwjBmJQEy25tRCoGPL+//FMKR2mHwAsy3R4ScdS
    /RLg9j5jjURdzmV+N3TAB0rnd7i3BkQKwP/GAY1AioTeg3o441DqpguAZu3ycTgD
    hKkDDaCqjMxJEUZhW88U1E2qiasAqArpKc6i68X1GVCjClxks4NdB0JUZR9bO9C+
    sB+gilfVtJI5730Adz35C5MGT3QAAAAASUVORK5CYII=
}]

set icons(stop) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAeRJREFUOE+t
    lOlOwlAQhfEPD+BzCeKCCKi4C0YNhofihzEaH0qhpRsoJqCM54y9FUoLmjjJzd2/
    nlluVzIJ5pbLkslmM5nRKGlb11bb7ZXUzekNwn7blgIXgbxSSbzt7bmPpUJTYbWa
    OPv74lYq4gKadG4OmggDyEWz63XpnZ+Lc3oq7vGxrmmLhSaCpsEsAnCRfbzZWOsB
    7hweintwEMEVOgc0CtB3mk3pXF9L9/JSLCi1oDSC8RxC4VWryUCBfQyH7OTl9lZ7
    Y4QNnp50+vr4KA5gxob391FsVWGPriEen+OxPLdaCuvc3Ej36krvGGUc946OdI3K
    aB7uaR9mX4E23CBw2gijmwoM3ZxMJpEyumns/e5O/I0NZXwD4Q4nRhkPmphxbCP4
    c8p2d5UXbG1JHzB/ff0HaEFJXKF1caGZVTeRSQeZfHt40Dlj5u/s6JiwQT4vwdra
    D5AwK0y/1WgIYfbZmZaFgbl7exovvha/WIyUETbI5SQI20wtOoAxQVoWJydaY1SW
    CCsUVBlh/TjMUKnURjIYsxkYnlykbHNT+iHsFW4GdBfAhe+5S3VQxkx6ISxAWQR/
    hU0rtVBv+oLCP4wPmA9lVNSnMmR1obK4ZHUf2WeNMq7Ruw2fJYFL/4X/deALuBEI
    lHqhVdQAAAAASUVORK5CYII=
}]

set icons(inspectas) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAAABGdBTUEAALGPC/xh
    BQAAAwBQTFRFAAAAZGRkbm5unnkWpoEapYIarooftZEjtZIjupcml5eXpKSktra2
    uLi4/9+A/+ih3Of33uj3/fTP/vTQ/fTR4On34er44+z45Oz45O355u756O/56vD6
    7PL67vP77/T7/v3v8PT78vb89Pf89Pj89vn99/r9+Pr9AAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAA1NJ/fAAAAQB0Uk5T////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////AFP3ByUAAAAJcEhZ
    cwAAEnQAABJ0Ad5mH3gAAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41LjEw
    MPRyoQAAAKhJREFUKFNtz9ESgiAQBdCQIkG3Io2AxIQs//8LDVFxMu/DPpzZC7O7
    fiMrJGGukIb5i7QJOmCehDA4pk2aTph03bt1jpCiLMorISN+AJy1tTnQM93Pmy1j
    FiEEEp8wzPhy9mlM9dAay2RGB2Aqb0phEdEy5nzdP5AtWPs9rdVdiBuPaAC0lEJw
    zi8RK8ZUqKNsQf+Fr/o1n4iDjbTgdPuYfMK/bGDffwFm1sl99am1jAAAAABJRU5E
    rkJggg==
}]

set icons(asgraphics) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AI9JREFUOE9j/P//P8MooH4IPLze959YTNB2Yg1CVofXUJoaCExQoESF4X10caJc
    CDKLagaCDIN5HZkNEsMmRyBiEIahG4puOMwCoryMHjnI3n9wpR/ugxtnu/DnXVyx
    DDMQZBgIgwyCYbJcCLIIm2HnDreQ7kJk1yCzQYYRNBDkfJBr0A2BaUanCWa94a8A
    AAl81eQA/IZhAAAAAElFTkSuQmCC
}]

set icons(asobject) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAARBJREFUOE/l
    lGtuglAUhNkTG2ARrIM1uAiXV1p88lBUBOWd0xnCbUiN9pj4o4kk8/djvrkXLOu9
    H8/zZog8kdnDxQiq216qppdr3UtRdZKXnWTXTk5FK4e8lfTcyC5rJDk1w4v/BJaA
    ua47JAcou7Q/sP0IiwGLjrUOeEEr27aHEIYGN3EcR7YHJbCA4pmKgB2hmUKTzRJo
    xmgVArRJa1nvK11DwozydC8qTmHLnRLI8Y0yx7+nHCRKIE/y9/jcaw3NFTQXAAVx
    KZ9RqVMmzCiH0NyOe62gSNjXCPsIlUDeL6PM8e8pq4Ecn4qEUZHjcy8286FJkInq
    Yk9hixHGvfwJ6Bnga7/l//1rDOZz6xX5Bng3FJPKQQRaAAAAAElFTkSuQmCC
}]

set icons(asoutput) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AXZJREFUOE+9lF9LAlEQxes77v0APUUEQQThpqIlW5mSKQUZklYUGYl/6MEgqaAH
    IYhe+wJFgZGB5OrKaea6KyF5dwNp4TBzh8Nvz16WmZwY0wNgTCQbw8CxQkcC/elr
    aPFHz2I/hxwJ1GIPWIxkPIv9amD0Hrqxj6em5Sr2aeR3Adbhj+YkrN0hmRZMEtd2
    p0eVxeceAtEDiPW6GihW7xCKH0mgQfcTTFaxYBQwox9ian4PrXaXZKH1ZUmfRn51
    QuMGka0TCWy2ukqxTxi3LglXaljbORsk5JTh1CV8G2XMhU8x7cvJpI3PDta28xCR
    KxfgchWxdEEC3z5MvNri3jnLvmkitluAIL/yk0XoApuZogQ+v5t4aZC4Oj2f7Vki
    UwL71cBgEclsRSqVLduV+lx/luTZoK9ABEtq4GyiBhE4/11+e+5U8rFfmXB4ZcgX
    6HT5rKX8ADDsUy6HPoR+Cf34R3V6nvflpPtTQq9L7v/Wl9dEo+7wGyUgTwV4niOT
    AAAAAElFTkSuQmCC
}]

set icons(back) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAAABGdBTUEAALGPC/xh
    BQAAAwBQTFRFAAAAoHNzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAasG4xAAAAQB0Uk5T////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////AFP3ByUAAAAJcEhZ
    cwAAEnIAABJyAV5lW+MAAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41LjEw
    MPRyoQAAAEdJREFUKFN1zUkOACAIQ1G5/6FxaBmDf1VfQlw6lFBEuAKPmTo+a5jN
    sBixGhBmAfnw/jiezx91JVY1LOoIxQy8ypUwGlB1A1XD/33WtFLBAAAAAElFTkSu
    QmCC
}]

set icons(forward) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAAABGdBTUEAALGPC/xh
    BQAAAwBQTFRFAAAAoHNzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAasG4xAAAAQB0Uk5T////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////AFP3ByUAAAAJcEhZ
    cwAAEnIAABJyAV5lW+MAAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41LjEw
    MPRyoQAAAElJREFUKFN1zUEKADAIA8H6/0fbgCamYPekA+LJJWJE9IQaYaaOUjsf
    1SNXoSuwNlbYi/rjes7GBs2EbsTHHqwR2XlPSI+8BTMv3qT/fehC0qYAAAAASUVO
    RK5CYII=
}]

set icons(parent) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAAABGdBTUEAALGPC/xh
    BQAAAwBQTFRFAAAAoHNzAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAasG4xAAAAQB0Uk5T////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////AFP3ByUAAAAJcEhZ
    cwAAEnMAABJzAYwiuQcAAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41LjEw
    MPRyoQAAAE5JREFUKFOtzTEOwDAIBMHw/0cT+24BR3KZLRBMYT95aTCC5cBYsTZu
    awVtpUZopVMIqEJOMnJ0g5qshd/pN3m49o0KVH+hv3CDRxfMfAHkYf99Ux0nyAAA
    AABJRU5ErkJggg==
}]

set icons(redraw) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAAAAwgAwm
    ZAq1tbXOzs7e3t7n3q3n5+fv7+////////////////////////////9FEnkFAAAA
    EHRSTlP///////8A////////////LGZlgAAAAFFJREFUeJxtzjEOgDAMA8B+wZ0y
    Z+rLEN9oB+Rnk4gkBQlPN9luR6V9SM/lPMlpTkpwAghCtcg1gsLFokV2WRJW99Db
    RrCr5lrfw1n2evZ3/QZoNUzyBudhawAAAABJRU5ErkJggg==
}]

set icons(fes) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAJFJREFUOE/F
    U8EJwCAQs6P4dsWO4CwdwUm6i1XxROy1l0KgBRGvSUwCbiklR/2qIHNRxVpaprv/
    BM8Q9rJy3a1EUOQuVgUzS5Dr0HLlvR/OR2QZan2ts/VcucJ3cpB97utppmEEy3do
    9YP8VztEiAjmFhkhvWGaYLEce6mRIthFzVeAXDZHPuZyEbKGgd7yF/ELKDsDXlOD
    lTQAAAAASUVORK5CYII=
}]

set icons(network) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAASNJREFUOE+t
    lL0OgjAUhXVoSEMijI6OPIKjo6Ojo8/gxGTcHH0ERsPkyOjo0Idw9DHwntKSUmj5
    EZKTG376ce7llGWe54tZDwChKIpKLX1tSm3BNFQEgbw3Vj5gKlartQke0oUbyPmN
    YF/SQ4Th3oT5RlO3ZL8dzqTC8Ei1GA3ErGhh2TUzgGcDKqcnqu/BM9SuTIcKFFPN
    lGLBObq4k86uFDRioYESxvkWrkhwVz8nGNvR+asXaLZDD18kjPPEXqicf6huuuY9
    KdgEuyq1gu8DYn4yOrYTuCPBZRvoioRcgHCr3aLhRi0QeBtahTcImDVDXIPDlITd
    kqmPVDt2RaizJRVy/TJUmUMpxg6+kPf+TRqtVlF6/gU0Ql87ngVogRPXDH8u+jdf
    401IRAAAAABJRU5ErkJggg==
}]

set icons(vertical) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAAABGdBTUEAALGPC/xh
    BQAAAwBQTFRFAAAAd3d3iYmJ1ODz1uH01+L02eL02+T13OT13ub24Oj24un34+r3
    5Ov35ez35uz46O746u/5AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAXJKnIAAAAQB0Uk5T////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////AFP3ByUAAAAJcEhZ
    cwAAEnEAABJxAfPceo4AAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41LjEw
    MPRyoQAAAGRJREFUKFOVzkEOgCAMRFERFaggcP/D4li6aAgm+lfkpSGztEkvuI6Z
    CZqOJecrpRhPIgpBkIUheO8E+QTk3YEE5QSwb9YKqszTgGwdaykYwAvwu6CeRL8n
    9d9VQHmpgJO+Yms3icGE2c5p0JMAAAAASUVORK5CYII=
}]

set icons(horizontal) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAAABGdBTUEAALGPC/xh
    BQAAAwBQTFRFAAAAd3d3iYmJ1+L02eL02+T02+T13OT13eb13ub24Of24ej24+n3
    4+r35Ov35ez35uz46O74AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAtr1uXwAAAQB0Uk5T////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////AFP3ByUAAAAJcEhZ
    cwAADsEAAA7BAbiRa+0AAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41LjEw
    MPRyoQAAAGVJREFUKFONzFkOgCAMRVGLKGAd979YbEurhqDx/Vw8Abvc2Au6etBA
    KHjs64LJ+okbnRmlinIhWC9EjILcG1McrYr8q+AdlCquM8aBPqwFcQqeUSsor3oA
    KyPUI9TTY4SN/cWcTybehVIuYYXkAAAAAElFTkSuQmCC
}]

set icons(find) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AXhJREFUOE+t1D1PwkAYB3D9WMZP4KDRRRcNiYObmuhMXF1Q0MVowKiQIrUBCxIb
    BEErWGZxcMHBpbowQIw14W+fo60I1FKgyaVJL/fL83YdBzA20ofAUaCWMwhYi0zC
    vz4D0b8M6WAF1eyWzhiBuQUJU+ML+K4l2ZLz9wwdCGzHplZPoKkxfFZDLFLXYCf2
    ZWCNSoCl7wrsTFNTeRZZvbKHD3EJtN8XKOx4QIv3eRDdXmQ1M7HGU8DCaOwcQYLK
    j2UoRQVy4QE5KYugd74rMnOG/wVNjMDiXRH5zC0k8RrJ8wT2N2b/ROYImmnSuySX
    UMgVkLmSkOJFCGc8AnoDqGadt8s2wrfTCTTrPn1fAafXLZu+QVpIIRG5QCzIYXdt
    uudd7Qm2Y0CTOoeQXrdLLg7+OAruMNw/2I0RSEvR6zYH7ihii/Xssvq8yQ63kF+M
    0qfBtUvVtinvr2EDokRbkRGmvXgdsb7m0O0/sqsp5odh39aVGRYyz/8AihCzldqH
    naQAAAAASUVORK5CYII=
}]

set icons(filter) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAAAlwSFlzAAAOwwAADsMBx2+oZAAAABh0RVh0U29mdHdhcmUA
    UGFpbnQuTkVUIHYzLjA39c2BcAAAAPZJREFUOE9jYKAV+P//PwMlGMNd2AzLL2sB
    CiMsKm+ZhcJHliPaQN+oWLghJBno17/3f0j35v8xrUv/p9ZO+Q9yHQzDDCXJQFxe
    RnZheEoN5V5GtsjCBeL9vS1i/0GY5DDEFesgw/79fY9iKFGRsqtB9D8y3gnlg2iQ
    gSC8q1EU7FKCBm6tEv7/99MxKD7+/+9HIBuEPwHZIPGPCLEt1cKYJmLz3voS4f/r
    SoT+rysV+r8ehEFsoBiI/efZPDBeXypMnAvx5ZqV+YJgw0A0TB1BL4MUoucUWCwv
    yxb4D8IkxzLIQLLT4YDkFKpkPbJLG1qVsxSbCwCEgN1oUjcSBAAAAABJRU5ErkJg
    gg==
}]

set icons(layers) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAMAUExURQAAAG5ubgAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAANekBdkAAAEAdFJOU///////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    /wBT9wclAAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGnRFWHRTb2Z0d2FyZQBQYWlu
    dC5ORVQgdjMuNS4xMDD0cqEAAAAbSURBVChTY/iPBZAkyIgGcAtighFuETr4/x8A
    5ZUbVHWiqyQAAAAASUVORK5CYII=
}]

set icons(config) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAAABGdBTUEAALGPC/xh
    BQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAD
    AFBMVEUAAABtbW2Vl5ianJ2bnZ6dn6CfoKKmp6eoqKjJzdLW297a3+Lf4+bl6Ovr
    7vDy8/T3+PkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAA6e3eFAAABAHRSTlP/////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    //////////////////////////////////////////8AU/cHJQAAAAlwSFlzAAAS
    dAAAEnQB3mYfeAAAABp0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjUuMTAw9HKh
    AAAAcUlEQVQoU2XOWRKAIAwDUAO4gOv9L4ttqRo1P4U306WrFEi0MmKazBgxHs1e
    uO+GeOG2KcpYxnUdZNPAiH6x9IRIsyXJiAsRSynRD1XUZ8g5B79I0YBN8G+Grfsx
    Rf3hi1q+aAGPdERga+g33/F2Tq0nxjgBbZnS0EYAAAAASUVORK5CYII=
}]

set icons(newnet) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAUVJREFUOE/V
    kiFTw0AQhU8xFRE1eFxBMFMHAscf6E9AYnHIDgaJRPInMPwCFDUIDAO9aUobGGAG
    Q9zx3nVzs4TQJaC4mTe5XPK+vN2sc/9xBYS21KquMHt8SZoWz2Eyewp+WuiP/A6Y
    YHlR3o7zNybPsmxHVbD1E3JMp5ONJ/Pyzj8QyFVvh8lsgpWVa0UBVxd7c6WeSbLS
    e59VrgvnTplyF8J+BHUtYvwBPp8HlMnevStYH4BLqMMzXHl/JUmZtrGn38E6AuvX
    Epk9TcmqUgFimiGl0q7LvQ1kmVIqS4gGmK+hHnQI3YiGB84NrDEKAoxzpwXIPXQM
    bTC19LGL/euyH0Ng48xJ6Z+8ONtmb5cCJRXfiSVvLko+l4R72oyzfRkla3q+Podx
    DToT8JHq70l7mnIQXO/vn4BiNsel7UfSSEmvo/8Dk8gZlTZw9lUAAAAASUVORK5C
    YII=
}]

set icons(newrun) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAANZJREFUOE+t
    1N0KwjAMBWB9WF/SK6/6FCod7seJKHhjvdIeIRJjktaxQRiD+fW0iVuGEBazXgDn
    rB8sp316VVpcBYfT9UHVj5fUDufUtGOihTzUBTm2i90NIC7cLdQEORYPx7Rv+k9C
    L6kKatg2dncqSqulVEE6M0oGCEipIe8RlC9hO2iAhW3E+clnFeQY0vFFJ4FoAD8z
    gIC8okXVhBzjCTO4zrWiH8tn8wwlSGhpuyaIjmopJ4PW4E4CtVmrbYi6ZWt4axry
    L/j1QZDbN8em5u/lvfMCYx9U8FAnH8kAAAAASUVORK5CYII=
}]

set icons(restart) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AHxJREFUOE9jvHTpEgNVAchAamIMw7Z4e//v9fAAY1wWgdSku7hglSfZQJiFVDEQ
    2fUkG4iuAdkwUHAQbSAs/JA1oBtGkYHYDKPIQJiL0WmKvIzNUIoMBKVHqroQlsCR
    DaXYheiGEm0gSCEM48p6+OSpWjCASy5qljQj1EAAxdJWY10KTyIAAAAASUVORK5C
    YII=
}]

set icons(finish) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AVBJREFUOE/NlD1OAzEQRuFsW1BAR4eExAGAI+QEiIYWCSQuQEdDFcmioNsjhBtE
    W6/RM3pmiDfIBQWRRk7smedvfpzD7fbp4E8/AHft7maVb1cX+fHhPi+d/7bXwHAW
    eH11mc/PTov1ghtgSuuiDhuGodrHZtMFbYCvL88FhioUAmWdpikLTSlljJKwN45j
    vawBqm6e56wBJJDflEPlAPXhwtLgWBvTJQgFQHAEQDDfrSnrl9+67ANugDFdAk6O
    j0q6MXV8MACcY4AXFdpdnGJaqFBlLEVsGrE/FKqOA1NlVQ0g1XohqigN2TiztYZs
    0JAI4DvOrARGReyrNo5UBZouhyq0oyjjQkeJ/dgQ61dTfn/7HmY2nSsgpufsOT6+
    ItQ3ClXH4e4TA2QXHW5r6yTEmJIyIFPY92ZRHV+Ebx6lDbD34ff4Lf7b9ATu8/n/
    wE9OgMfb1uAm5AAAAABJRU5ErkJggg==
}]

set icons(findobj) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAnJJREFUOE+l
    1N1LU2EcB/AJQUGXddNlQf0DCjKGCN5owXrBsbQXFlFe+VpeFbuIGombujViYWgv
    NqYex+Zmo7UdOzseZ9t1etFNMjzo9MYL5/BE+/Y8p53jzpos1uB7sZfzOd/f7zys
    Tvcfr12vAW/Tp3Tnzp7WHT9xTHfh/JnaNYplA9fxczcsR+CWEH3VhZrEUuxizztI
    2Vnkf0wi5LyrBXufcVXvUI4dFLHcqgvOvsuH11s9/LaT4/F0ij8SLR9TyjJys73V
    F9gJ3Qb9Xh758Uth2x4T4E4tw7kkYNDJSaW78I9aQMOMWDA9dEvemYLlvrm0GB3T
    5ufxPMBheJ6XQ9932/+MT6H01zRSyRSExDIWoywmrObKzZQWD0dZPJmLwxZiYQuz
    6HbENRgFk3wSXOwLoqFPCM8E4X5wVdus/PH2DMWl4c8sBt1RFVNGXRFWkFhMIPYx
    igUmBP8UAxd5AOrOjjorfS5WfSAb7/Uo7I0ASMFH9sZG4oj4FxD0zmF2woexXmPV
    E6HepxQDCgQFJsne5n0BMG+m4Rv/8O/g3xgFaVJkb9fge+2tjq13dhpI1khyG+Nd
    +JUXisghRsenB7fqqJnmZophvb0dGaMRmbY27Ho88phKM4pJ360qZjabC/39HSgN
    +QwkdTqCrIkmk4qJLS3YvHJJHlEJxWjokslFJrv9RmF//x7y+ftyEok7FGMUMEdb
    ia2tIG0hGgwQ9fqDSlgR1GAUVNvRH5BGj2grBdtqbITY0BCk31FUaVbEZjjOgtJ2
    DsdNCprVI0KAk2JT0xhptUMgaau+PkKir3RWld0NDHRAiaZdTX+GVS76DYYtd2i9
    SfybAAAAAElFTkSuQmCC
}]

set icons(none_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAMAUExURQAAAICAgKWlpQAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAJRq7HwAAAEAdFJOU///////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    /wBT9wclAAAACXBIWXMAABJzAAAScwGMIrkHAAAAGnRFWHRTb2Z0d2FyZQBQYWlu
    dC5ORVQgdjMuNS4xMDD0cqEAAABESURBVChTfctJDgAgCANA6///XFnqRow9EDtI
    Y8kL+pEEaEkIKIE9E1JsLPDiuIGITx+oJ7G2MSG6i0DdRHAk4E4BcgDaW7+tR/gF
    igAAAABJRU5ErkJggg==
}]

set icons(chan_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAMFBMVEUAAACEhIT/
    //////////////////////////////////////////////////////89O65jAAAA
    EHRSTlP//wAAAAAAAAAAAAAAAAAADwvvhgAAADdJREFUeJxjUIICBjSGAhOEocDA
    yAClBRigNEgKzAcyILQSA5RWYoDSSjBaiQFKA6WYsNuFxAAAc9UMXxHyo/oAAAAA
    SUVORK5CYII=
}]

set icons(cogwheel_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AK1JREFUOE+1U8ENwjAMhNmyQyX4dgn645cHO1RVlvB2KZyls4wbaEVEJCtyfL6c
    7eRcaz11LRD0WFeyqu+5/X8EKaWVdn8t70fFVgJApRRNXJZBDX7Ok+48i2RKMI4X
    AxDY6g1j3JGnBPN8M8leAYAtnypyvr4TiDzWSOYlk4yYDQECDPqaRcT64zFfFXwi
    wPlGAZoBeb6EIwTWRDSSY9wroTnGOLIIOvSQfv0TT168dPIInVHIAAAAAElFTkSu
    QmCC
}]

set icons(compound_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAGxJREFUOE9j
    /P//PwNFAGQAJZhBTk7uPyUYbMCdO3fIwiC91DUAl1dwuRDDBSCBxs6LKBjmRXTD
    QYaSbADMcGRDUcIAlwtgtpNtAMy5FBuAHA44wwBbTBAdCzCFxCYunAmJZAMoyguU
    5ESQXgDj9GhR8mUscgAAAABJRU5ErkJggg==
}]

set icons(placeholder_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAMFBMVEUAAAAAhP/c
    3Nz////////////////////////////////////////////////////nj/q/AAAA
    EHRSTlP///8AAAAAAAAAAAAAAAAAMIMH1wAAACtJREFUeJxjMIYCBkyGAYMSCDIz
    GCiBATODEYShjGDApUhTo8AEgsqYlgIAaT0SzHIyPsUAAAAASUVORK5CYII=
}]

set icons(simple_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAEFJREFUOE9j
    /P//PwNFAGQAJZgizWDXU2I73AA5Obn/5GKwC8jVDNKHYkBj58X/xGKYpaMGDLpA
    JCc9UCchUZIfAGyaNWbkC6VeAAAAAElFTkSuQmCC
}]

set icons(message_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAMRJREFUOE+1
    ku0GhEAUhndvKpEkEpFIJJJIN9Bd7E11Xe/Ps73TlD7NZmycH6Oe9zlzOu9xHF9W
    DwNsygpW3dvYbwPQdcNUgrYVNI3wfCc6dYC+JzDDdS2oKkFRCPJcrkJ2AfC8YbUS
    LMsVRpoK3x9D9gFs92BFlgmSZK4oOnWxD1isU7sKpFWDCENBEBgC9F1XaxwrK0H4
    Pq9gCOAMLqwE4brmGXBAyri1EnQcVca/sHwwGT/KqkGef96Dp5v5n1V+0sUXTs0o
    fqimM9gAAAAASUVORK5CYII=
}]

set icons(queue_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AIZJREFUOE9j/PfvHwNFAGQAIdxpb/8fGSOrZ0CXRFeISx5mCE4DQAqOrVwJt/ne
    rVv/QRhmIEgO7H18zocpBmmEqUM2BMQGGzB7tu9/EEZnYzMApAZZfNQAaCDiigmi
    YgFfQiGUDsDRSG5KhKUNgvkAOd6RvUSSASBDYEkZRsPzAqGcSEgeAEvthurzoY+N
    AAAAAElFTkSuQmCC
}]

set icons(container_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAMFBMVEUAAACEhACE
    hITGxsb///////////////////////////////////////////////9GEEOiAAAA
    EHRSTlP/////AAAAAAAAAAAAAAAADW2LcQAAACFJREFUeJxjcIECBiwMR0EgEAEx
    jIEAwjBghjAok8JpKQCFmhqioMIOzgAAAABJRU5ErkJggg==
}]

set icons(stat_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AElJREFUOE9j/PfvHwNFAGQAJZgizWDXU2I7UQZsdnH5D8K4LCLoArIMQNZEtAG4
    NBEyDO6FkW6ApaXlf1IxLF0QTAeEUurAGwAACvmYamLLnngAAAAASUVORK5CYII=
}]

set icons(outvect_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAAMFBMVEXAAAAAgAAA
    AP/a0tL//////0D///////////////////////////////////////8Dfx5lAAAA
    EHRSTlP/////AP8AAAAAAAAAAAAAF1YY2wAAAEtJREFUeJx1jbsJwDAMRF/hLCKc
    PYRQemNy+68S27hIkVz14H7kFl8g6Z5wDVCywQsZZhLDMnVrJYlT6qxwA7NKOocU
    FWfV34O/pw8hWyAp4RketQAAAABJRU5ErkJggg==
}]

set icons(canvas_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAABGdBTUEAALGPC/xh
    BQAAAwBQTFRFAAAAOXKteJNkx1c8zWJI0WRJ1IBsgICA9ODb////AAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAsrjIQgAAAQB0Uk5T////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////AFP3ByUAAAAJcEhZ
    cwAAEnMAABJzAYwiuQcAAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41LjEw
    MPRyoQAAADxJREFUKFNj+I8GiBFgRwEgAU4kABdgZGQkSYCDjY2Dk5MJCKACzECA
    X4CDhRWoBWEGCgAKoAFCAv//AwBpvHdCpf13wAAAAABJRU5ErkJggg==
}]

set icons(figure_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAMAAAAoLQ9TAAAABGdBTUEAALGPC/xh
    BQAAAwBQTFRFAAAAOnGpOXGqOXKrOXKsOXKtOXOvOXOwOXSxx1c8yVc7zVg70Fg7
    ymJI0mJH3ZqK4pmHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAEVu1NwAAAQB0Uk5T////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////AFP3ByUAAAAJcEhZ
    cwAAEnMAABJzAYwiuQcAAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41LjEw
    MPRyoQAAAFJJREFUKFOVy0kOgDAMQ1GmQomBcP/LhsRhUXWD8O4/yYN1+wFlrtO6
    NcAeG2DXFwAYuyR4A+yFIHsM0XlBQnx9DtqDXSLHmZlgeisjRmj3BWYPcyC5hq9g
    KQwAAAAASUVORK5CYII=
}]

set icons(gate_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAD5JREFUOE9j
    /P//PwNFAGQAJZgizWDXU2I7bQxwcHD4jw+juxjDCyDN37+nYsUguVED6BUGFEUj
    qSlz4JMyAI6uuXkgcWyIAAAAAElFTkSuQmCC
}]

set icons(param_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAYAAAAf8/9hAAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    ANVJREFUOE9j3L59OwNFAGQAJZgizWDX47Ndz3fJfxDGpwanAd4ZK/6HTJkHxiA2
    LkOwGgCy1SJ54f+wRdPABoDYuFyCYYBH+qr/RnGLgJrnwXHIorlgMZAcuktQDADZ
    4tM+D4z9O1AxTFzSCtU7GAZY5M7+D8KOldMhuApCw8TxGgBynkPssv+KPnP/e/RM
    /+/VNQ2MQWwl37n/QXJ4vQCTVHdb8l8zePZ/r2lAA5qmgNkgMWwxgTMaPZMXwQ0A
    sUmKRphikH/R/UyUF0jJG7TNC8S4BADaZQ4nNafa9AAAAABJRU5ErkJggg==
}]

set icons(tree) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEVAAADGxsaA
    AAD////AAAAAAACAgIAAgAD////////////////////////////////GxcxdAAAA
    EHRSTlP/AP//////////////////0XJbHgAAAEBJREFUeJxjEIQDBkHBRCKYogGh
    gUBmWlqioKixaSiQmZiYKChgbGwAFk1LgzJBoqLGxqYwtQGhoVQ3DMnpMAAAQhIf
    b/Voq10AAAAASUVORK5CYII=
}]

set icons(unknown) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAACAAAAAgBAMAAACBVGfHAAAAMFBMVEUAAAD/AACA
    AACAgID///+A////gP8AgIAAwAD//8CA/4D//8CAgP8AAP+AgIDAwMB6idRUAAAA
    EHRSTlP///////////////////8A4CNdGQAAAKZJREFUeJxtkkEOxCAIRVnMvoEL
    mMwFvMIs3Pf+txgS9xSoFjQlaWJev/+jAu0HH/8aQNMFnLLU/w3gCg6mkkBXIBsQ
    rsKo9QASQZykq6mBarBGrK35AaogA5QUVhMcE+B3pgzBDtB3BBgC7yMsuUSKCwg3
    UDgAuQXlPsyo3ilcNkDpEh2ol/Y1Fad7jZOM0+qPkZJAPMPby2VFXxp7B/cg2ESA
    T8QFuTKHjk1mSQUAAAAASUVORK5CYII=
}]

set icons(1pixtransp) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAAEAAAABAQMAAAAl21bKAAAABlBMVEUAAAD///+l
    2Z/dAAAAAnRSTlMA/1uRIrUAAAAKSURBVHicY2AAAAACAAFIr6RxAAAAAElFTkSu
    QmCC
}]

set icons(16pixtransp) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABAAAAAQAQMAAAAlPW0iAAAABlBMVEUAAAD///+l
    2Z/dAAAAAnRSTlMA/1uRIrUAAAAMSURBVHicY2AgDQAAADAAARaJmtEAAAAASUVO
    RK5CYII=
}]

set icons(modtype) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    AYJJREFUOE+tlM1Lw0AQxfVfEwRRUBQPIooe9NaLePEgqKeCRWyh9ashKhJaiiVQ
    aYNBsa1aUEsRingQPQT0IIJHKQTGfQu7xDQfUDPwWHYz/PJmJpv+DcvqizQAjFKR
    wni1wp277Ffrlio3cVL1eaY5LuxxHtgiL2C1ucMBOSNGZ7U1Kexxjue+UDcQybv5
    SSpdrVO9tUcPbU3KbGyTkC/UCfz4fKa0NkbXLYVEPL1UONAZAor8LqdOIHqklWN0
    ai7T5V2KMzqdH74XUAHLG0vcbSAQA8gWpkgpznIJoPX+KPeAKIVpLuQHAlFuQh2i
    zeygBJRrcbJtm7AiBAwr8kMdZliS0yHKhUOUjkArANtSh8MdopyMNkHJo1HpEEBI
    AO/bOdaWGZ7nOWnnUL6+31jJA1Q0V/5MFcBqc1+eAYi80CmjHygpdTJCx6VF0i9W
    uwRYWhvnpXt+3F43RUAP9QVyCy/zheENQXfZYN/lARsABoX1vJHo7S7/6//o57Bn
    aNTAX9fnY38wi/BuAAAAAElFTkSuQmCC
}]

set icons(channel) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAAADGxsaA
    gID////////////////////////////////////////////////////WYDUgAAAA
    EHRSTlP/AP//////////////////0XJbHgAAAClJREFUeJxjEIQDBlKYAkpQwMgg
    wAAFjAyCMCZOExAKkLQhGUamcxBMAJaCC0urkZPoAAAAAElFTkSuQmCC
}]

set icons(props) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATBAMAAABiojCGAAAAMFBMVEUAAADGxsb/
    ///////////////////////////////////////////////////////TdTWlAAAA
    EHRSTlP/AP//////////////////0XJbHgAAAClJREFUeJxjEIQDBhxMAQYwADOV
    QEABzFQACSpgE1XCKkqZWoQbCLgXAJGwDaRRYr5VAAAAAElFTkSuQmCC
}]

set icons(cut) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABMAAAATCAMAAABFjsb+AAAAAXNSR0IArs4c6QAA
    AwBQTFRF////2NvmvsPNnae5tr7MFzJdeYedTWB7Youzc5W4rsXdYYuzK22jR32r
    SH2rEV6bEl+cEl+bAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAd4ngqAAAAAF0Uk5TAEDm2GYAAAABYktHRACIBR1IAAAACXBIWXMAAAsT
    AAALEwEAmpwYAAAAB3RJTUUH2AUVCjYzpsVpigAAAGNJREFUGNOVjksOgCAMRAut
    Han4u/9lFTBR6MrZ9SXTN0T/w9GhAHEsqq9qYTJUmUTxXCmlYgBDJTS0GNlMOuHj
    WIlsUwWH91E2syzcLznO/RbCL5Fm6tJMfappYNU0lqvpVy5+VAJUiVmQ7QAAAABJ
    RU5ErkJggg==
}]

set icons(copy) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABMAAAATCAMAAABFjsb+AAAAAXNSR0IArs4c6QAA
    AwBQTFRF////8/X7+Pn8Y3qn7vL68vX7+fr8+Pn7XnajZn6oaoKsbYStcYixc4my
    fJK4fpO6jKDD8PT7gZe8hJq/iZ7BkaXH3uj43ef33+j35Oz55+757fL68/b73Of3
    3+n43uj34er46vD59vj75u758PX78vb79fj79/n7mpqQmJiRnZyNmpmQoZ6KqqSE
    pqGHop6KnpuNxLRzwbJ1va93tKp9tap+sKeBqqOFpqCHx7VxxLNzwrJ0wbF1vq93
    vq94uax6uq17sKaBq6OE4MiP1LJo1LJp2r181bJpAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAMOlcgwAAAAF0Uk5TAEDm2GYAAAABYktHRACIBR1IAAAACXBIWXMAAAsT
    AAALEwEAmpwYAAAAB3RJTUUH2AUVCjUm4DXeogAAAKxJREFUGNON0NkagVAUhmFC
    ZjJsaaKEZCihzDLm/u/I2kvhcdS3zt7nP1qJROy2Ub/Gsuw/7wwmSx16RLgfkroD
    bjBM8HTetszIgwV4Mde7BfcD2rlPuBO4nJShI5orSWkfvFEpF1I1H83TCLcClzAX
    baaL4kULd5qHZgmEW4PTdPGKZququhHCnWChjTukOVWjbLSJovDUq6V8u9uao5kQ
    dXq8Mvr8wfwW/6EvBlEaopGOlEcAAAAASUVORK5CYII=
}]

set icons(paste) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABMAAAATCAMAAABFjsb+AAAAAXNSR0IArs4c6QAA
    AwBQTFRF////9vf68/X6h5Suh5St8vX7+Pn7XnajbYStX3OWYHOWcYKgh5Wu3+j4
    4ur47/P67vL5gZe8gJS0gZS0kaXHgpGqh5Wtl6fAmKfAjpuwjZiqr7rM3uj45u34
    8/b7jJiqrrrM3uj34er44uv46vD53+n34uv35e348/b6kpum3un3kpym8vb6q8HU
    9fj6mp+hmaChoaScqKiXr62Su7SKtrCOsKyS4MiP2r188sZx8cZx8sl58ch58syD
    8s2D8tCO8tGO9NWZ89Wa9Nml9N2w9eG69eTC8cVx8sh588yD89CO9NSZ89Sa9dil
    9Nil9d2w9uG69uPC9uTC9ubI2K5szKh10Kx41LB7zqx5xZphw5pkzql2x6JyyqV0
    0656wZtsxJ5vvphrrYFSr4RWsYlcs41jvJZqtZBn5NbG1MGvAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAZEjVUgAAAAF0Uk5TAEDm2GYAAAABYktHRACIBR1IAAAACXBIWXMAAAsT
    AAALEwEAmpwYAAAAB3RJTUUH2AUVCjYXmsaNWwAAAL9JREFUGNNjYCANSOrqSqIJ
    iSooSCuIIglkREZyS4iLS3AnRWbAxMKDuYSFhYSFhTmDIxBicBAKE4sLCnQLMgGD
    KJhYmKtrgKsJGxBYmMLEol38XfxN9UTYGc3hgrG+fs7OZnKsOhoaTMZQsRgnH0dv
    I34RQQ52ASOoWIKDvZeXoQoYGELF4m3tPD0NZEHq1PWhYok21h7W2kpqfMpKfJpQ
    sbQQd0sreRlVXi0tRSmoWGZ6akoyM48YCwsQkRCWAE2wIld3Fw63AAAAAElFTkSu
    QmCC
}]

set icons(copyptr) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABMAAAATCAMAAABFjsb+AAAABGdBTUEAALGPC/xh
    BQAAAwBQTFRFAAAAIDkyIz4yI0EyKEE5KEU5KEg9LUg9LU49LmoiOnwrHWN4HWJ5
    H2R4H2V5LU5FMU5FMU5KMVZKOFZOOFZTIGV5ImZ6JGh6J2t6J2p7Km17Km18K258
    LXB8Y3qnZn6oU408c6dYaoKscYixc4myfJK4fpO6tap+vq93uax6uq17lcJ5wbF1
    wrJ0xLNzx7VxxLRz1LJo1bJp2r18npuNnZyNmpmQmJiRmpqQhJq/oZ6KpqGHq6OE
    qqSEsKeBsa6xiZ7BjKDDkaXHn8eBpsmHrs6RtdKZuNKcuNKdxtuux9uvx9yv4MiP
    1ebC2+rM3Of33uj33uj45/Pb4er45Oz55u756vD57fL68fT78/b79fj7+Pn8+fr8
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAIjAcQAAAQB0Uk5T////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////AFP3ByUAAAAJcEhZ
    cwAACxIAAAsSAdLdfvwAAAAHdElNRQfYBRUKNSbgNd6iAAAAGnRFWHRTb2Z0d2Fy
    ZQBQYWludC5ORVQgdjMuNS4xMDD0cqEAAADsSURBVChTZcoLUwFRGMbxxCKW7LZR
    6qiUSymnqBTy2nVLLou1rn3/r7Gd8x6ZMf4z58w7v3kOHN4J/v8JU9jT8OIxoxR8
    QGmEboiZqhx7CQEJqIcKZrs8kMkPIeQX/Cois6fVZe9oOPi+gHWx8IymaQuIDyfd
    dvNs1S++POLuISKdD7o3rUbM5V8us2iZ+WGs025d56KQVBb3aLWZFD5tNnKB0JyV
    QfuSbNslB2U5dZdMzGpoFdXQ3QC2qIpWtizLOzX0T76bVtDexobKXVRGezdNk3k9
    fXs1Go1f0Uos7qIPNB73TVvbad8c5w/yeb769MEdsQAAAABJRU5ErkJggg==
}]

set icons(debugger) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAAABGdBTUEAALGPC/xh
    BQAAAwBQTFRFAAAAIDkyIz4yI0EyKEE5KEU5KEg9LUg9LU49LmoiOnwrHWN4HWJ5
    H2R4H2V5LU5FMU5FMU5KMVZKOFZOOFZTIGV5IWd5ImZ6JGh6J2t6J2p7Km17Km18
    K258LG97LXB8U408c6dYksF/lcJ5sa6xn8eBpsmHrs6RtdKZuNKcuNKdxtuux9uv
    xtyux9yvy9+01ebC2+rM5/PbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAv72P9AAAAQB0Uk5T////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////AFP3ByUAAAAJcEhZ
    cwAAEnEAABJxAfPceo4AAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41LjEw
    MPRyoQAAAKtJREFUKFN9josOgjAMRUVFUVEeouJzKuWhiDD+/9/qtg4whniTpb0n
    t10H2KO/cK2rUgM98QJqWwhTQHSpJ+h7zoQxMAUnURJY/WKMoTFWVo+f3zNeFRcA
    y9cwCBCOvObl80QbKOmah4rf8yzZK6vHh2FR5rc0Dg2rgyZsH1l6jXYgL9bQgdUm
    iaP5UjmC8kvDXti2ck1SaAQ/x0tNdBVqodzQqEt+qQcifgDs/CKDOFgY9QAAAABJ
    RU5ErkJggg==
}]

set icons(down_vs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAAUAAAATBAMAAACqztpQAAAAMFBMVEUAAAD/////
    //////////////////////////////////////////////////////87TQQwAAAA
    EHRSTlP/AAAAAAAAAAAAAAAAAAAAE1gGDAAAABhJREFUeJxjEBQUYMCFQUAACAUZ
    catBwgB/EQNjxeU9+wAAAABJRU5ErkJggg==
}]

set icons(node_xs) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAAYAAAAHCAYAAAArkDztAAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAA
    OpgAABdwnLpRPAAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAA
    ADVJREFUGFdj/P37NwNWkJ196D82zAATzMxc9R8ZgyXQBUF8rBLp6RP/MyCrBgnA
    MAMyB5kNAHL8XDUQQ11rAAAAAElFTkSuQmCC
}]

set icons(modnames) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAADAFBMVEUAAAAlJSU8
    PDxRUVFjY2N0dHSAgICFhYWUlJSjo6Otra2xsbG0tLS/v7/BwcHMzMzZ2dne3t4A
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAC7h23zAAAB
    AHRSTlMA//////////////////////8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAWHyGPAAAAG9JREFUeJyFzksOgDAIBFAppbVa
    S73/YbGiqDF+ZsHiZSahk4d0bxjmuViG8I3lActw5sB8WjbM4ZL89ZIGbsisuF6p
    XBV7olYDxHY9RtyalUHnjivYnHw0ZGcIozZ5dZh2TM6TFyRMIpND/PvzFxduXvEg
    WbY14gAAAABJRU5ErkJggg==
}]

set icons(zoomin) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAADAFBMVEVCazlKczlK
    c0pSQilSazlSe0pahFpjWkpje5RjjGNrc3NrhKVrlGNzc2tzc3Nze4xzhIRzjJxz
    jK17c3N7hJR7jIx7nGuEa1qEc1qEnKWEpXuEpbWMc1qMlJSMnJyMnK2MpYSMrb2U
    c2OUe2OUe2uUnJyUpZyUpa2Utb2Utcace2OcjHuclIyclJSctb2cvc6ljHOllHul
    raWltbWlvcalxs6lxtalztatpZStxtatxt6tzt6t1t61nIS1pYy1tca1vb21vca1
    xs611ue13ue9tbW9xs69zta9zt69zue91t7GpYzGvaXGztbG1u/O1t7O5/fO7/fW
    1s7W3t7W5/fexq3e7+/e9/fnxqXn5+fv7+/v7/fv9//v///3////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    //////////////////////////////////////////////////////+MBfgOAAAB
    AHRSTlP/////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////AP//////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////8q7QIgAAALZJREFUeJxjiMMCGHAKhmhKK+o5
    RaII2strWJmZmhhHIgl6SJpY87BJOXvIRyEEpRW9AjmBggFObghBbjMeTh4eRjGx
    MFUkQStWVqAwC0uILEKQw5qHk5OHQUEhHEmloImlMycTT2yMgwNC0Jff04+HiTM2
    issf2Z387gEhMW58wrquSD7ylxUQFTAKshBX0cbwu49BqJYKRoBoe4cqKWGEkrZh
    qJYMRtDpWNgxY4YnL7sEjkAGACd4cD2Fo8KaAAAAAElFTkSuQmCC
}]

set icons(zoomout) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAADAFBMVEVSQilSazlS
    e0pjWkpje5Rrc3NrhKVrlGNzc2tzc3Nze4xzhIRzjJxzjK1zlHt7c3N7hJR7jIyE
    a1qEc1qEnKWEpbWEtYSMc1qMlJSMnJyMnK2MrYyMrb2Uc2OUe2OUe2uUnJyUpZyU
    pa2Utb2Utcace2OcjHuclIyclJSctb2cvc6cxtaljHOllHulraWltbWlvcalxs6l
    xtalztatpZStxtatxt6tzt6t1t61nIS1pYy1tca1vb21vca1xs611ue13ue9tbW9
    xs69zta9zt69zue91t695+/GpYzGvaXGztbG1u/G5/fO1t7O5/fO5//O7/fW1s7W
    3t7W5/fW7//W9//W///exq3e7+/e9/fnxqXn5+fn9//v7+/v7/fv9//v///3////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    //////////////////////////////////////////////////////8c2/2kAAAB
    AHRSTlP/////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////AP//////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////NF1uiQAAALFJREFUeJxjSMQCGHAKBquIymja
    RaMIWkspmxkZGuhHIwm6iBiYO1ho27tIxSIERWXcAkId3O397JwQgmxG7Ox8IBCh
    gCRoxsTECAIREghBFnMxaWkxIIhBEuQxMLL3CQiJibaxQQh6cbl6+/jHxEezBiG7
    k8vFLzjGiZNfwxHJR74S3ILceoEmQvJqGH731AlXlccIEF2PcFlZjFBS0w2XE8cI
    OnUTKwbM8ORgFsYRyADbo3SgHWkVkQAAAABJRU5ErkJggg==
}]

set icons(info) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAAABGdBTUEAALGPC/xh
    BQAAAwBQTFRFAAAAtm8Av5hdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAGBwmfQAAAQB0Uk5T////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////AFP3ByUAAAAYdEVY
    dFNvZnR3YXJlAFBhaW50Lk5FVCB2My4zNqnn4iUAAABCSURBVChTY/iPBTAAxZhQ
    AFAAKIgqxsQEFUQ2gQhBRkawBlSVWAWhBqOoZCReO2UqgRaBHUqEj9DdiR52uMIT
    M+gB93X4+z79XAoAAAAASUVORK5CYII=
}]

set icons(toolbarsep) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAAAkAAAATCAYAAABC3CftAAAABGdBTUEAALGPC/xh
    BQAAABh0RVh0U29mdHdhcmUAUGFpbnQuTkVUIHYzLjA39c2BcAAAAEBJREFUKFNj
    YKAJuHb+2P/NG1b/f//6+X+cFmzesPh/b0fVfxDAqej58+dgBf9/41FElB9G3URU
    MDEMxnDC5XIAtLR9uTyVSNcAAAAASUVORK5CYII=
}]

set icons(recordeventlog) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAYAAACQjC21AAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAAJcEhZcwAACu8AAArvAX12ikgAAAAHdElNRQfXBREO
    KQ5KyqZbAAAAGHRFWHRTb2Z0d2FyZQBwYWludC5uZXQgNC4wLjb8jGPfAAABZElE
    QVQ4T62RMUvDUBSFn0MmIWQoZAkhdMr/yJIfkP+UoYsIWhxKUFBaeINdFFenDmLA
    bIK1gw4OKoL78b60L8nNS2tAh+/lnnPfPXDzBACDvZMB9g+HVJq932DiYJVBnAqI
    e+JBILgIkL/l1OJDu2DCu/EgbinsY41buIhlTC0+tIv1QR/HcWAdWRCvdaDz6UCM
    1j19ZxdVoCaYBeWqOjB6iRBOwvJiX5iQTxL21C7Dwq8QyVWCcT6mVn3neTbD5WAA
    ORxiNZ+znoIJRVbQw9CainSRklX3VMA5jTwSS2IaBEZoVfThTHi4UyMblq4LGfNH
    K4+uH9zFsWXhuxFIJkb01f0qsC+SVlSr6sD3KMIk5I9WFX1YSglp21SRpKDrJEE+
    5o9WFX0psqxcU7FI+aMpmPgPDMP3fWj6eFprmFC0h9pel25iGOqyZpvX7LUxjHZQ
    2+vSTQxjW6Cm2WtqDRN/B+IHDszTocamQccAAAAASUVORK5CYII=
}]

set icons(log) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAAAAXNSR0IArs4c6QAA
    AARnQU1BAACxjwv8YQUAAAMAUExURQAAAFV5pVV5plV5qVV6qVV7rFV8rFV9r1V9
    sFV/tGFxmmd4oGl5olWBuFWDvFWCvXaDnHmFnm6AqGuPvXOFrXuJoHyJoX+Mo3iK
    sX2RuHuZv1SFwFWFwVSGxFSIyFSJy1SLzlSM0IOQpoeUqYeVqouYrY6cr4CSuYWZ
    v4+csJGfsZGfspGgstnx/Oft+ebu+enw+e3y+vH1+/X3/PX4+/X4/Pj5/Pj5/fj6
    /Pj6/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAL4Gq1gAAAEAdFJOU///////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    /wBT9wclAAAACXBIWXMAAAsSAAALEgHS3X78AAAAGnRFWHRTb2Z0d2FyZQBQYWlu
    dC5ORVQgdjMuNS4xMDD0cqEAAACaSURBVChTlcpbG4FAFIVhFVGEDCI6iEi7mXGc
    +P8/LJ22XLjgW3fvs1rZl/5Ee9NkI/rjJh/RMylmeojujD6EEM9UpHMX0bFotJwO
    9Nv9ajmIq4Be6oI14mhHo+iwmPT183aIaIT0VBcaiNqecsY5Y4wfNcQuQAyQQJwA
    9BCJWtbJpxLEIqIo7QKKKiSyJEuSnFf6+/nZr5hlL+Rf7wVVTCVwAAAAAElFTkSu
    QmCC
}]

set icons(pkheader) [image create photo -data {
    iVBORw0KGgoAAAANSUhEUgAAABQAAAATCAMAAACnUt2HAAAABGdBTUEAALGPC/xh
    BQAAAwBQTFRFAAAAPT09TExMVlZWxsb/0//GxuD//+vG+//GAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA
    AAAAAAAAAAAAr3qoyAAAAQB0Uk5T////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////////////////////
    ////////////////////////////////////////////////AFP3ByUAAAAJcEhZ
    cwAADr8AAA6/ATgFUyQAAAAadEVYdFNvZnR3YXJlAFBhaW50Lk5FVCB2My41LjEw
    MPRyoQAAAEBJREFUKFOdzDkOACAIRFEBt/tfGFeMRAvxZapfjOMLWyRFYhwoVR9R
    kZhzm+/eI0rcrRg2YI/zDRGqGQ+vkbkAOMPIT2wFEbcAAAAASUVORK5CYII=
}]

