//
// Created: ${date} for project ${projectName}
//

package ${projectname};

<#if generateNodeTypeDecl>
module ${nodeType} {
    parameters:
        @display("i=abstract/router_s");
    gates:
        inout g[];
}
</#if>

<#if generateChannelTypeDecl>
channel ${channelType} extends ned.DatarateChannel {
    parameters:
        int cost = default(0);
}
</#if>

<#assign numNodes = numNodes?number>
<#assign numLinks = numLinks?number>
<#assign seed = seed?number>

<#assign Topogen = classes["org.example.Topogen"]>
<#assign topo = Topogen.create(numNodes, numLinks, seed)>
<#assign neighbourLists = topo.getNeighborLists()>

//
// Graph generated by Topogen (${numNodes} nodes, ${numLinks} edges, seed=${seed}).
//
// Edge list:
// <pre>
// ${topo.toString().trim().replace("\n", "\n// ")}
// </pre>
//
network ${networkName} {
    submodules:
<#list 0..neighbourLists.size()-1 as i>
        node${i} : ${nodeType};
</#list>
    connections:
<#list 0..neighbourLists.size()-1 as i>
  <#assign neighbourList = neighbourLists[i] >
  <#list neighbourList as neighbour>
        node${i}.g++ <--> ${channelType} <--> node${neighbour}.g++;
  </#list>    
</#list>
}
    