#! /bin/sh
#
# usage: runtest [<testfile>...]
# without args, runs all *.test files in the current directory
#

MODE=${MODE:-"debug"}
MAKEOPTIONS="MODE=$MODE"
MAKE=${MAKE:-"make"}
MAKEFLAGS=${MAKEFLAGS:-"-j$(nproc)"}

case "$MODE" in
  "release") PROGSUFFIX="" ;;
  "debug") PROGSUFFIX="d" ;;
  *) PROGSUFFIX="_$MODE" ;;
esac

TESTFILES=$*
if [ "x$TESTFILES" = "x" ]; then TESTFILES='*.test'; fi
if [ ! -d work ];  then mkdir work; fi
rm -rf work/lib
cp -pPR lib work/       # OSX dos not support cp -a
export NEDPATH=.:../lib
EXTRA_INCLUDES="-I../../../src/sim/parsim -I../../../src/envir -I../../../src/common -I../../../include/platdep"

opp_test -g $OPT -v $TESTFILES || exit 1
echo
(cd work; opp_makemake -f --deep --no-deep-includes $EXTRA_INCLUDES; $MAKE $MAKEOPTIONS) || exit 1
echo
opp_test -r $OPT -p work$PROGSUFFIX -v $TESTFILES || exit 1
echo
echo Results can be found in ./work

