#!/bin/sh
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:`dirname $0`/../queueinglib
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:`dirname $0`/../queueinglib
export PATH=$PATH:`dirname $0`/../queueinglib
opp_run -l`dirname $0`/queueinglibext $*

