<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model"
    nsURI="http://www.omnetpp.org/omnetpp/scave" nsPrefix="scave">
  <eClassifiers xsi:type="ecore:EClass" name="Dataset">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//DatasetItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="basedOn" eType="#//Dataset"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Chart" abstract="true" eSuperTypes="#//DatasetItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" upperBound="-1"
        eType="#//SelectDeselectOp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Add" eSuperTypes="#//AddDiscardOp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="excepts" upperBound="-1"
        eType="#//Except" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Discard" eSuperTypes="#//AddDiscardOp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="excepts" upperBound="-1"
        eType="#//Except" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProcessingOp" abstract="true" eSuperTypes="#//DatasetItem">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operation" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="filters" upperBound="-1"
        eType="#//SelectDeselectOp" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="params" upperBound="-1"
        eType="#//Param" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Except">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterPattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetOperation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceDataset" eType="#//Dataset"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterPattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//ResultType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatasetItem" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Group" eSuperTypes="#//DatasetItem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="items" upperBound="-1"
        eType="#//DatasetItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Param">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChartSheet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="charts" upperBound="-1"
        eType="#//Chart"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Analysis">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" eType="#//Inputs"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="datasets" eType="#//Datasets"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="chartSheets" eType="#//ChartSheets"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Select" eSuperTypes="#//SelectDeselectOp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="excepts" upperBound="-1"
        eType="#//Except" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Deselect" eSuperTypes="#//SelectDeselectOp">
    <eStructuralFeatures xsi:type="ecore:EReference" name="excepts" upperBound="-1"
        eType="#//Except" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AddDiscardOp" abstract="true" eSuperTypes="#//SetOperation #//DatasetItem"/>
  <eClassifiers xsi:type="ecore:EClass" name="SelectDeselectOp" abstract="true" eSuperTypes="#//SetOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="Inputs">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//InputFile" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputFile">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChartSheets">
    <eStructuralFeatures xsi:type="ecore:EReference" name="chartSheets" upperBound="-1"
        eType="#//ChartSheet" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Datasets">
    <eStructuralFeatures xsi:type="ecore:EReference" name="datasets" upperBound="-1"
        eType="#//Dataset" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ResultType">
    <eLiterals name="scalar" value="1" literal="SCALAR"/>
    <eLiterals name="vector" value="2" literal="VECTOR"/>
    <eLiterals name="histogram" value="3" literal="HISTOGRAM"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Apply" eSuperTypes="#//ProcessingOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="Compute" eSuperTypes="#//ProcessingOp"/>
  <eClassifiers xsi:type="ecore:EClass" name="BarChart" eSuperTypes="#//Chart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupBy" ordered="false"
        upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="groupNameFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="barNameFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="barFields" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LineChart" eSuperTypes="#//Chart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineNameFormat" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HistogramChart" eSuperTypes="#//Chart"/>
  <eClassifiers xsi:type="ecore:EClass" name="ScatterChart" eSuperTypes="#//Chart">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xDataModule" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="xDataName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="averageReplications" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true"/>
  </eClassifiers>
</ecore:EPackage>
