
//
// @titlepage
// <h1>opp_neddoc test files</h1>
//
// This page was created with the @titlepage directive and should appear
// as the starting page if the document.
//
// It contains links to other pages, such as
// <a href="playground.html">playground</a>, and
// <a href="foo.html">foo</a>.
//
//#---------------------------------------------------------------------
// @page playground.html, HTML playground page...
//
// <font size=4>H<sup>T</sup>M<sub>L</sub></font>
//
//#---------------------------------------------------------------------
// @externalpage ext-one.html
// @externalpage ext-two.html, ext-two, the second external page
//#---------------------------------------------------------------------
// @page noname.html
//
// This is a page without title. Of course you can still put a title
// manually, e.g. using the <nohtml><h2>..</h2></nohtml> construct
// like this:
//
// <h2>Unnamed page</h2>
//
// but it's really better to define a title in the @ page directive.
//
//#---------------------------------------------------------------------
// @page foo.html, This is another page
//
// Whatever...
//#---------------------------------------------------------------------
// @externalpage x-two.html, second external page
//