//
// @titlepage
// <h1>opp_neddoc test files</h1>
//
// This page was created with the @titlepage directive and should appear
// as the starting page if the document.
//
// It contains links to other pages, such as
// <a href="playground.html">playground</a>, and
// <a href="foo.html">foo</a>.
//
//#---------------------------------------------------------------------
// @page nasty-!@#$%^&*()[]{}"':;.\L<?>/+=-`ßéáíöüóú, Nasty Filename
// @-page nasty-!@#$%^&*()[]{}"':;.\L<?>/+=-`ßéáíöüóú, Nasty Filename
//
// This is a page with a file name that contains nasty characters.
//
//#---------------------------------------------------------------------
// @externalpage ext-one.html
// @externalpage ext-two.html, ext-two, the second external page
//

package org.omnetpp.neddoc;

