#!/bin/sh
if [ -n "$1" ] ; then
  echo Please change to the directory you want to convert and run the script there without any comnmand line argument!
  exit 1
fi

echo
echo Press ENTER to convert all NED files under the current directory:
echo `pwd`
echo
read WAIT

find . -name "*.ned" >nedfiles.lst

echo The following files will be checked/modified:
cat nedfiles.lst | less

echo
echo Press ENTER to start the conversion, or CTRL-C to quit.
read WAIT

nedtool -P @nedfiles.lst || exit 1

echo <<__END__
NED files has been converted.

Since there were semantic changes in the NED language, there are details
that could not be converted automatically. Please revise the following:

 1. Adjust "import" directives. Previously they pointed to files, now
    they refer to module types.

 2. Remove "volatile" qualifiers from parameters that are only read
    from the C++ code once, at the beginning of the simulation.

 3. Old "numeric" parameters have been converted to "double", but
    you may want to change some of those to "int".

 4. Remove unnecessary networks definitions. Compound modules can now be
    used as networks directly, by changing the "module" keyword to
    "network".

 5. Additionally, you can change the files to take advantage of new NED
    features: module default icons, parameter physical units, inout gates
    and bidirectional connections, inheritance, inner types, and so on.

You may safely re-run this script any time you want.
__END__

