both in parameter value and connections part
index - index of module in parent's vector
sizeof - gate/submodule vector, own or another submodule's
this - submodule's parameter (by default parameter names refer to parent's p..)
variable reference either refers to a cycle variable or a compound module parameter
connections may refer to submodule parameters (submodname.paramname)

like might be an expression and may come from ini file
<> may be specified by *.typename = in the ini file
