#! /bin/sh
# single-process multi-theaded parallel simulation with named pipe communication
mkdir -p comm
if [ -x ../cqn ]; then CQN=../cqn; else CQN=../cqn_dbg; fi
$CQN -n.. -u Cmdenv --parallel-simulation=true --parsim-mode=multithreaded --parsim-communications-class=cNamedPipeCommunications  -c LargeLookahead omnetpp.ini partitioning.ini $*

