#! /bin/sh
echo
echo '*** Distributed execution of the Closed Queueing Network ***'
echo 'IMPORTANT: If you'"'"'re running CQN under the GUI, you'"'"'ll have to click [Run]'
echo 'in all three windows to start the simulation. See Readme.txt for more info.'
echo

rm -rf comm
mkdir comm
mkdir comm/read

# make sure HOSTNAME is exported as some distros no longer export it by default
if test "$HOSTNAME" = ""; then
  export HOSTNAME=`hostname`
fi

export NEDPATH=..
../cqn -p0,3 $* > cqn-0.log &
../cqn -p1,3 $* > cqn-1.log &
../cqn -p2,3 $* > cqn-2.log &
