#!/bin/sh
# Builds the IDE native support library. BUILD_{PLATFORM}_DISTRO must be set to "yes" to build a specific platform

cd $(dirname $0)/../../..
export PATH=$HOME/omnetpp/bin:$PATH

if [ "$BUILD_LINUX_X86_64_DISTRO" = "true" ]; then
  # build Linux x86_64
  echo Building Linux x86_64 binaries
  cp releng/ide/native/Makefile.inc.linux.x86_64 Makefile.inc
  make cleanall || { echo --- error during cleaning native Linux x86_64 IDE parts ---; exit 1;}
  make SHARED_LIBS=no MODE=release ui -j$(nproc) || { echo --- error during compiling native Linux x86_64 IDE parts ---; exit 1;}
fi

if [ "$BUILD_WIN32_X86_64_DISTRO" = "true" ]; then
  # Build MS Windows
  echo Building Windows x86_64 binaries
  cp releng/ide/native/Makefile.inc.win32.x86_64 Makefile.inc
  make cleanall || { echo --- error during cleaning native Windows x86_64 IDE parts ---; exit 1;}
  make SHARED_LIBS=no MODE=release ui -j$(nproc) || { echo --- error during compiling native Windows x86_64 IDE parts ---; exit 1;}
fi

if [ "$BUILD_MACOSX_DISTRO" = "true" ]; then
 if which x86_64-apple-darwin20.4-clang++-libc++ ; then
  echo Building x86_64 macOS binaries using a cross compiler
  cp releng/ide/native/Makefile.inc.macosx Makefile.inc
  export MACOSX_DEPLOYMENT_TARGET=10.10
  make cleanall || { echo --- error during cleaning native macOS IDE parts ---; exit 1;}
  make SHARED_LIBS=no MODE=release ui -j$(nproc) || { echo --- error during compiling native macOS IDE parts ---; exit 1;}
 else
  echo macOS cross compiler is not available
  exit 1
 fi
fi

echo IDE native library build finished.