: generated by the ExportNotesText() macro in figures.ppt
cd figures
rename Slide2.* partitioning.*
rename Slide3.* perfbar-screenshot.*
rename Slide4.* sydney-melbourne.*
rename Slide5.* nonblocking-crit.*
rename Slide6.* pairwise.*
rename Slide7.* cqn-model.*
rename Slide8.* cqn-partitioning.*
rename Slide9.* cqn-screenshot1.*
rename Slide10.* cqn-screenshot2.*
rename Slide11.* parsim-screenshot.*
rename Slide12.* placeholders.*
rename Slide13.* placeholders2.*
rename Slide14.* parsim-arch.*
rename Slide15.* usmanFig1.*
rename Slide16.* usmanFig2.*
rename Slide17.* usmanFig3.*
rename Slide18.* usmanFig4.*
rename Slide19.* usmanFig5.*
rename Slide20.* usmanFig6.*
rename Slide21.* usmanFig7.*
rename Slide22.* usmanFig8.*
rename Slide23.* usmanFig9.*
rename Slide24.* usmanFig10.*
rename Slide25.* usmanFig11.*
rename Slide26.* usmanFig12.*
rename Slide27.* usmanFig13.*
rename Slide28.* usmanFig14.*
rename Slide29.* usmanFig15.*
rename Slide30.* usmanFig16.*
rename Slide31.* usmanFig17.*
rename Slide32.* usmanFig18.*

