//-------------------------------------------------------------
// file: $$MODULE_NAME$$.ned
//-------------------------------------------------------------


// $$MODULE_NAME$$ --
//
// $$DESCRIPTION$$
//
simple $$MODULE_NAME$$
    parameters:
        // example parameters
        first_param: string,
        second_param: numeric;
    gates:
        // example gates
        in:  in1,
             in2;
        out: out1,
             out2;
endsimple
