#!/bin/sh

if [ "$what" != "omnest" ]; then
  # if "what" is not "omnest" we build omnetpp by default
  export what=omnetpp
fi

if [ "$BUILDID"x = "x" ]; then
  # generate our own build identifier
  export BUILDID=`date +%y%m%d`-`git describe --tags | awk -F '-g' '{print $2;}'`
fi
if [ "$VERSION"x = "x" ]; then
  # undefined version number
  export VERSION=unknown
fi

cd `dirname $0`/../../..

echo Copying 'ui' to 'out/ui' ...
rm -rf out/ui
mkdir -p out
cp -r ui out

echo Building $what IDE version: $VERSION with buildID: $BUILDID
cd out/ui
mvn clean verify -Dwhat=$what -DforceContextQualifier=$BUILDID || { echo --- error during compiling/packaging Java IDE parts ---; exit 1;}

# post process the final layout. Merge the plugins and features directory of all platforms to save space
cd releng/org.omnetpp.ide.product/target/products/org.$what.ide.product || { echo --- error changing to the final result directory ---; exit 1;}

echo Post processing IDE installation files...
rm -rf ide
mkdir -p ide

cp -rl linux/gtk/x86 ide
mv ide/x86 ide/linux32
cp -rlf ide/linux32/plugins ide
cp -rlf ide/linux32/features ide
rm -rf ide/linux32/plugins
rm -rf ide/linux32/features

cp -rl linux/gtk/x86_64 ide
mv ide/x86_64 ide/linux64
cp -rlf ide/linux64/plugins ide
cp -rlf ide/linux64/features ide
rm -rf ide/linux64/plugins
rm -rf ide/linux64/features

cp -rl win32/win32/x86 ide
mv ide/x86 ide/win32
cp -rlf ide/win32/plugins ide
cp -rlf ide/win32/features ide
rm -rf ide/win32/plugins
rm -rf ide/win32/features

cp -rl macosx/cocoa/x86_64 ide
mv ide/x86_64 ide/macosx
cp -rlf ide/macosx/Eclipse.app/Contents/Eclipse/plugins ide
cp -rlf ide/macosx/Eclipse.app/Contents/Eclipse/features ide
rm -rf ide/macosx/Eclipse.app/Contents/Eclipse/plugins
rm -rf ide/macosx/Eclipse.app/Contents/Eclipse/features
