#! /bin/sh

# make sure HOSTNAME is exported as some distros no longer export it by default
if test "$HOSTNAME" = ""; then
  export HOSTNAME=`hostname`
fi

mpiexec -n 3 ../routing -n .. -c Net10-parsim -u Cmdenv --parsim-communications-class=cMPICommunications --parsim-num-partitions=3
