#
# Definitions to be customized by configure
#

include ../../Makefile.inc

#
# Targets
#
all: 
	chmod +x opp_msgc
	cp opp_msgc $(OMNETPP_BIN_DIR)

depend:

clean:

# DO NOT DELETE THIS LINE -- make depend depends on it.
