#
# Global definitions
#
!include ..\..\configuser.vc

#
# Targets
#
all:
	copy opp_msgc $(OMNETPP_BIN_DIR:/=\)
	copy opp_msgc.cmd $(OMNETPP_BIN_DIR:/=\)

depend:

clean:

# DO NOT DELETE THIS LINE -- make depend depends on it.
