# Makefile to translate tutorial document to ps, pdf.

SOURCE = tutorial

default: pdf

pdf: latex
	pdflatex $(SOURCE).tex 

ps: latex
	dvips $(SOURCE).dvi -o $(SOURCE).ps

html: latex
	latex2html -split 1 $(SOURCE)

latex: 
	latex $(SOURCE).tex
	latex $(SOURCE).tex

clean: 
	-del $(SOURCE).aux
	-del $(SOURCE).dvi
	-del $(SOURCE).log
	-del $(SOURCE).toc

cleanall: clean
	-del $(SOURCE).pdf
	-del $(SOURCE).ps
	-del $(SOURCE)

