#!/bin/sh

# variables used by the build script
export what=omnetpp
export BUILD_CORE_DISTRO=true
export BUILD_LINUX_X86_64_DISTRO=true
export BUILD_WIN32_X86_64_DISTRO=true
export BUILD_MACOSX_DISTRO=true
export BUILD_DOC=true
export GIT_VERSION=$(git rev-parse HEAD)

. $(dirname $0)/docker-build.sh
