#!/bin/sh

OMNETPP_ROOT="/home/andras/omnetpp"
RELEASE_NUMBER="0.60b"

dir=$OMNETPP_ROOT
staticlibs=yes

# Warning
cat <<END

You MUST have a FRESHLY installed OMNeT++ in $dir!
(Created by install.bat from DOS or DOSEMU)

If you do not have it, press ^C now!
END
read

# directory exists?
if [ ! -d $dir ]; then
        echo "$0: no $dir directory!"
        exit
fi

cd $dir

#
# DO THE ZIP VERSION
#

# Some cleaning
rm -r arj
rm -r gnu
rm -r stuff
rm -f `find . -name "*_n.cc" -print`
rm -f `find . -name "*.bak" -print`

# make bin/ and lib/
mkdir bin
mkdir lib

# Create catalog file
#echo "OMNeT++ version $RELEASE_NUMBER" > doc/package
#echo ""
echo "distribution contents:" > doc/package
echo "~~~~~~~~~~~~~~~~~~~~~" >> doc/package
cat `find $dir -name version -print` >> doc/package

# convert text files to Unix format
chmod 755 ./src/utils/all2unix
./src/utils/all2unix

# Update makefiles for models
for i in models/*
do
   (cd $i; ../../src/utils/makemake -f -n; mv makefile makefile.in)
done

# Update makefiles for sample simulations
for i in samples/*
do
   (cd $i; ../../src/utils/makemake -f; mv makefile makefile.in)
done

# Copy some files to installation root directory
cp src/utils/makeall.bat .
cp doc/readme* .

# Create DOS zip file
zip -r ../omnetpp.zip *

#
# NOW DO THE TGZ VERSION
#

# Copy some files to installation root directory
(cd src/utils; mv configur configure)
(cd doc; mv readme.unx readme.unix)
rm * 2>/dev/null
ln -s src/utils/configure .
ln -s src/utils/makeall .
ln -s src/utils/makeall.bat .
ln -s doc/readme* .

# Create a ./bin directory
cd bin
ln -s ../src/nedc/nedc .
ln -s ../src/gned/gned .
ln -s ../src/plove/plove .
ln -s ../src/utils/seedtool .
ln -s ../src/utils/makemake .
ln -s ../src/utils/splitvec .
cd ..

# Create a ./lib directory
cd lib
if [ "$staticlibs" = "yes" ]; then
   ln -s ../src/sim/libsim_std.a .
   ln -s ../src/sim/libsim_pvm.a .
   ln -s ../src/envir/libenvir.a .
   ln -s ../src/envir/cmdenv/libcmdenv.a .
   ln -s ../src/envir/tkenv/libtkenv.a .
   ln -s ../src/envir/tvenv/libtvenv.a .
else
   ln -s ../src/sim/libsim_std.so .
   ln -s ../src/sim/libsim_pvm.so .
   ln -s ../src/envir/libenvir.so .
   ln -s ../src/envir/cmdenv/libcmdenv.so .
   ln -s ../src/envir/tkenv/libtkenv.so .
   ln -s ../src/envir/tvenv/libtvenv.so .
fi
cd ..

# Create tgz
(cd ..; tar cvfz omnetpp.tgz omnetpp)

