#!/bin/sh
#
# Detects the platform and architecture, and starts the IDE with the right launcher
#
IDEDIR=`dirname $0`/../ide
PLATFORM=`uname -sm`
LAUNCHER=omnetpp

echo Starting the OMNeT++ IDE...

if java -version 2>&1 | grep -i "libgcj" >/dev/null 2>/dev/null; then
  echo "A compatible JRE is required to run the IDE. "
  echo "Found GNU GIJ which is not supported. Please use Oracle JRE or Open JRE 1.7+"
  echo "If you have several JDKs installed on you machine, change the default JVM."
  echo "You can switch between Java VMs with the 'sudo update-alternatives --config java' command."
  exit 1;
fi

if test ! -d $IDEDIR/configuration; then
  echo "The IDE is not yet configured. Please run the 'configure' script in the installation root folder!"
  exit 1;
fi

#set default language so GCC will report errors in english. see bug #3
export LANG=en_US.UTF-8
# workaround for KDE bug: https://bugs.kde.org/show_bug.cgi?id=316012
export OXYGEN_DISABLE_INNER_SHADOWS_HACK=1
# workaround for bug: https://bugs.eclipse.org/bugs/show_bug.cgi?id=419830
export UBUNTU_MENUPROXY=0
# arguments needed to initially correctly show  the default 'samples' workspace
DEFAULT_WORKSPACE_ARGS="-vmargs -Dosgi.instance.area.default=$IDEDIR/../samples"

case $PLATFORM in
*MINGW*)
	$IDEDIR/${LAUNCHER}.exe $* $DEFAULT_WORKSPACE_ARGS 2>$IDEDIR/error.log &
        ;;
*Linux*)
	$IDEDIR/${LAUNCHER} $* $DEFAULT_WORKSPACE_ARGS 2>$IDEDIR/error.log &
        ;;
*Darwin*)
	open -a $IDEDIR/${LAUNCHER}.app --args $* $DEFAULT_WORKSPACE_ARGS 2>$IDEDIR/error.log
        ;;
*)
	echo OMNeT++ IDE is supported only on: Linux, Windows and MacOS X
	exit 1
        ;;
esac
