eval '(exit $?0)' && eval 'exec perl -S $0 ${1+"$@"}' && eval 'exec perl -S $0 $argv:q'
  if 0;

#!perl
#line 6

#-----------
# to be configured:
$NEDTOOL = "d:\\home\\omnetpp\\bin\\nedtool.exe";
$XSLTPROC = "d:\\home\\tools\\libxslt-1.0.27.win32\\util\\xsltproc.exe";
$GNED = "d:\\home\\omnetpp\\bin\\gned.exe";
$GHOSTSCRIPT = "d:\\home\\tools\\gs\\gs8.11\\bin\\gswin32c.exe";
$GIFTRANS = "";
$DOT = "d:\\home\\tools\\Graphviz\\bin\\dot.exe";
$PERL = "perl";
#-----------

use Cwd;

$progdir = $0;
$progdir =~ s|/|\\|g;
$progdir =~ s|[^\\:]*$|\\|g;
$progdir = "." if ($progdir eq "");

# assume the stylesheet and the postprocessor are in the same directory as we
$NEDDOC_XSL = "$progdir\\neddoc.xsl";
$NEDDOC_PL = "$progdir\\neddocproc.pl";

# process command-line options
$outdir = "html";
$doxytagfile = "";
$doxyhtmldir = "../api-doc/html";
$screenshots = 1;
$unassignedpars = 1;
$all_files = 0;
$verbose = 1;
$debug = 0;

if ($DOT ne "")
{
    $have_dot = "y";
}

# process arg vector
while (@ARGV)
{
    $arg = $ARGV[0];
    if ($arg eq '-o')
    {
       shift @ARGV;
       $outdir = $ARGV[0];
       $outdir =~ s|/|\\|g;
    }
    elsif ($arg eq '-a' || $arg eq '--all')
    {
       $all_files = 1;
    }
    elsif ($arg eq '-d' || $arg eq '--doxyhtmldir')
    {
       shift @ARGV;
       $doxyhtmldir = $ARGV[0];
       $doxyhtmldir =~ s|/|\\|g;
    }
    elsif ($arg eq '-t' || $arg eq '--doxytagfile')
    {
       shift @ARGV;
       $doxytagfile = $ARGV[0];
       $doxytagfile =~ s|/|\\|g;
    }
    elsif ($arg eq '-n' || $arg eq '--no-figures')
    {
       $screenshots = 0;
    }
    elsif ($arg eq '-p' || $arg eq '--no-unassigned-pars')
    {
       $unassignedpars = 0;
    }
    elsif ($arg eq '-x' || $arg eq '--no-diagrams')
    {
       $have_dot = 1;
    }
    elsif ($arg eq '-D' || $arg eq '--debug')
    {
       $debug = 1;
    }
    elsif ($arg eq '-s' || $arg eq '--silent')
    {
       $verbose = 0;
    }
    elsif ($arg eq '-h' || $arg eq '--help')
    {
       $do_help = 1;
    }
    elsif ($arg =~ /^-/)
    {
       print STDERR "opp_neddoc: $arg: invalid option, try -h for help\n";
       exit(2);
    }
    else
    {
       last;
    }
    shift @ARGV;
}

if ($do_help)
{
    print "opp_neddoc - NED and MSG documentation tool, part of OMNeT++\n";
    print "(c) 2003 Andras Varga\n";
    print "\n";
    if ($GHOSTSCRIPT eq "")
    {
        print "Note: cannot generate figures because Ghostscript is not installed.\n";
        print "\n";
    }
    if ($DOT eq "")
    {
        print "Note: cannot generate usage diagrams because Graphviz is not installed.\n";
        print "\n";
    }
    print "Usage: opp_neddoc [-o <dir>] [-n] [-a] files-or-directories ...\n";
    print " -s, --silent do not print what it is doing\n";
    print " -D, --debug  print invocations of external programs and other info\n";
    print " -a, --all    process all *.ned and *.msg files recursively\n";
    print "              ('opp_neddoc -a' is equivalent to 'opp_neddoc .')\n";
    print " -o <dir>     output directory, defaults to ./html\n";
    print " -t <filename>, --doxytagfile <filename>\n";
    print "              turn on generating hyperlinks to Doxygen documentation;\n";
    print "              <filename> specifies name of XML tag file generated by Doxygen\n";
    print " -d <dir>, --doxyhtmldir <dir>\n";
    print "              directory of Doxygen-generated HTML files, relative to the \n";
    print "              opp_neddoc output directory (-o option). -t option must also be\n";
    print "              present to turn on linking to Doxygen. Default: ../api-doc/html\n";
    print " -n, --no-figures\n";
    print "              do not generate diagrams\n";
    print " -p, --no-unassigned-pars\n";
    print "              do not document unassigned parameters\n";
    print " -x, --no-diagrams\n";
    print "              do not generate usage and inheritance diagrams\n";
    print " -h, --help   displays this help text\n";
    print "Files specified as arguments are parsed and documented. If directories\n";
    print "are specified, all *.ned and *.msg files in them are documented.\n";
    print "\n";
    exit(0);
}

# we need backslashes in file names
$NEDTOOL =~ s|/|\\|g;
$XSLTPROC =~ s|/|\\|g;
$GNED =~ s|/|\\|g;
$GHOSTSCRIPT =~ s|/|\\|g;
$GIFTRANS =~ s|/|\\|g;
$DOT =~ s|/|\\|g;
$PERL =~ s|/|\\|g;
$NEDDOC_XSL =~ s|/|\\|g;
$NEDDOC_PL =~ s|/|\\|g;


# OS check
if ($ENV{"OS"} ne "Windows_NT")
{
    error("this program can only be used on Windows NT/2000/XP, but your OS environment variable says '$ENV{OS}'\n");
}

if (! -d $outdir)
{
    print "creating directory $outdir\n" if $debug;
    mkdir($outdir) || error("cannot create output directory '$outdir'");
}
else
{
   runprog("del /s /q $outdir\\* >nul")==0 || error("cannot clean output directory '$outdir' from old files");
}
print "collecting files...\n" if $verbose;
if ($all_files eq "")
{
    runprog("dir /s /b *.ned *.msg >$outdir\\filelist.txt")==0 || error("error creating the file list");
}
else
{
    if (@ARGV==())
    {
        print STDERR "opp_neddoc: no input files specified, type -h for help\n";
        exit(2);
    }

    while (@ARGV)
    {
        $arg = shift @ARGV;
        $arg =~ s|/|\\|g;
        if (-d "$arg")
        {
            runprog("dir /s /b $arg\\*.ned $arg\\*.msg >>$outdir\\filelist.txt")==0 || error("error creating the file list");
        }
        else
        {
            runprog("echo $arg >>$outdir\\filelist.txt")==0 || error("error creating the file list");
        }
        shift;
    }
}

# make file names in filelist.txt relative to current directory; also weed out
# file names not ending in .ned or .msg (i.e. backup files ending in .ned~0)
$currentdir = cwd();
$currentdir =~ s|/|\\|g;
rename("$outdir\\filelist.txt", "$outdir\\filelist.tmp");
open FLIN, "$outdir\\filelist.tmp";
open FLOUT, ">$outdir\\filelist.txt";
while (<FLIN>)
{
    next if (!/.ned$/ && !/.msg$/);
    s|^\Q$currentdir\E\\*||;
    print FLOUT;
}
close FLOUT;
close FLIN;
unlink("$outdir\\filelist.tmp");

#
# now start the real job
#
print "transforming to xml...\n" if $verbose;
runprog("$NEDTOOL -x -e -t -y -m -o $outdir\\inputfiles.xml \@$outdir\\filelist.txt")==0 || error("error");

if ($screenshots)
{
    if ($GHOSTSCRIPT ne "")
    {
        print "exporting screenshots in Postscript using GNED...\n";
        $nedfilesonly = `type $outdir\\filelist.txt`;
        #runprog("$GNED >nul -- -c $outdir -e jpg $nedfilesonly")==0 || error("error invoking GNED");
        runprog("$GNED -- -c $outdir -e jpg \@$outdir\\filelist.txt >nul")==0 || error("error invoking GNED");
        print "converting Postscript to JPG with Ghostscript...\n";
        foreach $i (glob("$outdir/*.eps"))
        {
           print "#";
           $jpg = $i;
           $jpg =~ s/eps$/jpg/;
           runprog("$GHOSTSCRIPT -dEPSCrop -sNOPAUSE -sBATCH -sDEVICE=jpeg -sOutputFile=$jpg $i >>$outdir\\gs.err")==0 || error("error invoking Ghostscript");
        }
        print "\n";

        if (-s "$outdir\\gs.err")
        {
           print "see Ghostscript warnings in $outdir\\gs.err\n";
        }

        # hack: must convert $outdir to absolute path, otherwise xslt will take it
        # as relative to the sylesheet (@#$#@$!!)
        $imagesxml = absolutepath("$outdir\\images.xml");
    }
    else
    {
        print "skipping diagram exporting (no Postscript-to-JPG converter configured)";
        $imagesxml = "";
    }
}

# hack: must convert $doxytagfile to absolute path, otherwise xslt will take it
# as relative to the sylesheet
if ($doxytagfile ne "") {
    $doxytagfile = absolutepath($doxytagfile);
}

print "applying XSLT stylesheet...\n" if $verbose;
$xsltcommand = "$XSLTPROC".
               " --stringparam outputdir \"".toslash($outdir)."\"".
               " --stringparam imagesxml \"".toslash($imagesxml)."\"".
               " --stringparam document-unassigned-params \"$unassignedpars\"".
               " --stringparam have_dot \"$have_dot\"".
               " --stringparam doxytagfile \"".toslash($doxytagfile)."\"".
               " --stringparam doxyhtmldir \"".toslash($doxyhtmldir)."\"".
               " --output nul".
               " $NEDDOC_XSL $outdir\\inputfiles.xml";
runprog($xsltcommand)==0 || error("error invoking xsltproc");

if ($have_dot)
{
    print "generating diagrams via DOT...\n";
    foreach $i (glob("$outdir/*.dot"))
    {
       print "#";
       $gif = $i; $gif =~ s/dot$/gif/;
       $map = $i; $map =~ s/dot$/map/;
       runprog("$DOT -Tgif  <$i >$gif 2>>$outdir\\dot.err")==0 || error("error invoking DOT");
       runprog("$DOT -Tcmap <$i >$map 2>>$outdir\\dot.err")==0 || error("error invoking DOT");
       if ($GIFTRANS ne "")
       {
           rename($gif, "$gif.tmp");
           runprog("$GIFTRANS -t white $gif.tmp >$gif")==0 || error("error invoking giftrans");
           unlink("$gif.tmp");
       }
    }
    print "\n";
    if (-s "$outdir\\dot.err")
    {
       print "see warnings from $DOT in $outdir\\dot.err\n";
    }
}

print "formatting comments...\n" if $verbose;
runprog("$PERL $NEDDOC_PL $outdir")==0 || error("error invoking HTML formatter");

if (!$debug)
{
    unlink(glob("$outdir/*.eps"));
    unlink(glob("$outdir/*.dot"));
    unlink(glob("$outdir/*.map"));
    unlink("$outdir/inputfiles.xml");
    unlink("$outdir/images.xml");
    unlink("$outdir/filelist.txt");
}
else
{
    print "debug mode -- leaving intermediate files in $outdir/\n";
}

print "documentation created in $outdir/ -- start page is index.html\n" if $verbose;


sub runprog
{
    my $prog = shift;
    print "running: $prog\n" if $debug;
    system($prog);
}

sub absolutepath
{
    my $filename = shift;
    $absfilename = `dir /s /b $filename`;
    chomp($absfilename);
    if ($absfilename eq "") {error("'$filename' does not exist");}
    $absfilename;
}

sub error
{
    my $msg = shift;
    print STDERR "opp_neddoc: ", $msg, "\n";
    exit(2);
}

sub tobackslash
{
    my $f = shift;
    $f =~ s|/|\\|g;
    $f;
}

sub toslash
{
    my $f = shift;
    $f =~ s|\\|/|g;
    $f;
}

