#!/usr/bin/env python
# This script manipulates omnetpp project features.
#

from __future__ import print_function
import argparse
import csv
import os
import sys
import re
import types
import xml.dom.minidom

def queryYesNo(question, default="yes"):
    """Ask a yes/no question via raw_input() and return their answer.

    "question" is a string that is presented to the user.
    "default" is the presumed answer if the user just hits <Enter>.
        It must be "yes" (the default), "no" or None (meaning
        an answer is required of the user).

    The "answer" return value is True for "yes" or False for "no".
    """
    valid = {"yes": True, "y": True, "ye": True,
             "no": False, "n": False}
    if default is None:
        prompt = " [y/n] "
    elif default == "yes":
        prompt = " [Y/n] "
    elif default == "no":
        prompt = " [y/N] "
    else:
        raise ValueError("invalid default answer: '%s'" % default)

    while True:
        sys.stdout.write(question + prompt)
        choice = raw_input().lower()
        if default is not None and choice == '':
            return valid[default]
        elif choice in valid:
            return valid[choice]
        else:
            sys.stdout.write("Please respond with 'yes' or 'no' "
                             "(or 'y' or 'n').\n")

############################
class OppError(Exception):
    def __init__(self, value):
        self.value = value

    def __str__(self):
        return repr(self.value)

############################
class Feature:
    def __init__(self, feature, ord):
        self.id = feature.getAttribute("id")
        self.name = feature.getAttribute("name")
        self.description = feature.getAttribute("description")
        self.initiallyEnabled = True
        if feature.hasAttribute("initiallyEnabled"):
            self.initiallyEnabled = feature.getAttribute("initiallyEnabled") == 'true'
        self.requires = feature.getAttribute("requires").split()
        self.labels = feature.getAttribute("labels").split()
        self.nedPackages = feature.getAttribute("nedPackages").split()
        self.extraSourceFolders = feature.getAttribute("extraSourceFolders").split()
        self.compileFlags = feature.getAttribute("compileFlags").split()
        self.linkerFlags = feature.getAttribute("linkerFlags").split()
        self.ord = ord

############################
class FeatureState:
    def __init__(self, id, enabled, ord):
        self.id = id
        self.enabled = enabled
        self.ord = ord

    @classmethod
    def fromXML(cls, xmlelement, ord):
        return cls(xmlelement.getAttribute("id"), xmlelement.getAttribute("enabled").lower() == 'true', ord)

    def __repr__(self):
        return "<%s: id=%s, enabled=%s, ord=%d)" % (self.__class__.__name__, self.id, self.enabled, self.ord)

############################
class NedFolder:
    def __init__(self, name, path, prefix, ord):
        self.name = name
        self.path = path
        self.prefix = prefix
        self.ord = ord

    def isSubpackage(self, subpkg):
        if self.prefix == '':
             return True
        return subpkg.startswith(self.prefix) and (len(subpkg) == len(self.prefix) or subpkg[len(self.prefix)] == '.')

    def __repr__(self):
        return "<%s: name=%s, path=%s, prefix=%s, ord=%d>" % (self.__class__.__name__, self.name, self.path, self.prefix, self.ord)

############################
class FeatureTool:
    def __init__(self):
        self.fixingMode = False
        self.autoFixingMode = False
        self.errorOccured = False
        self.fsChanged = False
        self.nedExclusionFileChanged = False
        self.nedfolders = []
        self.nedfoldersExcluded = []
        self.cppSourceRoots = []

    def createParser(self):
        self.parser = argparse.ArgumentParser()
        subparsers = self.parser.add_subparsers(help='', dest='command', metavar='COMMAND')

        # list command
        list_parser = subparsers.add_parser('list', help='List features')
        list_group = list_parser.add_mutually_exclusive_group()
        list_group.add_argument('-a', '--all', action='store_true',
                    default=False,
                    help='List all features (default)',
                    )
        list_group.add_argument('-e', '--enabled', action='store_true',
                    default=False,
                    help='List enabled features',
                    )
        list_group.add_argument('-d', '--disabled', action='store_true',
                    default=False,
                    help='List disabled features',
                    )
        list_group.add_argument('-x', '--diff', action='store_true',
                    default=False,
                    help='List features not in default state',
                    )

        # validate command
        validate_parser = subparsers.add_parser('validate', help='Validate feature states: Report inconsistencies and dependency problems in the FEATURESTATEFILE and NEDEXCLUSIONS file.')

        # reset command
        reset_parser = subparsers.add_parser('reset', help='Reset all feature enablements to their default')

        # repair command
        repair_parser = subparsers.add_parser('repair', help='Repair feature states: missing features are added to the state file with the initiallyEnabled flag, non-existent features are removed from the FEATURESTATEFILE')

        # enable command
        enable_parser = subparsers.add_parser('enable', help='Enable the specified features')
        enable_parser.add_argument('features', nargs='+',
                    help='Enable the specified features, use \'all\' for all features',
                    )
        enable_parser.add_argument('--with-dependencies', action='store_true',
                    default=False,
                    help='Enable all required features automatically',
                    )

        # disable command
        disable_parser = subparsers.add_parser('disable', help='Disable the specified features')
        disable_parser.add_argument('features', nargs='+',
                    help='Disable the specified features, use \'all\' for all features',
                    )
        disable_parser.add_argument('--with-dependencies', action='store_true',
                    default=False,
                    help='Disable all dependent features automatically',
                    )

        # print command:
        print_parser = subparsers.add_parser('makemakeargs', help='Print opp_makemake command line arguments for the current feature state')
        print_parser.add_argument('-s', '--srcpath',
                    help='Selects the source folder to print makemake options for. (The default is the first value in the cppSourceRoots attribute of the <features> tag in the FEATUREFILE.)',
                    )

        # common arguments:
        self.parser.add_argument('--featurefile', help='path/to/feature_file', default='./.oppfeatures', type=argparse.FileType('r'))
        self.parser.add_argument('--featurestatefile', help='path/to/feature_state_file', default='./.oppfeaturestate')
        self.parser.add_argument('--nedfoldersfile', help='path/to/nedfolders_file', default='./.nedfolders', type=argparse.FileType('r'))
        self.parser.add_argument('--nedexclusionsfile', help='path/to/nedexclusions_file', default='./.nedexclusions')

    ############################
    def doResetCommand(self):
        # RESET command #
        print("All features were set to their default state")
        self.featurestate = dict()
        for fk, feature in self.sortedFeatures:
            fs = FeatureState(feature.id, feature.initiallyEnabled, feature.ord)
            self.featurestate[fk] = fs
        self.writeFeatureState()

        self.nedfoldersExcluded = []
        for fk, feature in self.sortedFeatures:
            if not feature.initiallyEnabled:
                self.nedfoldersExcluded.extend(feature.nedPackages)

        self.writeNedExclusions()
        sys.exit(0)


    ############################
    def readFeatures(self):
        # read features xml file
        try:
            DOMTree = xml.dom.minidom.parse(self.args.featurefile)
            featuresDom = DOMTree.documentElement
            self.cppSourceRoots = featuresDom.getAttribute("cppSourceRoots").split()
            featurelistDom = featuresDom.getElementsByTagName("feature")

            self.features = dict()
            ord = 0
            for featureDom in featurelistDom:
                feature = Feature(featureDom, ord)
                self.features[feature.id] = feature
                ord += 1
        except Exception as e:
            print("opp_featuretool: Error: XML error in features file: ({})".format(e), file=sys.stderr)
            sys.exit(1)

        self.sortedFeatures = sorted(self.features.items(), key=lambda x:x[1].ord)


    ############################
    def readNedFoldersFile(self):
        # read nedfolders file:
        self.nedfolders = []

        emptyline = re.compile(r'^\s*$')
        check = re.compile(r'^\-?([a-zA-Z0-9_]+\.)*[a-zA-Z0-9_]+$')
        pkgchk = re.compile(r'^package\s+(([a-zA-Z0-9_]+\.)*[a-zA-Z0-9_]+);')
        try:
            ord = 0
            for line in self.args.nedfoldersfile:
                ord += 1
                line = line.rstrip('\n')
                if emptyline.match(line):
                    continue
                if not check.match(line):
                    print("opp_featuretool: Error: invalid line in .nedfolders:%d : '%s'" % (ord, line), file=sys.stderr)
                    sys.exit(1)
                else:
                    path = line.replace('.', '/')
                    prefix = ''
                    nedfilename = path+'/package.ned'
                    if os.path.isfile(nedfilename):
                        try:
                            with open(nedfilename, 'r') as nedfile:
                                for nedline in nedfile:
                                    m = pkgchk.match(nedline)
                                    if m:
                                        prefix = m.group(1)
                                        break
                        except IOError as e:
                            print("opp_featuretool: error occured when reading the " + nedfilename + ", ignored: ({})".format(e), file=sys.stderr)
                    self.nedfolders.append(NedFolder(line, path, prefix, ord))
        except IOError as e:
            print("opp_featuretool: error occured when reading the .nedfolders file: ({})".format(e), file=sys.stderr)
            sys.exit(1)


    ############################
    def readNedExclusionsFile(self):
        # read nedfolders file:
        self.nedfoldersExcluded = []

        if not os.path.isfile(self.args.nedexclusionsfile):
            if self.fixingMode or self.autoFixingMode:
                # print("opp_featuretool: Warning: the .nedexclusions file is missing.", file=sys.stderr)
                return
            else:
                # print("opp_featuretool: Error: the .nedexclusions file is missing.", file=sys.stderr)
                sys.exit(1)
        try:
            nedexclusionsfile = open(self.args.nedexclusionsfile, 'r')
        except IOError as e:
            print("opp_featuretool: .nedexclusions file error: {}".format(e), file=sys.stderr)
            sys.exit(1)

        check = re.compile(r'^([a-zA-Z0-9_]+\.)*[a-zA-Z0-9_]+$')
        try:
            ord = 0
            for line in nedexclusionsfile:
                ord += 1
                line = line.rstrip('\n')
                if not check.match(line):
                    if self.fixingMode:
                        print("opp_featuretool: Warning: invalid line in .nedexclusions:%d, removed: '%s'" % (ord, line), file=sys.stderr)
                        self.nedExclusionFileChanged = True
                    elif self.autoFixingMode:
                        print("opp_featuretool: Warning: invalid line in .nedexclusions:%d, ignored: '%s'" % (ord, line), file=sys.stderr)
                    else:
                        print("opp_featuretool: Error: invalid line in .nedexclusions:%d, '%s'" % (ord, line), file=sys.stderr)
                        sys.exit(1)
                else:
                    self.nedfoldersExcluded.append(line)
            nedexclusionsfile.close()
        except IOError as e:
            print("opp_featuretool: Error: I/O error while reading the .nedexclusions file: ({})".format(e), file=sys.stderr)
            sys.exit(1)


    ############################
    def writeNedExclusions(self):
        try:
            nedexclusionsfile = open(self.args.nedexclusionsfile, 'w')
            for nf in sorted(self.nedfoldersExcluded):
                nedexclusionsfile.write("%s\n" % (nf))
            nedexclusionsfile.close()
        except IOError as e:
            print("opp_featuretool: Error: I/O error while writing the .nedexclusions file: ({})".format(e), file=sys.stderr)
            sys.exit(1)


    ############################
    def writeFeatureState(self):
        try:
            DOMTree = xml.dom.minidom.parseString("<featurestates/>")
            featurestateDom = DOMTree.documentElement
            for fk, fs in sorted(self.featurestate.items(), key=lambda x:x[1].ord):
                oneFS = DOMTree.createElement("feature")
                oneFS.setAttribute("id", fs.id)
                oneFS.setAttribute("enabled", str(fs.enabled).lower())
                featurestateDom.appendChild(oneFS)
            fsFile = open(self.args.featurestatefile, 'w')
            DOMTree.writexml(fsFile, addindent="    ", newl="\n")
            fsFile.close()
        except IOError as e:
            print("error occured when write featurestate file: ({})".format(e), file=sys.stderr)
            sys.exit(1)


    ############################
    def readFeatureState(self):
        # read featurestate xml file
        self.featurestate = dict()

        if not os.path.isfile(self.args.featurestatefile):
            if (self.fixingMode or self.autoFixingMode):
                # print("opp_featuretool: Warning: the .featurestate file does not exists. Using defaults.", file=sys.stderr)
                # generate default featurestate
                for fk, feature in self.sortedFeatures:
                    fs = FeatureState(feature.id, feature.initiallyEnabled, feature.ord)
                    self.featurestate[fk] = fs

                if self.fixingMode:
                    self.fsChanged = True
            else:
                print("opp_featuretool: Error: the .featurestate file does not exists.", file=sys.stderr)
                sys.exit(1)
        else:
            try:
                fsFile = open(self.args.featurestatefile, 'r')
            except IOError as e:
                print("opp_featuretool: Error: I/O error while reading the .featurestate file: {}".format(e), file=sys.stderr)
                sys.exit(1)

            if os.stat(self.args.featurestatefile).st_size == 0:
                return
            try:
                DOMTree = xml.dom.minidom.parse(fsFile)
            except Exception as e:
                print("opp_featuretool: Error: XML error while reading the .featurestate file: ({})".format(e), file=sys.stderr)
                print("To fix it: Repair the file by hand, or delete '" + self.args.featurestatefile + "'", file=sys.stderr)
                sys.exit(1)

            fsFile.close()

            featurestateDom = DOMTree.documentElement
            featurestatelistDom = featurestateDom.getElementsByTagName("feature")

            xord = len(self.features) + 1000
            for featureDom in featurestatelistDom:
                featureState = FeatureState.fromXML(featureDom, xord)
                if featureState.id in self.features:
                    featureState.ord = self.features[featureState.id].ord
                elif self.fixingMode:
                    print("opp_featuretool: Warning: FEATURESTATEFILE: Line '" + featureDom.toxml() + "' contains the unknown feature '" + featureState.id + "', removed", file=sys.stderr)
                    self.fsChanged = True
                    xord += 1
                    continue
                else:
                    print("opp_featuretool: Error: FEATURESTATEFILE: Line '" + featureDom.toxml() + "' contains the unknown feature '" + featureState.id + "'", file=sys.stderr)
                    sys.exit(1)

                if featureState.id in self.featurestate:
                    if self.fixingMode:
                        print("opp_featuretool: Warning: FEATURESTATEFILE: Line '" + featureDom.toxml() + "' contains the same feature more than one time '" + featureState.id + "', removed", file=sys.stderr)
                        self.fsChanged = True
                        continue
                    else:
                        print("opp_featuretool: Error: FEATURESTATEFILE: Line '" + featureDom.toxml() + "' contains the same feature more than one time '" + featureState.id + "'", file=sys.stderr)
                        sys.exit(1)
                else:
                    self.featurestate[featureState.id] = featureState


    ############################
    def isCxxSourceFolder(self, folder):
        if len(self.cppSourceRoots) == 0:
            return True
        for cppSourceRoot in self.cppSourceRoots:
            if folder.startswith(cppSourceRoot) and (len(folder) == len(cppSourceRoot) or folder[len(cppSourceRoot)] == '/'):
                return True;
        return False;


    ############################
    def getNedBasedCxxSourceFolders(self, feature):
        result = []
        for nedPackage in feature.nedPackages:
            for nedfolder in self.nedfolders:
                if nedfolder.isSubpackage(nedPackage):
                    packageSuffix = nedPackage[len(nedfolder.prefix):]
                    folder = nedfolder.path + '/' + packageSuffix.replace('.', '/')
                    if (os.path.exists(folder) and self.isCxxSourceFolder(folder)):
                        result.append(folder)
        return result


    ############################
    def doListCommand(self):
        self.doValidateCommand()
        # LIST command #
        if self.args.enabled:
            categ = "enabled "
            print("List of enabled features:")
        elif self.args.disabled:
            categ = "disabled "
            print("List of disabled features:")
        elif self.args.diff:
            categ = "changed "
            print("List of changed features:")
        else:
            categ = ""
            print("List of all features:")
            self.args.all = True

        cnt = 0
        for key, fs in sorted(self.featurestate.items(), key=lambda x:x[1].ord):
            if not fs.id in self.features:
                self.errorOccured = True
                print("  * %s%s *** unknown feature. Not found in feature file" % ('+' if fs.enabled else '-', fs.id))
            elif self.args.all or (self.args.enabled and fs.enabled) or (self.args.disabled and not fs.enabled) or (self.args.diff and fs.enabled != self.features[fs.id].initiallyEnabled):
                print("    %s%s" % ('+' if fs.enabled else '-', fs.id))
                cnt += 1
        for key, fi in self.sortedFeatures:
            if not key in self.featurestate:
                print("  * ?%s *** feature is missing from the .featurestate file" % key)
                self.errorOccured = True
        print(cnt, categ+"feature(s) found.")


    ############################
    def updateRequirementsOf(self, featureid, featureOnList, requirements):
        for req in self.features[featureid].requires:
            if not self.featurestate[req].enabled:
                if not req in requirements and not req in featureOnList:
                    self.updateRequirementsOf(req, featureOnList, requirements)
                requirements.add(req)
    ############################
    def updateRequirements(self, featureOnList, requirements):
        for featureid in featureOnList:
            self.updateRequirementsOf(featureid, featureOnList, requirements)
    ############################
    def doEnableCommand(self):
        self.doValidateCommand()
        # ENABLE command #
        if 'all' in self.args.features:
            if len(self.args.features) > 1:
                print("opp_featuretool: Error: 'all' should not be used while individual features are mentioned on the command line.", file=sys.stderr)
                sys.exit(1)
            else:
                for key,fs in self.sortedFeatures:
                    if not self.featurestate[key].enabled:
                        self.fsChanged = True
                        self.featurestate[key].enabled = True
        else:
            featureOnList = set()
            requirements = set()
            for key in self.args.features:
                if not key in self.features:
                    print("opp_featuretool: Error: unknown feature '%s'." % (key), file=sys.stderr)
                    sys.exit(1)
                if not self.featurestate[key].enabled:
                    featureOnList.add(key)
            self.updateRequirements(featureOnList, requirements)
            update = True
            if len(featureOnList) == 0:
                print("Feature(s) are already enabled.")
                sys.exit(0)
            print("Enabling feature(s): ", ", ".join(featureOnList))
            if len(requirements):
                if self.args.with_dependencies:
                    print("Required features that are enabled, too: ", ", ".join(sorted(requirements)))
                else:
                    print("Required features: ", ", ".join(sorted(requirements)))
                    update = queryYesNo("Enable these features?", default="yes")
            if update:
                featureOnList.update(requirements)
                for key in featureOnList:
                    self.featurestate[key].enabled = True
                    self.fsChanged = True


    ############################
    def updateDependsOf(self, featureid, featureOffList, dependencyList):
        for fk,f in self.sortedFeatures:
            if (featureid in f.requires) and self.featurestate[f.id].enabled and (not (f.id in dependencyList)) and (not (f.id in featureOffList)):
                self.updateDependsOf(f.id, featureOffList, dependencyList)
                dependencyList.add(f.id)
    ############################
    def updateDependencies(self, featureOffList, dependencyList):
        for featureid in featureOffList:
            self.updateDependsOf(featureid, featureOffList, dependencyList)
    ############################
    def doDisableCommand(self):
        self.doValidateCommand()
        # DISABLE command #
        if 'all' in self.args.features:
            if len(self.args.features) > 1:
                print("opp_featuretool: Error: 'all' should not be used while individual features are mentioned on the command line.", file=sys.stderr)
                self.errorOccured = True
                sys.exit(1)
            else:
                for key,fs in self.sortedFeatures:
                    if self.featurestate[key].enabled:
                        self.featurestate[key].enabled = False
                        self.fsChanged = True
        else:
            featureOffList = set()
            dependencyList = set()
            for key in self.args.features:
                if not key in self.features:
                    print("opp_featuretool: Error: unknown feature '%s'." % (key), file=sys.stderr)
                    self.errorOccured = True
                    sys.exit(1)
                if self.featurestate[key].enabled:
                    featureOffList.add(key)
            self.updateDependencies(featureOffList, dependencyList)
            update = True
            if len(featureOffList) == 0:
                print("All the selected features are already disabled.")
                sys.exit(0)
            print("Disabling feature(s): ", ", ".join(featureOffList))
            if len(dependencyList):
                if self.args.with_dependencies:
                    print("Dependent features that are disabled, too: ", ", ".join(sorted(dependencyList)))
                else:
                    print("Dependent features: ", ", ".join(sorted(dependencyList)))
                    update = queryYesNo("Disable these features, too?", default="yes")
            if update:
                featureOffList.update(dependencyList)
                for key in featureOffList:
                    self.featurestate[key].enabled = False
                    self.fsChanged = True


    ############################
    def doRepairCommand(self):
        # "creation of default featurestate file when it missing" for 'prepare' implemented in readFeatureState()
        self.doValidateCommand()


    ############################
    def doValidateCommand(self):
        # "syntax check in featurestate file" for 'validate' implemented in readFeatureState()

        featureMissed = False
        # check feature existing in FEATURESTATE file:
        for fid, feature in self.sortedFeatures:
            if not fid in self.featurestate:
                featureMissed = True
                fs = FeatureState(feature.id, feature.initiallyEnabled, feature.ord)
                self.featurestate[fid] = fs
                if self.fixingMode:
                    print("opp_featuretool: Warning: feature '%s' is missing from the FEATURESTATE file, adding it with default state." % (fid), file=sys.stderr)
                    self.fsChanged = True
                elif self.autoFixingMode:
                    print("opp_featuretool: Warning: feature '%s' is missing from the FEATURESTATE file, using the default state." % (fid), file=sys.stderr)
                else:
                    print("opp_featuretool: Error: feature '%s' is missing from the FEATURESTATE file." % (fid), file=sys.stderr)
                    sys.exit(1)

        # check dependencies:
        dependencyErrorOccured = False
        featureOnList = set()
        requirements = set()
        for fid, feature in self.sortedFeatures:
            if self.featurestate[fid].enabled:
                for r in feature.requires:
                    if not self.featurestate[r].enabled:
                        print("opp_featuretool: Warning: feature '%s' is required for '%s', but it is disabled." % (r, fid), file=sys.stderr)
                        featureOnList.add(r)
                        dependencyErrorOccured = True
        if len(featureOnList):
            self.updateRequirements(featureOnList, requirements)
            if len(requirements):
                print("opp_featuretool: Warning: these features are also required: ", ", ".join(requirements), file=sys.stderr)
            featureOnList.update(requirements)

        nedfolderErrorOccured = False
        for fid, feature in self.sortedFeatures:
            for np in feature.nedPackages:
                if self.featurestate[fid].enabled:
                    if np in self.nedfoldersExcluded:
                        # print("opp_featuretool: Warning: NED package '%s' is part of the enabled feature '%s', but it is excluded." % (np, fid), file=sys.stderr)
                        nedfolderErrorOccured = True
                else:
                    if not np in self.nedfoldersExcluded:
                        # print("opp_featuretool: Warning: NED package '%s' is part of the disabled feature '%s', but it is not excluded." % (np, fid), file=sys.stderr)
                        nedfolderErrorOccured = True
        if dependencyErrorOccured:
            if self.fixingMode:
                for key in featureOnList:
                    self.featurestate[key].enabled = True
                self.fsChanged = True
            else:
                print("opp_featuretool: <!> Error: feature dependency error(s) occured.", file=sys.stderr)
                sys.exit(1)
        if nedfolderErrorOccured:
            if self.fixingMode:
                self.fsChanged = True
            elif not self.autoFixingMode:
                print("opp_featuretool: Error: feature dependency error(s) occured in the .nedexclusions file.", file=sys.stderr)
                sys.exit(1)


    ############################
    def doPrintCommand(self):
        self.doValidateCommand()
        if self.args.srcpath == None:
            self.args.srcpath = self.cppSourceRoots[0]
        elif self.args.srcpath not in self.cppSourceRoots:
            print("opp_featuretool: Error: the selected '%s' source path is not specified in the .oppfeatures file. Choose any of ['%s']." % (self.args.srcpath, "','".join(self.cppSourceRoots)), file=sys.stderr)
            sys.exit(1)
        extraSourceFolders = []
        excludedExtraSourceFolders = []
        excludedSourceFolders = []
        compileFlags = []
        linkerFlags = []
        for fid,feature in self.sortedFeatures:
            if self.featurestate[fid].enabled:
                extraSourceFolders.extend(feature.extraSourceFolders)
                compileFlags.extend(feature.compileFlags)
                linkerFlags.extend(feature.linkerFlags)
            else:
                excludedExtraSourceFolders.extend(feature.extraSourceFolders)
                excludedSourceFolders.extend(self.getNedBasedCxxSourceFolders(feature))

        extraSourceFolders = ["-d"+x for x in extraSourceFolders]

        excludedSrcFolders = []
        s = self.args.srcpath+'/'
        for f in excludedSourceFolders + excludedExtraSourceFolders:
            if f.startswith(s):
                excludedSrcFolders.append("-X"+f[len(s):])

        #print(" ".join(extraSourceFolders)),    # //TODO how to enable extra source folders?
        print(" ".join(excludedSrcFolders), " ".join(compileFlags), " ".join(linkerFlags))


    ############################
    def run(self):
        self.errorOccured = False
        self.fsChanged = False
        self.features = dict()

        self.createParser()
        try:
            self.args = self.parser.parse_args()
        except IOError as e:
            print("opp_featuretool: Error: error while parsing the arguments: ({})".format(e))
            sys.exit(1)

        self.autoFixingMode = (self.args.command != "validate")
        self.fixingMode = (self.args.command == "repair")

        # read feature file
        self.readFeatures()

        # read nedfolders file:
        self.readNedFoldersFile()

        if self.args.command == 'reset':
            self.doResetCommand()

        # Read featurestate file #
        self.readFeatureState()

        # read nedexclusions file:
        self.readNedExclusionsFile()

        if self.args.command == 'list':
            self.doListCommand()
        elif self.args.command == 'validate':
            self.doValidateCommand()
        elif self.args.command == 'repair':
            self.doRepairCommand()
        elif self.args.command == 'reset':
            print("opp_featuretool: Error: reset command already processed", file=sys.stderr)
            sys.exit(1)
        elif self.args.command == 'enable':
            self.doEnableCommand()
        elif self.args.command == 'disable':
            self.doDisableCommand()
        elif self.args.command == 'makemakeargs':
            self.doPrintCommand()
        else:
            print("opp_featuretool: Error: unknown command '%s'" % self.args.command, file=sys.stderr)
            sys.exit(1)

        if self.fsChanged:
            print("opp_featuretool: .featurestate file updated.")
            self.writeFeatureState()

            self.nedfoldersExcluded = []
            for key, fs in sorted(self.featurestate.items(), key=lambda x:x[1].ord):
                enabled = False
                if fs.id in self.features and not fs.enabled:
                    self.nedfoldersExcluded.extend(self.features[fs.id].nedPackages)
            self.nedExclusionFileChanged = True

        if self.nedExclusionFileChanged:
            print("opp_featuretool: .nedexclusions file updated.")
            self.writeNedExclusions()

        if self.errorOccured:
            print("opp_featuretool: Error: an error ocurred", file=sys.stderr)
            sys.exit(1)


#####################################################
tool = FeatureTool()
tool.run()

