#!/bin/sh

usage ()
{
  echo "`basename $0`: post-process a shared library"
  echo "Usage: `basename $0` FILENAME"
}

# assert that we have one argument on the command line
if [ $# != 1 ]; then
  usage
  exit 1
fi

# set the context for the library on Security Enhanced Linux
if chcon --version >/dev/null 2>/dev/null ; then
  echo "chcon -t textrel_shlib_t $1"
  chcon -t textrel_shlib_t $1
fi

true

