#!/usr/bin/env python3

"""
This script can load .anf files and execute the chart scripts in them, independent of the IDE.
"""

import os
import sys
import glob
import argparse
from argparse import RawTextHelpFormatter
import traceback
import subprocess
import numpy as np
import pandas as pd
import xml.etree.ElementTree as ET
import matplotlib.pyplot as plt
from omnetpp.scave.analysis import *
from omnetpp.scave.impl_charttool import results, chart


def error(message):
    print("ERROR: " + message)
    sys.exit(1)

def run_chart_safe(analysis, chart, wd, workspace, extra_props=dict(), show=False):
    try:
        analysis.run_chart(chart, wd, workspace, extra_props, show)
    except Exception as e:
        print("Error in chart " + chart.name, file = sys.stderr)
        print(traceback.format_exc(), file = sys.stderr)
        return False
    return True

if __name__ == "__main__":

    parser = argparse.ArgumentParser(description=
        "Export images from OMNeT++ Analysis files (*.anf) and perform "
        "other tasks on them, without starting the IDE.\n"
        "This program can read and list the contents (input patterns and charts) "
        "of such files, and even execute the chart scripts.\n"
        "The native charts are 'emulated' using matplotlib.\n"
        "Use the -e flag to export all charts, or if specified, the selected chart, as image.\n"
        "NOTE: Exporting the charts this way does not (yet) take into account the exporting "
        "preferences configured in the IDE.",
        epilog="Some commands have additional arguments specific to them. For more info, see:\n"
        "opp_charttool COMMAND -h",
        formatter_class=RawTextHelpFormatter)


    subparsers = parser.add_subparsers(help='', dest='command', metavar='COMMAND')


    common_parser = argparse.ArgumentParser()
    common_parser.add_argument('-i', metavar='chart_index', type=int, nargs=1, help='The index of the chart to select (conflicts with -n)')
    common_parser.add_argument('-n', metavar='chart_name', type=str, nargs=1, help='The name of the chart to select (conflicts with -i, the first chart is selected when ambiguous)')
    common_parser.add_argument('-p', metavar='project_path', type=str, nargs='*', default=[], help='Adds a workspace path to filesystem directory mapping (format: "/project=.")')
    common_parser.add_argument('-w', metavar='workspace_directory', type=str, nargs=1, default=[None], help='The workspace directory. Acts as a fallback after -p. The input patterns are relative to this')
    common_parser.add_argument('-D', metavar='properties', dest='properties', type=str, nargs='*', default=[], help='Extra properties to pass to the chart script, format: key=value')
    common_parser.add_argument('anf_file', type=str, nargs=1, default="", help='The Analysis (.anf) file')


    info_parser = subparsers.add_parser('info', help='(default) Info about the analysis file', parents=[common_parser], add_help=False)


    run_parser = subparsers.add_parser('run', help='Run a selected chart', parents=[common_parser], add_help=False)


    imageexport_parser = subparsers.add_parser('imageexport', help='Export selected or all charts as image(s)', parents=[common_parser], add_help=False)
    imageexport_parser.add_argument('-f', metavar='format', dest='format', type=str, default='svg', help='The image format to export in')
    imageexport_parser.add_argument('-d', metavar='folder', dest='target_folder', type=str, default=None, help='The folder to export into')
    imageexport_parser.add_argument('-o', metavar='filename', dest='out_file', type=str, default=None, help='The filename to export as')

    imageexport_parser.add_argument('--width', metavar='width', type=float, default=None, help='The width of the image in inches')
    imageexport_parser.add_argument('--height', metavar='height', type=float, default=None, help='The height of the image in inches')
    imageexport_parser.add_argument('--dpi', metavar='dpi', type=int, default=None, help='The resolution of the image in dots per inch')


    dataexport_parser = subparsers.add_parser('dataexport', help='Export data of selected or all charts', parents=[common_parser], add_help=False)
    dataexport_parser.add_argument('-f', metavar='format', dest='format', type=str, default='csv', help='The data format to export in')
    dataexport_parser.add_argument('-d', metavar='folder', dest='target_folder', type=str, default=None, help='The folder to export into')
    dataexport_parser.add_argument('-o', metavar='filename', dest='out_file', type=str, default=None, help='The filename to export as')


    argv = sys.argv[1:]

    COMMANDS = ["info", "run", "imageexport", "dataexport"]
    if argv and argv[0] not in COMMANDS \
            and not argv[0].startswith("-") and argv[0].endswith(".anf"):
        argv = ["info"] + argv

    args = parser.parse_args(argv)

    if not args.command:
        parser.print_help()
        exit(1)

    if args.command not in COMMANDS:
        parser.print_help()
        error("Unknown command '%s'" % args.command)

    anf_file = args.anf_file[0]
    anf_dir = os.path.dirname(os.path.abspath(anf_file))

    analysis = load_anf_file(anf_file)

    if False: # debug output
        import json
        print(json.dumps(analysis, default=lambda obj: vars(obj), indent=4, separators=(',', ': ')))

    project_paths = dict([tuple(p.split('=', 1)) for p in args.p]) if args.p else dict()

    workspace_dir = args.w[0]
    if not workspace_dir:
        workspace_dir = Workspace.find_workspace()
        if not workspace_dir:
            workspace_dir = os.path.dirname(os.path.abspath(anf_file))
    workspace = Workspace(workspace_dir, project_paths)


    selected_charts = None

    if args.i and args.n:
        error("Do not use -i and -n together.")

    if args.i:
        selected_charts = [ analysis.charts[args.i[0]] ]
    elif args.n:
        for c in analysis.charts:
            if c.name == args.n[0]:
                selected_charts = [ c ]
                break
        if not selected_charts:
            error('No chart named "{}".'.format(args.n[0]))
    else: # neither -i nor -n given
        selected_charts = analysis.charts

    ok = True

    props = dict([i.split("=", 1) for i in args.properties])

    if args.command == 'info':
        print(anf_file + ":\n\n" + analysis.info())
    else:
        for chart in selected_charts:
            if args.command == 'run':
                print("Running:", chart.name)
                chart_ok = run_chart_safe(analysis, chart, anf_dir, workspace, show=True, extra_props=props)
            elif args.command == 'imageexport':
                print("Exporting:", chart.name)
                chart_ok = analysis.export_image(chart, anf_dir, workspace, enforce=False,
                                                format=args.format, target_folder=args.target_folder, filename=args.out_file,
                                                width=args.width, height=args.height, dpi=args.dpi,
                                                extra_props=props) is not None
            elif args.command == 'dataexport':
                print("Exporting:", chart.name)
                chart_ok = analysis.export_data(chart, anf_dir, workspace, enforce=False,
                                                format=args.format, target_folder=args.target_folder, filename=args.out_file,
                                                extra_props=props) is not None
            ok = ok and chart_ok

    if not ok:
        sys.exit(1)
