/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.omnetpp.ned.model.swig;

public class NEDGenerator {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected NEDGenerator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(NEDGenerator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      nedxmlJNI.delete_NEDGenerator(swigCPtr);
    }
    swigCPtr = 0;
  }

  public NEDGenerator() {
    this(nedxmlJNI.new_NEDGenerator(), true);
  }

  public void setIndentSize(int indentsize) {
    nedxmlJNI.NEDGenerator_setIndentSize(swigCPtr, indentsize);
  }

  public void setNewSyntax(boolean value) {
    nedxmlJNI.NEDGenerator_setNewSyntax(swigCPtr, value);
  }

  public String generate(NEDElement node, String indent) {
    return nedxmlJNI.NEDGenerator_generate(swigCPtr, NEDElement.getCPtr(node), indent);
  }

}
