/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.omnetpp.ned.model.swig;

class nedxmlJNI {

  static {
    try {
      System.loadLibrary("nedxml_engine");
    } catch (UnsatisfiedLinkError e) {
      System.err.println("Native code library failed to load. \n" + e);
      System.exit(1);
    }
  }

  public final static native long new_NEDElementUserData();
  public final static native void delete_NEDElementUserData(long jarg1);
  public final static native void delete_NEDElement(long jarg1);
  public final static native String NEDElement_className(long jarg1);
  public final static native String NEDElement_getTagName(long jarg1);
  public final static native int NEDElement_getTagCode(long jarg1);
  public final static native int NEDElement_getId(long jarg1);
  public final static native void NEDElement_setId(long jarg1, int jarg2);
  public final static native String NEDElement_getSourceLocation(long jarg1);
  public final static native void NEDElement_setSourceLocation(long jarg1, String jarg2);
  public final static native void NEDElement_applyDefaults(long jarg1);
  public final static native int NEDElement_getNumAttributes(long jarg1);
  public final static native String NEDElement_getAttributeName(long jarg1, int jarg2);
  public final static native int NEDElement_lookupAttribute(long jarg1, String jarg2);
  public final static native String NEDElement_getAttribute__SWIG_0(long jarg1, int jarg2);
  public final static native String NEDElement_getAttribute__SWIG_1(long jarg1, String jarg2);
  public final static native void NEDElement_setAttribute__SWIG_0(long jarg1, int jarg2, String jarg3);
  public final static native void NEDElement_setAttribute__SWIG_1(long jarg1, String jarg2, String jarg3);
  public final static native String NEDElement_getAttributeDefault__SWIG_0(long jarg1, int jarg2);
  public final static native String NEDElement_getAttributeDefault__SWIG_1(long jarg1, String jarg2);
  public final static native long NEDElement_getParent(long jarg1);
  public final static native long NEDElement_getFirstChild(long jarg1);
  public final static native long NEDElement_getLastChild(long jarg1);
  public final static native long NEDElement_getNextSibling(long jarg1);
  public final static native long NEDElement_getPrevSibling(long jarg1);
  public final static native void NEDElement_appendChild(long jarg1, long jarg2);
  public final static native void NEDElement_insertChildBefore(long jarg1, long jarg2, long jarg3);
  public final static native long NEDElement_removeChild(long jarg1, long jarg2);
  public final static native long NEDElement_getFirstChildWithTag(long jarg1, int jarg2);
  public final static native long NEDElement_getNextSiblingWithTag(long jarg1, int jarg2);
  public final static native int NEDElement_getNumChildren(long jarg1);
  public final static native int NEDElement_getNumChildrenWithTag(long jarg1, int jarg2);
  public final static native long NEDElement_getFirstChildWithAttribute__SWIG_0(long jarg1, int jarg2, String jarg3, String jarg4);
  public final static native long NEDElement_getFirstChildWithAttribute__SWIG_1(long jarg1, int jarg2, String jarg3);
  public final static native long NEDElement_getParentWithTag(long jarg1, int jarg2);
  public final static native void NEDElement_setUserData(long jarg1, long jarg2);
  public final static native long NEDElement_getUserData(long jarg1);
  public final static native void set_np(long jarg1);
  public final static native long get_np();
  public final static native long new_NEDParser();
  public final static native void delete_NEDParser(long jarg1);
  public final static native void NEDParser_setParseExpressions(long jarg1, boolean jarg2);
  public final static native void NEDParser_setStoreSource(long jarg1, boolean jarg2);
  public final static native boolean NEDParser_parseFile(long jarg1, String jarg2);
  public final static native boolean NEDParser_parseText(long jarg1, String jarg2);
  public final static native long NEDParser_getTree(long jarg1);
  public final static native void NEDParser_error(long jarg1, String jarg2, int jarg3);
  public final static native long new_NEDGenerator();
  public final static native void delete_NEDGenerator(long jarg1);
  public final static native void NEDGenerator_setIndentSize(long jarg1, int jarg2);
  public final static native void NEDGenerator_setNewSyntax(long jarg1, boolean jarg2);
  public final static native String NEDGenerator_generate(long jarg1, long jarg2, String jarg3);
  public final static native void delete_NEDElementFactory(long jarg1);
  public final static native long NEDElementFactory_getInstance();
  public final static native long NEDElementFactory_createNodeWithTag__SWIG_0(long jarg1, String jarg2);
  public final static native long NEDElementFactory_createNodeWithTag__SWIG_1(long jarg1, int jarg2);
}
