#
# Global definitions
#
OMNETPP_ROOT=..\..

!include $(OMNETPP_ROOT)\configuser.vc

#
# Local definitions
#
BASEPKG = org.omnetpp.ned.model
JMODELPKG = $(BASEPKG).pojo
JMODELDIR = src\$(JMODELPKG:.=\)

#
# Targets
#
all: genjava

genjava:
	-mkdir $(JMODELDIR) 2>nul
	$(PERL) etc/dtdclassgen.pl $(OMNETPP_ROOT)/doc/etc/ned2.dtd $(BASEPKG) $(JMODELPKG) $(JMODELDIR)

clean:
	-del $(JMODELDIR)\*.java 2> nul

