#
# Global definitions
#
!include ..\..\configuser.vc

#
# NOTE: an 'all: plove.bat' rule wouldn't be good, wouldn't overwrite
#       stock plove.bat right after installation
#

all:
	echo @$(WISH:/=\) -f $(OMNETPP_SRC_DIR)/plove/plove > plove.bat
        copy plove.bat $(OMNETPP_BIN_DIR:/=\)

plove.bat:
	echo @$(WISH:/=\) -f $(OMNETPP_SRC_DIR)/plove/plove > plove.bat
        copy plove.bat $(OMNETPP_BIN_DIR:/=\)

depend:

clean:

# DO NOT DELETE THIS LINE -- make depend depends on it.
