/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.omnetpp.scave.engine;

public class FileList {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected FileList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(FileList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ScaveEngineJNI.delete_FileList(swigCPtr);
    }
    swigCPtr = 0;
  }

        public File[] toArray() {
            int sz = (int)size();
            File[] array = new File[sz];
            for (int i=0; i<sz; i++)
                array[i] = get(i);
            return array;
        }

  public FileList() {
    this(ScaveEngineJNI.new_FileList__SWIG_0(), true);
  }

  public FileList(long arg0) {
    this(ScaveEngineJNI.new_FileList__SWIG_1(arg0), true);
  }

  public long size() {
    return ScaveEngineJNI.FileList_size(swigCPtr);
  }

  public boolean isEmpty() {
    return ScaveEngineJNI.FileList_isEmpty(swigCPtr);
  }

  public void clear() {
    ScaveEngineJNI.FileList_clear(swigCPtr);
  }

  public void add(File x) {
    ScaveEngineJNI.FileList_add(swigCPtr, File.getCPtr(x));
  }

  public File get(int i) {
    long cPtr = ScaveEngineJNI.FileList_get(swigCPtr, i);
    return (cPtr == 0) ? null : new File(cPtr, false);
  }

  public void set(int i, File x) {
    ScaveEngineJNI.FileList_set(swigCPtr, i, File.getCPtr(x));
  }

}
