/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.omnetpp.scave.engine;

public class ResultItem {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ResultItem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ResultItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ScaveEngineJNI.delete_ResultItem(swigCPtr);
    }
    swigCPtr = 0;
  }

  public void setRun(Run value) {
    ScaveEngineJNI.set_ResultItem_run(swigCPtr, Run.getCPtr(value));
  }

  public Run getRun() {
    long cPtr = ScaveEngineJNI.get_ResultItem_run(swigCPtr);
    return (cPtr == 0) ? null : new Run(cPtr, false);
  }

  public String getModuleName() {
    return ScaveEngineJNI.ResultItem_getModuleName(swigCPtr);
  }

  public String getName() {
    return ScaveEngineJNI.ResultItem_getName(swigCPtr);
  }

  public ResultItem() {
    this(ScaveEngineJNI.new_ResultItem(), true);
  }

}
