/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.omnetpp.scave.engine;

public class StringMap {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected StringMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ScaveEngineJNI.delete_StringMap(swigCPtr);
    }
    swigCPtr = 0;
  }

  public StringMap() {
    this(ScaveEngineJNI.new_StringMap__SWIG_0(), true);
  }

  public StringMap(StringMap arg0) {
    this(ScaveEngineJNI.new_StringMap__SWIG_1(StringMap.getCPtr(arg0)), true);
  }

  public long size() {
    return ScaveEngineJNI.StringMap_size(swigCPtr);
  }

  public boolean empty() {
    return ScaveEngineJNI.StringMap_empty(swigCPtr);
  }

  public void clear() {
    ScaveEngineJNI.StringMap_clear(swigCPtr);
  }

  public String get(String key) {
    return ScaveEngineJNI.StringMap_get(swigCPtr, key);
  }

  public void set(String key, String x) {
    ScaveEngineJNI.StringMap_set(swigCPtr, key, x);
  }

  public void del(String key) {
    ScaveEngineJNI.StringMap_del(swigCPtr, key);
  }

  public boolean has_key(String key) {
    return ScaveEngineJNI.StringMap_has_key(swigCPtr, key);
  }

}
