/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.25
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package org.omnetpp.scave.engine;

public class StringVector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected StringVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(StringVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public void delete() {
    if(swigCPtr != 0 && swigCMemOwn) {
      swigCMemOwn = false;
      ScaveEngineJNI.delete_StringVector(swigCPtr);
    }
    swigCPtr = 0;
  }

  public StringVector() {
    this(ScaveEngineJNI.new_StringVector__SWIG_0(), true);
  }

  public StringVector(long arg0) {
    this(ScaveEngineJNI.new_StringVector__SWIG_1(arg0), true);
  }

  public long size() {
    return ScaveEngineJNI.StringVector_size(swigCPtr);
  }

  public boolean isEmpty() {
    return ScaveEngineJNI.StringVector_isEmpty(swigCPtr);
  }

  public void clear() {
    ScaveEngineJNI.StringVector_clear(swigCPtr);
  }

  public void add(String x) {
    ScaveEngineJNI.StringVector_add(swigCPtr, x);
  }

  public String get(int i) {
    return ScaveEngineJNI.StringVector_get(swigCPtr, i);
  }

  public void set(int i, String x) {
    ScaveEngineJNI.StringVector_set(swigCPtr, i, x);
  }

}
