//
// This file is part of an OMNeT++/OMNEST simulation example.
//
// Copyright (C) 2010 OpenSim Ltd.
//
// This file is distributed WITHOUT ANY WARRANTY. See the file
// `license' for details on this and other legal matters.
//


//
// Answers HTTP GET requests that arrive to the built-in web server
// of the simulation, and returns KML or HTML documents.
//
simple KmlHttpServer
{
    @display("i=block/socket");
}



