/*--------------------------------------------------------------*
  Copyright (C) 2006-2020 OpenSim Ltd.

  This file is distributed WITHOUT ANY WARRANTY. See the file
  'License' for details on this and other legal matters.
*--------------------------------------------------------------*/

package org.omnetpp.scave.model;

import org.eclipse.core.runtime.Assert;
import org.omnetpp.scave.engine.ResultFileManager;

// TODO: delete, use the one generated by SWIG
public enum ResultType {
    SCALAR(ResultFileManager.SCALAR),
    PARAMETER(ResultFileManager.PARAMETER),
    VECTOR(ResultFileManager.VECTOR),
    HISTOGRAM(ResultFileManager.HISTOGRAM),
    STATISTICS(ResultFileManager.STATISTICS);

    int value;

    private ResultType(int v) {
        value = v;
    }

    public int getValue() {
        return value;
    }

    public static ResultType asResultType(int internalResultType) {
        if (internalResultType == ResultFileManager.SCALAR)
            return SCALAR;
        if (internalResultType == ResultFileManager.PARAMETER)
            return PARAMETER;
        else if (internalResultType == ResultFileManager.VECTOR)
            return VECTOR;
        else if (internalResultType == ResultFileManager.STATISTICS)
            return STATISTICS;
        else if (internalResultType == ResultFileManager.HISTOGRAM)
            return HISTOGRAM;
        else {
            Assert.isTrue(false, "Unknown internal ResultType:"+internalResultType);
            return null;
        }
    }

}
