/* dummy header -- it's here because lex.matchexpressionyy.cc (generated by flex 
   from matchexpression.lex) wants to include unistd.h, which completely unnecessary 
   but fails on Windows which has no unistd.h. --Andras 
*/